lib/utils.js, test/acceptance/utils.js
I use a lot of prototype-less objects (`Object.create(null)`) in my code. Sadly, mocha fails to display the diff when an error occurs.
=> utils.stringify should handle objects without an Object prototype

lib/reporters/html.js
=> Prevent multiple 'grep=' querystring params in html reporter

bin/_mocha
For issue https://github.com/mochajs/mocha/issues/333
Note: this does not address the issues with `mocha interfaces` and other non-test commands, because if we actually waited for the output to get flushed, the default `mocha` action (running tests) would start to occur. Refactoring needs to happen to fix this.
But this solves the output being cut when the STDIO is async, which is the main use-case.
=> Fix test running output truncation on async STDIO

lib/reporters/base.js, lib/utils.js, test/acceptance/utils.js
This PR should fix some issues in the __Diff viewer__ that depends on the `stringify` function
for example: 
* #1229:
```js
expect(-0).eql(0);  // assert with empty representation
expect({ n: -0 }).eql({ n: 0 });  // same with the canonical behavior
expect(-0).eql(1);
/* representation:
+expected: 1
-actual: 0
```
* buffer diff #1132 :
```js
expect(new Buffer([0x01])).eql(new Buffer([0x02])); // asset with empty representation
```
* Infinity,NaN:
```js
expect({ infi: Infinity, nan: NaN }).eql({});
/* representation:
-{
-  "infi": null
-  "nan": null
-}
this happens because JSON.stringify(NaN/Infinity) returns `null`(could fixed with `replacer` function)
```
* Date, RegExp, Function and Circular represents as a string:
```js
var actual = {
string: "string",
regex: /^[a-z]/,
func: …
```
=> [Fix]: Diff viewer(#1229, #1132, ...)

test/runnable.js
just a slight test improvement I suggested at #1410.
=> in runnable test, compare to undefined error's message rather than a literal

Makefile, lib/mocha.js, test/mocha.js
=> In .run(fn), check if fn exists before executing the callback, fixes #1496

lib/context.js, lib/pending.js, lib/runnable.js, lib/runner.js, test/acceptance/pending.js
Opening a PR to get some feedback for this implementation.
=> Allow skip from test context for #332

lib/runner.js, test/runner.js
=> Improve error output when a test fails with a non-error

.travis.yml
The docker containers are far more abundant and
offer vastly reduced boot time and some increased
CPU power. As long as you don't require 'sudo',
this is the way to go.
http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
=> travis: use docker containers

lib/reporters/base.js, package.json
This replaces https://github.com/mochajs/mocha/pull/1497.
Detecting whether a terminal is TTY is not enough
to ensure that it can also support color.
This module, supports-color, is a wholistic solution
which captures the greatest range of possible terminals
with the greatest accuracy. The module is extremely
lightweight and does not represent a burdern to Mocha
users.
=> reporters/base: use supports-color to detect colorable term

Makefile, bin/_mocha, lib/interfaces/bdd.js, lib/interfaces/common.js, lib/interfaces/qunit.js, lib/interfaces/tdd.js, lib/mocha.js, lib/runner.js, lib/suite.js, mocha.js, test/delay/delay.js
This allows delayed root suite execution with flag `--delay`.
While I was in there I refactored some to reduce LOC (see `lib/interfaces/common.js`).
It works like this:
- if you specify `--delay`, the Runner will wait until the root suite has emitted a `run` event
- in addition, `--delay` will put a function `run()` in the global context
- once you have done your async business and generated your suite(s), call `run()`.
- this emits the event on the root suite, and it is executed.
See the [unit test](/boneskull/mocha/blob/be02d437cfaea67c177f7422e9bde97bbd2c66dd/test/delay/delay.js) for an example.
Also rebuilt `/mocha.js`.
=> add ability to delay root suite; closes #362, closes #1124

lib/utils.js, mocha.js
fix issue #1558 and run build for browser version (`mocha.js`)
=> fix(utils): issue #1558 + make

lib/reporters/base.js, lib/utils.js, mocha.js
Fixing a few issues caused by recent commits that break when mocha.js is loaded in the browser:
https://github.com/mochajs/mocha/commit/eab389f3f106290e8386520a2f3b8206c18c486e introduced `require('supports-color')`, which is not available in the browser.
https://github.com/mochajs/mocha/commit/00ef54cd41d46b1c29358942dc0874e2ae7da0ff added `if(Buffer && ...)` usage, which doesn't work in browsers.
=> Fixing errors that prevent mocha.js from loading in the browser - fixes #1558

Makefile, lib/runnable.js, lib/runner.js, test/acceptance/failing/uncaught-and-async.js
This improves on https://github.com/mochajs/mocha/pull/1540 From that thread:
Given the following test, which only has one spec:
``` javascript
it('fails exactly once when a global error is thrown first', function(done) {
setTimeout(function() {
throw new Error('global error');
setTimeout(function() {
done(new Error('test error'));
}, 0);
}, 0);
});
```
You get two two failures:
``` javascript
$ ./bin/mocha pr1540.js
․․
0 passing (6ms)
2 failing
1)  fails exactly once:
Error: test error
at null._onTimeout (/Users/danielstjules/git/mocha/pr1540.js:10:12)
at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
at timers.js:117:18
at process._tickCallback (node.js:415:13)
at process._tickFromSpinner (node.js:390:15)
2)  fails exactly once:
Error: test error
at null._onTimeout …
```
=> Ignore asynchronous failures after spec resolution

Makefile, lib/runnable.js, test/acceptance/failing/uncaught-and-async.js
`Runner#uncaught` labels the currently-executing `Runnable` instance as
"failed" in response to uncaught exceptions. If the the `Runnable`
instance later signals failure through Mocha's asynchronous interface,
the `Runner` counts this as a distinct test failure. Consequently,
reporters generate inaccurate reports (and in some cases, this triggers
uncaught exceptions causing the process itself to crash).
When a runnabe completes, explicitly check that it has not already been
labeled as failing before reporting any additional errors.
=> Ignore asynchronous errors after global failure

bin/_mocha, lib/mocha.js, support/tail.js, test/grep.js
Finished https://github.com/mochajs/mocha/pull/632, which had already been +1'ed. This also updates the names to be in line with the following comment: https://github.com/mochajs/mocha/pull/632#issuecomment-54741917
``` javascript
$ cat example.js
it('foo()', function(done) {
done();
});
$ ./bin/mocha --grep 'foo.*' example.js
․
1 passing (3ms)
$ ./bin/mocha --fgrep 'foo.*' example.js
0 passing (1ms)
$ ./bin/mocha -i --fgrep 'foo.*' example.js
․
1 passing (3ms)
$ ./bin/mocha --fgrep 'foo' example.js
․
1 passing (3ms)
```
=> Add --fgrep. Use grep for RegExp, fgrep for str

bin/mocha
The recent commit 1430c2b5102e9d355119a643e9b2be2e76e91d1f inadvertently broke the ability pass arguments to node/iojs before running mocha -- note that arguments intended for the executable are _prepended_ to args; the previous commit assumes that args[0] will be the executable, but that is only correct if no args intended for the executable have been `unshift`ed onto args.
So, if you try, for instance:
`mocha --harmony ...`
... you'll get an `ENOENT` error as `spawn` tries to execute a file named `--harmony`.
See #1548 for the origin of this issue.
=> Fix passing of args intended for node/iojs.

bin/_mocha, lib/mocha.js, lib/runner.js, lib/utils.js, mocha.js, test/browser/stack-trace.html, test/browser/stack-trace.js, test/runner.js, test/utils.js
following #545 discussion.
I added a stack-trace filter(based on @rstacruz `mocha-clean` module), ran `make` and added tests too.
If for some reason someone want to stay with full stack-trace, just run mocha with the `--full-trace` flag
=> feat(runner/stack-trace): solve issue #545 + test

README.md
A few notes:
* homebrew doesn't have the `make` package anymore
* homebrew requires Xcode CLI tools (it even installs it for you!), so having homebrew implies you have make
* Ubuntu doesn't come with make by default unless you install `build-essential`
=> Site readme: update instructions for 2015

lib/reporters/dot.js, lib/reporters/spec.js
Fixes https://github.com/mochajs/mocha/issues/1574
```
$ cat example.js
it('test', function() {});
it('test2', function() {});
it('test3', function(done) { setTimeout(done, 180); });
$ ./bin/mocha example.js > output.txt
<- two spaces here
․․․
3 passing (185ms)
$ ./bin/mocha --reporter spec example.js > output.txt
✓ test <- space here
✓ test2 <- another space
✓ test3 (182ms)
3 passing (185ms)
```
After the PR:
```
$ ./bin/mocha example.js > output.txt
․․․
3 passing (185ms)
$ ./bin/mocha --reporter spec example.js > output.txt
✓ test
✓ test2
✓ test3 (182ms)
3 passing (187ms)
```
=> Remove trailing whitespace from reporter output

bin/_mocha, bin/mocha
As per https://iojs.org/en/es6.html this is a (prefered) synonym for --harmony.
=> support --es_staging flag for iojs

lib/reporters/templates/style.html
There are more improvements that could be made, for example it'd be nice to be able to collapse the menu all together, but at least the fixes the current issue I'm having which is, if my file names are long, the menu covers up the content and I am not able to scroll so my content is completely hidden.
=> fix issue where menu overlaps content.

lib/reporters/templates/menu.jade
The icon link on a html-cov reporter leads to a 404'd page I changed it to go to the website instead.
=> Fixed broken link on html-cov reporter

lib/runner.js, lib/utils.js, mocha.js
Fixes #1606
``` html
<html>
<head>
<meta charset="utf-8">
<title>Mocha Tests</title>
<link rel="stylesheet" href="mocha.css" />
</head>
<body>
<div id="mocha"></div>
<script src="mocha.js"></script>
<script>mocha.setup('bdd')</script>
<script>
it('test', function() {
throw new Error('uh oh!');
});
</script>
<script>
mocha.run();
</script>
</body>
</html>
```
**Before**
**After**
Edit: Ugly PR screenshots :(
=> Fix 1606: fix err handling in IE <= 8 and non-ES5 browsers

lib/utils.js, mocha.js, test/utils.js
Fixes https://github.com/mochajs/mocha/issues/1556
``` html
<html>
<head>
<meta charset="utf-8">
<title>Mocha Tests</title>
<link rel="stylesheet" href="mocha.css" />
</head>
<body>
<div id="mocha"></div>
<script src="mocha.js"></script>
<script>mocha.setup('bdd')</script>
<script>
it(
'test case',
function ()
{
say('hi!');
}
);
</script>
<script>
mocha.checkLeaks();
mocha.globals(['jQuery']);
mocha.run();
</script>
</body>
</html>
```
**Before**
**After**
=> Fix 1556: Update utils.clean to handle newlines in func declarations

bin/_mocha
This is for https://github.com/mochajs/mocha/issues/1585
After merging, I think it'd be a good idea to push a new patch release, since both 2.2.0/2.2.1 broke backwards compatibility for those relying on `_mocha` being executable.
To show that it's compatible with https://github.com/mochajs/mocha/commit/1430c2b5102e9d355119a643e9b2be2e76e91d1f
``` javascript
$ cat example.js
it('test', function() {
var gen = function*() {};
});
$ node --version
v0.12.0
$ ./bin/mocha --harmony-generators example.js
․
1 passing (4ms)
$ nvm use 0.10
Now using node v0.10.20
$ /Users/danielstjules/.nvm/versions/node/v0.12.0/bin/node ./bin/mocha --harmony-generators example.js
․
1 passing (5ms)
$ ./bin/mocha --harmony-generators example.js
Error: unrecognized flag --harmony-generators
Try --help for options …
```
=> Fix 1585: make _mocha executable again

lib/reporters/base.js, test/reporters/base.js
Ignore **showDiff** only if it's explicitly set to `false`.
see #1614 , #810
=> fix(reporter/base): explicitly ignore showDiff #1614

lib/reporters/base.js, test/reporters/base.js
The current implementation assumes that the first line of the err.stack is the error message. This is not the case for Safari. When using Mocha with a different HTML generator (e.g. Consolify) this produces weirdly formatted output with no error message.
I don't know how to come up with a test case for this. Please advise if there is anything I can provide.
The attached screenshot was produced with `mochify --consolify runner.html`.
=> fix(reporter/base): don't assume error message is first line of stack

bin/mocha
This allows the passing of the `--allow-natives-syntax` flag into the node binary.
[Some literature about allow-natives-syntax](http://dailyjs.com/2014/06/26/optimization-killers/)
=> Pass `--allow-natives-syntax` flag to node.

lib/runnable.js, test/runnable.js
closes #1644
I'm not sure if the error should be thrown or passed to something—let me know if it needs changing.
=> Throw an exception when timeout too large.

lib/reporters/base.js, lib/utils.js, test/reporters/base.js
Follow [1241 discussion](https://github.com/mochajs/mocha/issues/1241#issuecomment-92979416), this PR fix the regression of "strings diff", and solved #1241 as well.
/cc @caseywebdev @domenic
=> fix(reporter/base): issue #1241

lib/reporters/base.js
This fixes diffs being unnecessarily hard to read:
Before
After
Others are experiencing the same issue with standard terminal color schemes too:  https://github.com/mochajs/mocha/issues/1200#issuecomment-59562618
- Fixes #802
- Fixes #1200
- Fixes #1212 for diff output
=> Fix diff colors

lib/mocha.js, lib/runnable.js, lib/runner.js, support/tail.js, test/runnable.js, test/runner.js
- added allowUncaught option (#553)
- allows unhandled exceptions to propagate in the browser
- added tests for allowUncaught option
- global error handler prints to dom with allowUncaught
=> Added option to allow unhandled exceptions to propagate in the browser (rel #1659)

package.json, test/integration/fixtures/diffs/output
`jsdiff` v1.4.0 contains a fix for https://github.com/kpdecker/jsdiff/issues/14.  Upgrading will display multi-line diffs in the same standard order as `diff`, `git`, etc:
```diff
- actual / removed
+ expected / added
```
The current order is unintuitive which makes it harder to read at a glance:
```diff
+ expected / added
- actual / removed
```
Supersedes #1647.  cc @danielstjules @boneskull
=> Upgrade jsdiff to v1.4.0

lib/utils.js
I receive the error `ReferenceError: location is not defined` when running Mocha tests via Gulp. I'm using jsdom to mock the `document` and `window`, which is resulting in the global `location` being undefined unless I explicitly do `global.location = '{};` (or utilize this fix).
Fix of PR #1653 
CC @dasilvacontin
=> fix 'location is not defined' error

bin/_mocha, bin/mocha
Hello, I think this option can be useful as I've had to use it. Thx.
=> Add support of --harmony_arrow_functions V8 option

lib/reporters/json-stream.js
Extremely useful for running mocha on a CI server. The JSON reporter already has it, just updating the stream reporter.
=> Add stack to json-stream reporter

bin/mocha
This adds support for both hyphen and underscored flags. (at least a few of them)
Here's my reasoning: I'm trying to run CI tests against several versions of node. (0.10, 0.11, 0.12 and iojs to be precise) I'm using generators in my code, so:
* iojs breaks if I add `--harmony-generators`
* 0.11 and 0.12 require `--harmony-generators`
* 0.10 doesn't support generators at all, but I'm using gnode as a last-resort fallback
Rather than doing fancy "version sniffing", I've opted to use a clever shell script to determine if the `node` executable supports the generators flag, and using that to make my determination: 
```sh
$ node --v8-options | grep generators | cut -d ' ' -f 3
--harmony_generators
```
Unfortunately, passing this value directly to `mocha` breaks, since `v8-options` uses the …
=> Add support for some underscored harmony flags as well

lib/reporters/html.js, mocha.css
For the next version of the [Unexpected](https://github.com/sunesimonsen/unexpected/tree/v5) assertion library we're focusing on adding colored object diffs to error messages in "deep equal" and related cases. We have reached the limits of mocha's current approach with serializing `err.actual` and `err.expected` as JSON and then doing a line-based diff. It imposes too many restrictions on the quality of the output, especially when attempting to shoehorn other types of nested diffs (eg. binary `Buffer` or `Uint8Array`) into the resulting output.
Also, we have implemented a [lightweight type system](https://github.com/sunesimonsen/unexpected/blob/v5/lib/types.js) that allows "userland" to introduce new types and control exactly how they they equal, inspect and diff. It's awkward to make …
=> HTML reporter: Allow the error to contain a formatted HTML error message

HISTORY.md
was trying to figure out what changed, so i manually made this.
see: https://github.com/rstacruz/mocha/blob/patch-1/HISTORY.md
h/t [gh-annotate](https://www.npmjs.com/package/gh-annotate)
=> HISTORY: improve 2.2.5 changelog

lib/runner.js, test/runner.js
When passing errors through between frames, AssertionErrors and the like will fail an instanceof check against Error. We need a compatible check. According to [Mozilla Error Docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/message), Error prototype will always have message defined.
All tests pass: https://travis-ci.org/outdooricon/mocha/builds/67555897
It's worth noting that this currently prevents us from upgrading the Konacha project to use latest Mocha.
=> Add cross-frame compatible Error checking for fail

lib/reporters/html.js, test/browser/ui.html, test/browser/ui.js
=> Escape test/suite title for re in html reporter

bin/options.js
The current parsing of options does not allow spaces within an option so this fixes that. This is particularly useful in the case of reporter options where a custom reporter may want to accept a string option that contains a space.
See https://github.com/adamgruber/mochawesome/issues/20 for an example.
This patch would require any spaces to be escaped like `--option option\ with\ spaces`
=> support escaped spaces in cli options

lib/utils.js, test/acceptance/utils.js
Some older JS engines, such as PhantomJS, return the `window` object instead of "[object Null]", as would be expected here, crashing the test runner.
=> Explicitly check `null` and `undefined` values in exports.type

index.html, index.md
This refers to the `allowUncaught` method added in #1662.
=> Add note on allowUncaught method in the browser

bin/mocha
This prevents an infinite loop when the child process (the target of the runner, ie your tests) installs a SIGINT / SIGTERM handler. You might want to do this, for example, if you need to ensure clean shutdown of your tests when the user presses Ctrl+C. I ran into this problem when spawning a subprocess from the setup portion of my tests, and trying to capture SIGINT in the test suite.
=> Stop runner sending SIGINT to itself from within SIGINT handler

bin/_mocha
Previously "mocha --reporter-options foo" would blow up because an equal sign is required. This is quite unhandy for reporters that need to accept boolean (flag-ish) options.
This commit changes that so that a value-less reporter option will be interpreted as having a value of true.
This means that --reporter-options foo=bar,quux will turn into { foo: 'bar', quux: true }
=> _mocha: Allow boolean --reporter-options

lib/hook.js, lib/reporters/dot.js, lib/reporters/landing.js, lib/reporters/list.js, lib/reporters/min.js, lib/reporters/nyan.js, lib/reporters/progress.js, lib/reporters/spec.js, lib/reporters/xunit.js, lib/runnable.js, lib/runner.js, lib/suite.js, lib/test.js, package.json, support/compile.js
cc @boneskull @jbnicolai 
Resolves https://github.com/mochajs/mocha/issues/1728.
Depends on merging https://github.com/mochajs/mocha/pull/1727 because it pulls in an npm dependency; uses style from https://github.com/mochajs/mocha/pull/1750
=> Replace __proto__ references with inherits module

Makefile
Whoops, left this in during the Browserify transition.
=> Remove TODO from Browserify transition

lib/runner.js
The TypeScript repo is running into some scalability issues with Mocha. We pinned down the problem in this line of code https://github.com/mochajs/mocha/blob/master/lib/runner.js#L541. It does a huge recursive loop if there are is a large amount of test suites and thus causing a maximum call stack error. 
This PR fixes that problem.
Related issue in TypeScript repo:
https://github.com/Microsoft/TypeScript/pull/3511
=> Maximum call stack issue for large test suite

support/browser-entry.js
Fixes: #1789
When running mocha in the browser you get a crash in the following code:
```js
if (isatty) {
exports.window.width = process.stdout.getWindowSize
? process.stdout.getWindowSize(1)[0]
: tty.getWindowSize()[1];
}
```
That is because we need to shim the process.stdout before requiring
mocha from browser-entry.js, I fixed that by moving it to the top of the
file.
=> Fix: html-runner crashing because of missing process.stdout shim

lib/runner.js, test/runner.js
=> Decorate failed hook titles with test title

lib/runner.js, test/integration/fixtures/hooks/after.hook.async.error.js, test/integration/fixtures/hooks/after.hook.error.js, test/integration/fixtures/hooks/afterEach.hook.async.error.js, test/integration/fixtures/hooks/afterEach.hook.error.js, test/integration/fixtures/hooks/before.hook.async.error.js, test/integration/fixtures/hooks/before.hook.error.js, test/integration/fixtures/hooks/beforeEach.hook.async.error.js, test/integration/fixtures/hooks/beforeEach.hook.error.js, test/integration/fixtures/hooks/multiple.hook.async.error.js, test/integration/fixtures/hooks/multiple.hook.error.js, test/integration/hook.err.js
* The issue causes sibling suites too fail when there is an async error thrown in the hooks of one suite
* Added unit test cases for async hook error handling
* Fixed minor issue in existing sync hook error unit test case
Detail:
Hook failures are handled in the same manner as outlines in this PR - https://github.com/mochajs/mocha/pull/1043
This fix simply ensures that uncaught aysnc errors are being handled appropriately rather than bailing. 
This fix should also resolve issue - https://github.com/mochajs/mocha/issues/534
=> Fix for async hook error handling issue

lib/reporters/html-cov.js, lib/reporters/templates/coverage.jade, lib/reporters/templates/menu.jade, package.json
For #1811 .
There is a error for html-cov. I fixed it, and then I updated jade.
=> Upgrade Jade dependency to 1.11.0

bin/mocha
This allows setting the heap size for tests which require it.
=> Support --max-old-space-size node argument

lib/runner.js, test/integration/fixtures/options/bail.js
Fixes #1812
Added a bail check to the runSuite method in runner.js. There was already a commented out check for a subsequent before block in the bail fixture so I just uncommented that for the test.
=> Fix: Bail flag causes before() hooks to be run even after a failure

lib/reporters/xunit.js, test/integration/reporters.js
Fix for https://github.com/mochajs/mocha/issues/1864
``` javascript
./bin/mocha --reporter=xunit --reporter-options output=results.xml test.js; cat results.xml
<testsuite name="Mocha Tests" tests="2" failures="1" errors="1" skipped="0" timestamp="Wed, 09 Sep 2015 19:34:48 GMT" time="0.004">
<testcase classname="my test" name="should pass" time="0.001"/>
<testcase classname="my test" name="should fail" time="0.001"><failure><![CDATA[fail
Error: fail
at Context.&lt;anonymous&gt; (test.js:7:14)
at callFnAsync (/Users/danielstjules/git/mocha/lib/runnable.js:306:8)
at Test.Runnable.run (/Users/danielstjules/git/mocha/lib/runnable.js:261:7)
at Runner.runTest (/Users/danielstjules/git/mocha/lib/runner.js:417:10)
at /Users/danielstjules/git/mocha/lib/runner.js:524:12
at next …
```
=> Fix #1864: xunit missing output with --reporter-options output

lib/runner.js, test/integration/fixtures/options/delay-fail.js, test/integration/options.js
For https://github.com/mochajs/mocha/issues/1669
``` javascript
$ cat test.js
setTimeout(function() {
throw new Error('oops');
it('test', function() {});
run();
}, 100);
```
``` javascript
// Before PR
$ ~/git/mocha/bin/mocha --delay test.js
$ // EMPTY
// After PR
$ ~/git/mocha/bin/mocha --delay test.js
1) Uncaught error outside test suite
0 passing (5ms)
1 failing
1)  Uncaught error outside test suite:
Uncaught Error: oops
at null._onTimeout (test.js:2:9)
```
=> Fix #1669: catch uncaught errors outside test suite execution

lib/reporters/templates/coverage.jade, lib/reporters/templates/menu.jade, package.json
Reverts https://github.com/outsideris/mocha/commit/d70759f1730a7cecf8f786715a74065db5b6638b for older npm versions, as discussed in https://github.com/mochajs/mocha/issues/1868
=> Revert jade to support npm < v1.3.7

lib/utils.js, test/utils.js
Followup to https://github.com/mochajs/mocha/issues/1766 and https://github.com/mochajs/mocha/pull/1767
Makes the behavior consistent in the browser. We now only filter out mocha's own function calls, and don't touch calls from dependencies. Given how modularity is embraced in the node community, I think this is ideal.
=> Stackfilter fix: Don't remove modules/components from stack trace in the browser

lib/runner.js, test/integration/fixtures/multiple.done.before.js, test/integration/fixtures/multiple.done.beforeEach.js, test/integration/fixtures/multiple.done.specs.js, test/integration/multiple.done.js
``` javascript
$ cat test.js
describe('suite', function() {
before(function(done) {
setTimeout(done, 30);
setTimeout(done, 60);
});
it('test', function(done) {
setTimeout(done, 100);
});
});
// -------------------------------------------------------------
// Before PR, the error is incorrectly attributed to the spec,
// rather than the before hook. Furthermore, the error was
// uncaught, so that suite would stop
// -------------------------------------------------------------
$ mocha test.js
suite
1) test
0 passing (67ms)
1 failing
1) suite test:
Uncaught Error: done() called multiple times
// -------------------------------------------------------------
// After the PR, the error is correctly attributed to the hook
// -------------------------------------------------------------
$ mocha …
```
=> Fix #1798: Correctly attribute mutiple done err with hooks

bin/mocha, test/integration/regression.js
Found by @jameswomack (see [yargs issue 267](https://github.com/bcoe/yargs/issues/267)), mocha is reading options from `test/mocha.opts` and adding them to `process.argv` twice - once in `bin/mocha` and then again in `bin/_mocha`. This PR removes the 2nd one and adds a unit test to cover this scenario.
Wasn't quite sure where to put the unit test, but `test/integration/regression.js` seems like a decent place.
Let me know if there's anything you'd like me to change. Thanks.
=> Fix duplication of mocha.opts on process.argv

package.json
debug@2.0.0 has a vulnerability in its dependency on ms@0.6.2.
debug@2.2.0 has updated its ms dependency to a version without this vulnerability.
=> Update debug dependency to 2.2.0

lib/runnable.js
Bluebird js now prints a warning message and stack trace when it discovers Promises that create other Promises but do not return them. Mocha trips this warning when the user chains together multiple hooks, and this PR eliminates the warning by explicitly returning null instead of undefined which signals that the warning should not be emitted.
=> Silence Bluebird js warnings

Makefile, lib/interfaces/bdd.js, test/acceptance/misc/only/bdd-require.js
Resolves #1964 
the bdd UI was being called twice, once from within the `Mocha` constructor, and also from the `_mocha` command line. This prevents a UI from being called twice, and it's `pre-require` hooks being called twice so that it partially clobbers itself.
=> Dont double install bdd ui

lib/utils.js
ES5 appears to require that `{` be escaped when not used as part of a quantifier. While this works fine in browsers it appears to choke less lenient runtimes (e.g. Duktape).
A similar case is discussed in Duktape (https://github.com/svaarala/duktape/issues/69 and https://github.com/svaarala/duktape/issues/74).
Please find attached a simple Duktape-powered C file that tries to parse the given argument file. [test.c.zip](https://github.com/mochajs/mocha/files/70018/test.c.zip)
Compile and run using:
```
$ gcc -std=c99 -o test test.c duktape-1.3.1/src/duktape.c -I duktape-1.3.1/src/  -lm && ./test mocha/mocha.js
```
When choking it produces a:
`eval failed: SyntaxError: invalid regexp quantifier (unknown char) (line 5755)`
when the parsing is fine it will produce (because I did not setup a …
=> Fix non ES5 compliant regexp

lib/reporters/xunit.js
Fixes #1674; provides support *much* needed for [mocha-phantomjs](https://github.com/nathanboktae/mocha-phantomjs) (see [#133](https://github.com/nathanboktae/mocha-phantomjs/issues/133), [#220](https://github.com/nathanboktae/mocha-phantomjs/issues/220), etc).  Maintains support for running the XUnit reporter in a browser (unlike the previously reverted PR #1068).
ping @alemangui, @nathanboktae
Thanks all.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mochajs/mocha/2005)
=> XUnit Reporter Writes to stdout, falls back to console.log

bin/_mocha, bin/mocha
Support for passing along the `--use_strict` flag from `mocha` to `_mocha`. Also fixes a strict code incompatibility with the undeclared variable `Reporter` in `_mocha`, as outlined in #1879.
Tests all pass and the lib works on node v4.2.3 and v5.1.1.
=> support for strict mode

lib/reporters/html.js, test/browser/index.html, test/browser/multiple-done.js
In either of the test cases below, when using the HTML reporter, the failure details are not currently shown. The failure count is increased, but there's no specific details.
This patch adjusts the reporter so that failures after the initial done() are displayed. This doesn't seem to cause any regressions in the manual browser tests.
The output does show the test as passing, and then shows it as failing, but I think that's reasonable given what is happening and is better than not showing any errors.
Test cases:
```
describe('Multiple Done calls', function(){
it('should report an error if done was called more than once', function(done){
done();
done();
})
it('should report an error if an exception happened after done was called', function(done){
done();
throw new Error("thrown error");
}) …
```
=> Fix HTML reporting display to show errors if done is called multiple times, or if an exception is thrown after done is called.

bin/_mocha, bin/mocha
Very basic PR, adding support for --perf-basic-prof v8 option.
----
This supports creating flamegraphs on linux with mocha tests.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mochajs/mocha/1963)
=> Add support --perf-basic-prof

bin/_mocha, bin/mocha
This provides better insights when profiling application using `--prof` switch. Especially useful when the log is processed by [profviz tool](https://v8.googlecode.com/svn/branches/bleeding_edge/tools/profviz/profviz.html).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mochajs/mocha/1982)
=> Enable --log-timer-events option

bin/_mocha, lib/context.js, lib/interfaces/bdd.js, lib/interfaces/common.js, lib/interfaces/qunit.js, lib/interfaces/tdd.js, lib/mocha.js, lib/reporters/json-cov.js, lib/reporters/json-stream.js, lib/reporters/json.js, lib/runnable.js, lib/runner.js, lib/suite.js, test/integration/fixtures/options/retries.js, test/integration/fixtures/retries/early-pass.js, test/integration/fixtures/retries/hooks.js, test/integration/fixtures/retries/nested.js, test/integration/options.js, test/integration/retries.js, test/runnable.js
- make retries run proper hooks
- allow retries override at different levels
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mochajs/mocha/1989)
=> Allow to retry failed test from test context for #1773

lib/utils.js
When running in PhantomJS, due to http://stackoverflow.com/questions/14218670/why-are-null-and-undefined-of-the-type-domwindow `canonicalize` can throw an exception, resulting from `Runner.prototype.uncaught` returning without emitting the `end` event (causing test mocha-phantomjs test runner to just hang and not exit).  I'm not sure whether it's better to alter logic in `Runner.prototype.uncaught` to ensure `end` is always emitting, as I don't really understand the logic there (why in certain cases it returns without emitting).
This patch just catches an exception stringifying the canonicalized value, which seems like a reasonable thing to do anyway.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mochajs/mocha/1977 …
=> safely stringify PhantomJS undefined value

lib/runner.js, test/integration/fixtures/hooks/before.hook.async.error.tip.js, test/integration/fixtures/hooks/before.hook.error.tip.js, test/integration/hook.err.js
Fix #2006
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mochajs/mocha/2028)
=> Remove reference to test before afterAll hook runs

.travis.yml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mochajs/mocha/2038)
=> Also run Travis-CI on node.js 4 & 5

lib/runner.js, lib/utils.js, test/integration/fixtures/regression/issue-1991.js, test/integration/regression.js
(it/before[Each]/after[Each]).
related to #1991
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mochajs/mocha/2037)
=> Fix for memory leak caused by referenced to deferred test functions

package.json, test/integration/helpers.js, test/utils.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mochajs/mocha/2033)
=> Update tests for newer versions of should.js

lib/runnable.js, lib/runner.js, lib/test.js, test/integration/fixtures/retries/async.js, test/integration/retries.js, test/test.js
@danielstjules @boneskull 
The reason `retry` isn't working for timeout `async` test is because of internal state change within `test` (`timer`, `timedOut`...). Therefore, instead of trying to reuse the test & reset its state, I just clone it instead for a fresh state.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mochajs/mocha/2047)
=> add clone capability to test, fix async retry, fix #2045

lib/runner.js
From https://github.com/mochajs/mocha/pull/1945#issuecomment-170399856 Fixes the following simple case for the HTML reporter:
```js
describe('skipping', function() {
it('amazes', function() {
this.skip()
assert(true)
})
})
// expected: "amazes" test shows as pending within test results
// actual outcome: "TypeError: Cannot read property 'toString' of undefined"
```
Before PR:
After PR:
=> Fix `this.skip` from spec with HTML reporter

lib/runner.js
Tests didn't get skipped when calling ``this.skip()`` in the ``before`` function of a suite.
e.g.
````js
describe('Suite', function(){
before(function(){
this.skip();
});
it('this is still ran', function(){
//code
});
});
````
I don't know if this is the best way of fixing the issue, or even if this is the intended behaviour. Suggestions welcome to improve this PR. :boom:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mochajs/mocha/1945)
=> Correctly skip tests when skipping in a suites before()

lib/runner.js
Fixes the issue reported here: https://github.com/mochajs/mocha/issues/2040#issuecomment-174864558
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mochajs/mocha/2066)
=> Fix test fn's being deleted too early for browser reporter

lib/reporters/doc.js, lib/reporters/html.js, lib/reporters/markdown.js, lib/test.js
Fixes https://github.com/mochajs/mocha/issues/2067
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mochajs/mocha/2068)
=> Fix 2067: HTML/DOC reporter regression with async failures

support/browser-entry.js
Assigning to `window` only works in a normal browser environment; however, Web Workers don't have access to `window`. Instead, the global object inside Web Workers is `self`.
Browserify already ensures that `global` is present and dereferenced accordingly. It will equal to `window` unless `self` is defined.
This fixes Web Workers compatibility lost in a81e5558f086808b682b6d196b80893d2c8926f8 (v2.3.0).
/cc @jbnicolai @ndhoule
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mochajs/mocha/2053)
=> Have global exports be compatible with Web Workers

lib/reporters/base.js
Removed extraneous color code that broke output on Windows as shown in https://github.com/mochajs/mocha/issues/2071
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mochajs/mocha/2072)
=> Fix #2071: Removed color code to fix Chalk colors

test/acceptance/utils.js, test/grep.js, test/runnable.js, test/runner.js, test/suite.js, test/test.js
They were missing parentheses and thus no assertion method was ever executed.
=> Fix a number of assertions that weren't asserting anything

lib/utils.js, test/acceptance/utils.js
This PR fixes issue #2089.
It enables to generate diff of objects that have Symbol values.
Fixed output:
=> handle Symbol values in util.stringify()

lib/utils.js, test/reporters/base.js
Instead of calling `hasOwnProperty` directly, it should be `Object.prototype.hasOwnProperty.call(object, prop)`. This is already the case further up in the `exports.stringify` implementation.
=> fix diff for objects with custom hasOwnProperty values

lib/interfaces/bdd.js, lib/interfaces/tdd.js, lib/reporters/html.js, lib/reporters/xunit.js, lib/runnable.js, lib/runner.js, lib/suite.js, test/suite.js, test/test.js
Checking for boolean property `.pending` on Test or Suite objects was too brittle in a way that the caller often forgot to check whether any of the object's parents are marked as pending as well.
This moves all the pending checks to new `.isPending()` predicate method that is defined on all Suite and Runnable (and thus Test and Hook as well.)
Runners and reporters should always use this method to check for "pendingness" of test and suite objects.
Fixes #1760, fixes #1936
/cc @puzrin @danielstjules @Kirill89
=> Strenghten checks across the board for pending/skipped tests or suites

lib/runnable.js, lib/test.js
Fixes `Uncaught TypeError: Cannot read property 'replace' of undefined` when an exception is thrown from a hook.
Example test suite that correctly renders after the PR:
``` javascript
before(function() {
throw new Error('uh oh!');
});
it('test', function() {});
```
=> Fix hook error in browser reporter by moving body prop from test to runnable

mocha.css
This is not the best solution for a problem, mocha should not know anything about Bootstrap.
Proposed change would result in less conflicts. However it is made just to get the ball rolling.
In order to prevent such conflicts from happening, it is a good idea to avoid nesting in mochas CSS, e.g. by adapting BEM naming convention (see https://css-tricks.com/bem-101/).
Giving mocha elements classes named `mocha-stats-progress` will eliminate conflicts with other libraries entirely.
=> Set safe CSS for progress indicator which does not conflict with Bootstrap

lib/reporters/base.js, test/reporters/base.js
This PR checks that when handling assertion error messages in a reporter, the message is actually a string since if it isn't the `message.match` function (https://github.com/jkimbo/mocha/blob/2a1dc7a8f32d7eb65cdf645c30aac3cc37714ae7/lib/reporters/base.js#L208) fails and leads to the test suite failing silently.
=> Non string error messages

package.json
this updates to last version of growl ( from https://github.com/tj/node-growl/issues/57 )
this for example fixes the way notifications look in OSX (they don't show a success/fail icon currently), with this update now it looks like this:
=> updating growl dependency

lib/utils.js, test/acceptance/utils.js
Fix for #2109.  When comparing objects with certain length properties, the reporter throws when stringifying the diff:
```javascript
it('compare two objects', function () {
assert.deepEqual({length: {toString: 0}}, {length: 1});
});
```
Root cause is that some JS objects cannot be coerced to a Number:
```javascript
> Number({toString: 0});
TypeError: Cannot convert object to primitive value
> Number({a: 0});
< NaN
```
=> Fix #2109: stringify should handle objects with non-coercible length

bin/_mocha
The growl functionality lives in core mocha now.
=> Remove dead growl code in bin/_mocha (fixes #2132)

lib/utils.js, test/utils.js
=> Only replace absolute -> relative paths for stack lines

lib/interfaces/exports.js
Was "TDD-style interface", should refer to Export interface style. See issue #2204 for alternative suggestions.
Fixes #2204
=> Correct comment label in exports interface

package.json
When installing `mocha@2.4.5`, `glob@3.2.3` triggers the following warning:
```
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
```
This commit bumps to the latest patch version before a major version.
Diff at https://github.com/isaacs/node-glob/compare/v3.2.3...v3.2.11.
=> Bump glob patch version to remove warning

README.md
- Use new logo
- Centers logo
- Gives it some margin
I couldn't use the `.svg`'s we have in `/assets/` for some reason, maybe because of the way it was exported. You can try it out for yourselves. /cc @boneskull 
If we were to use an image, we need a `@2x` export (double size) for retina screens. Hmm, I can actually generate one of those myself. But I hope we can solve the issues our `svg` files have.
I'll squash (or use "squash & merge") as necessary once the PR is reviewed, just in case we want to easily revert a subset of the changes.
=> Update README's header section

.travis.yml, test/acceptance/utils.js
also:
- add integration coverage when using glob module
=> adds node 6 to CI matrix; closes #2239

package.json
naively:
```shell
$ npm install mocha
$ npm install -g browserify
```
```js
// foo.js
require('mocha')
```
```shell
$ browserify foo.js > foo.dist.js
```
...completes successfully.
=> full browserification support; closes #880

lib/reporters/html.js
Fixed #2083
This is a minor refactor of the HTML reporter to listen to `pass/fail/pending` events rather than `test end`, just like the spec/dot reporters.
--------
As seen below, the sync error is displayed only a single time:
--------
--------
And the async errors are each correctly displayed. This is the behavior https://github.com/mochajs/mocha/pull/1981 was intended to fix. Prior to that PR, none of the errors below were displayed in the HTML reporter.
--------
=> Fix #2083: HTML reporter regression causing duplicate error output

lib/reporters/html.js
I have noticed a small issue with the hash updating when the passed/failure filters are clicked on the html reporter. When testing an app that uses hash navigation this can cause the page to navigate.
Let me know thoughts. Thanks
=> prevent html reporter updating url hash

lib/runner.js, test/integration/fixtures/regression/issue-2286.js, test/integration/regression.js
=> Add failing test: after hook is not run if test skipped in beforeEach

lib/utils.js, test/utils.js
Fixes #2208
- Treat tabs etc. as spaces.
- Match function name for removal.
- Match only non-`)` inside the function parameter list for removal instead of `.`; prevents matching through later in the first line e.g. `function(){ if ([condition]) { ...`.
- Match 0 or more spaces before } on the end for removal rather than 1 or more.
- Make the closing } optional for arrow functions with a single-statement body just like the opening {.
- Add tests for these cases.
=> Correct regex for function source cleaning

lib/reporters/doc.js
This fixes the following scenario:
```js
describe('Mocha', function() {
it('should fail', function() {
throw Error('ouch');
});
});
```
```
$ mocha example.js --reporter doc
<section class="suite">
<h1>Mocha</h1>
<dl>
<dt class="error">should fail</dt>
<dt class="error">should fail</dt>
```
Expected output:
```
<section class="suite">
<h1>Mocha</h1>
<dl>
<dt class="error">should fail</dt>
<dd class="error"><pre><code>throw Error('ouch');</code></pre></dd>
<dd class="error">Error: ouch</dd>
</dl>
</section>
```
The typo was introduced in d59cc6c166d0d112a62016909b33e04ed08d2274:
https://github.com/danielstjules/mocha/blob/d59cc6c166d0d112a62016909b33e04ed08d2274/lib/reporters/doc.js#L58
=> Fix a small typo in the doc reporter that causes mocha to crash

lib/reporters/html.js
Hi mocha team.
This is a small fix for the progress bar staying consistently at 0 when using the HTML reporter.
Seems like a regression that happened due to the "double-error" fix/refactor.
Reasoning for the changes:
updateStats() accesses this.total, but this === the global object (window) if not specified explicitly here.
Also added a missing update when all tests end.
=> Fix % always 0 in HTML reporter

lib/runnable.js, test/integration/fixtures/pending/skip.async.before.js, test/integration/fixtures/pending/skip.async.beforeEach.js, test/integration/fixtures/pending/skip.async.spec.js, test/integration/pending.js
I can't tell if this is an actual bug fix, regression, or what (because where are the tests for async `skip()` calls?), but it allows this test:
```js
it('should be skipped async', function (done) {
const self = this
setTimeout(function () {
self.skip()
}, 1000)
})
```
To be successfully marked as "pending".
cc @dasilvacontin @maggiesavovska
=> allow skip() in async test context; closes #2334

bin/_mocha
Fixes #2317 and prevents similar issues in the future.
=> Get interface name list from collection; closes #2317

bin/_mocha
`mocha --compilers js:C:\User\fortest\demo\compiler.js`
https://github.com/mochajs/mocha/issues/2310
=> fix custom comiler file (absolute path) support in windows system

Makefile, appveyor.yml, karma.conf.js, mocha.js, package.json, test/acceptance/fs.js, test/acceptance/lookup-files.js, test/color.js, test/integration/diffs.js, test/integration/fixtures/hooks/multiple.hook.async.error.js, test/integration/fixtures/hooks/multiple.hook.error.js, test/integration/fixtures/regression/issue-1991.js, test/integration/helpers.js, test/integration/hook.err.js, test/integration/hooks.js, test/integration/multiple.done.js, test/integration/pending.js, test/integration/regression.js, test/integration/retries.js, test/integration/timeout.js, test/integration/uncaught.js
This is based on @TimothyGu's work in #2270, which was based on #1814.
In 78f36fc, I added `appveyor.yml`.  All test modifications simply increased timeout values, as appveyor seems to run tests slowly.
=> adds ability to run tests on windows; adds appveyor to CI; closes #1813

bin/_mocha, bin/mocha
This is a new flag added in Node 6.2.0 https://github.com/nodejs/node/pull/6537
I would like to be able to use it with mocha!
=> Add --preserve-symlinks flag for node

lib/reporters/base.js
when an `Error` is thrown *without* a message, we end up setting this `message` variable to an empty string.  But this seems to be a constant:
```js
anyString.indexOf('') === 0
```
We attempt to remove and format `message` as it exists within the `stack` [here](https://github.com/boneskull/mocha/blob/52d0268d5fab42c3d1f5636c85419c23edc9ab7d/lib/reporters/base.js#L190).  Since `index === 0`, we just end up removing the *first character* from `'Error'`.
This PR ensures that if `message === ''` then `index === -1`.
=> don't truncate message-list Error in Base.list(); closes #2361

mocha.css
Simple fixes to CSS syntax.  My editor was throwing errors on the CSS as border-radius:none is not a acceptable value (Should be "0"). I linted the CSS, kept all legacy css support, and added modern syntax for border-radius and box shadow.
=> Update syntax for "border-radius" and "box-shadow", added vendor prefixes for calc()

.eslintrc, package.json
Rules space-after-keywords and space-return-throw-case merged into keyword-spacing
=> Upgrade eslint package to 2.13 version fix for #2348

lib/interfaces/bdd.js, lib/interfaces/common.js, lib/interfaces/qunit.js, lib/interfaces/tdd.js, lib/runner.js, test/integration/fixtures/options/only/bdd.js, test/integration/fixtures/options/only/tdd.js, test/integration/only.js
- includes some more refactoring of interface code into `lib/interfaces/common.js` for DRY (still more work to be done here)
- unfortunately said refactoring contains hellish logic which addresses this issue (someone should make a flowchart of this for lolz)
- original PR did not address `exports` interface; this doesn't either
- may need more coverage against `qunit` interface
*This is a PR into the `v3.0.0` branch*
cc @mochajs/core
=> let child suites run if parent is exclusive; closes #2378

lib/interfaces/common.js, lib/runner.js, lib/suite.js, lib/utils.js, test/integration/fixtures/regression/issue-2406.js, test/integration/regression.js
Previously, tests in nested `describe.only` suites would not be registered as `only` tests in their parent suite (due to the implementation described in https://github.com/mochajs/mocha/pull/2387#discussion_r71646306). This caused mocha to think that the parent suite had no `only` tests, so the suite was skipped entirely. (See #2406 for more information.)
This PR moves some of the logic for `it.only` and `describe.only` to the test runner, rather than the place where suites are created. This makes the logic slightly simpler, because all of the suites already exist at the time that `only` suites are handled.
---
The correct logic for `only` blocks (from what I can tell, looking at the existing tests and the docs) is as follows:
* If a suite contains no `only` suites/tests among all of its …
=> fix nested describe.only suites; closes #2406

lib/runner.js, test/integration/fixtures/regression/issue-2417.js, test/integration/regression.js
fixes #2417
The issue was that instead calling itself with child suites, the function for filtering a `.only` suite was calling itself with the same suite. This resulted in infinite recursion.
=> fix .only suites nested within each other

Makefile, mocha.js, scripts/dedefine.js
added browserify transform to remove code which conflicts with AMD loaders.
=> avoid define() calls in dependencies; closes #2424

bin/mocha
PR: https://github.com/nodejs/node/pull/6792
Merged in Node v7.0: https://nodejs.org/download/nightly/v7.0.0-nightly20160619a92089b6bd/
Short article about it: https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27#.cs12vrlsa
Usage:
```bash
mocha --inspect --debug-brk hello.js
```
A quick patch release will be greatly appreciated! Thanks!
=> Exclude the --inspect flag

.eslintignore, Makefile, lib/runnable.js, lib/runner.js, test/runner.js
- also fixes lack of support for async `skip()` when `allowUncaught` option is used
- adds some debuggability into `this.skip()` calls
=> always halt execution when async skip() called; closes #2465

bin/_mocha
- Exit with code 130 on SIGINT
- ~~Exit with code 1 if any error occurred~~
- Exit with an exit code of max 255 to avoid 8-bit overflow mistakingly reporting no errors
Closes #2438
=> Exit process with correct error codes

bin/_mocha, test/acceptance/glob/glob.sh
This displays a warning on STDERR for each glob pattern that is passed in as a binary execution argument if the glob pattern results in no files matched.
If no files are matched across all the passed glob patterns it exits with error code 1
This allows for running tests for any glob pattern that correctly matches files, while still making the user aware of their other invalid glob patterns. Previously we would throw if any pattern did not match any files and the error message was not the best one to figure out the problem.
Fixes #2194
=> Report non-match to STDERR and exit if no files are matched

lib/utils.js, test/acceptance/utils.spec.js
- rename some exported functions/vars as to use locally
- update JSDoc comments
=> fix diff output for String objects; closes #2496

lib/runner.js, lib/utils.js, test/runner.spec.js
I have no idea what's causing the error to have a non-writable `stack` property. ¯\_(ツ)_/¯
=> recover gracefully if stack is not writable; closes #2528

README.md
There might be people who are looking for the exact license text.  Added a link to the license text (Raw form at https://raw.githubusercontent.com/mochajs/mocha/master/LICENSE) for easy access.
=> Added link to License text for easy access

lib/runnable.js, mocha.js
Since there isn't currently a way to tell whether the test tried to return a promise or not where we throw the timeout error, I simply went with the suggestion by @dasilvacontin.
=> Add a more clear timeout message. Closes #2294

bin/_mocha
Simply adds information about `--inspect` support to options displayed when running `--help`
=> adds info about --inspect flag to options in --help

lib/reporters/list.js
Hello,
The List reporter's output regressed during a [past refactoring](https://github.com/mochajs/mocha/commit/bec7a6e1686cf1f4c26ef6c2ba25eda36ccdd6c5#diff-855bef20eedfd15010e9e05ba5ddf02f). This pull request reverts the output to the [old correct output](https://mochajs.org/#list) but it still retains the benefit of the refactoring.
All tests passing.
=> Revert test pass symbol in List reporter

package.json
This update includes me to the list of contributors in package.json
Couple years ago I did this one: https://github.com/mochajs/mocha/pull/1043/files and I still see some of its' code in master.
Please let me be in contributors list.
=> Please, include me to the list of contributors

.travis.yml, scripts/travis-after-script.sh, scripts/travis-before-script.sh
This should mean quicker builds.
=> use trusty container in travis-ci; use "artifacts" addon

lib/reporters/html.js, mocha.js
Fixes #2283.
The issue causes the HTML reporter to display garbled characters (`â€`) instead of the [triangular bullet character](http://graphemica.com/%E2%80%A3) (`‣`) unless the containing HTML page has explicitly set:
```html
<meta charset="utf-8" />
```
=> Replaced embedded unicode characters in html reporter with their hex encoded equivalents

test/integration/suite.spec.js
The current timeout of 1000ms gives us a lot of false negatives on different node tests on Travis. The problem might be related to running lots of tests in parallel. Since this is hard to confirm on a local machine I have no scientific grounds for setting 2000ms specifically
=> Double timeouts on integration tests

karma.conf.js, package.json
We need to pin Karma to v1.3.0 for whatever reason, and also pin the # of concurrent Karma sessions to 5.  This seems to imrpove the situation, though I can't guarantee it's "fixed".
=> limit browser concurrency on sauce; closes #2478 and #2667

.eslintignore, .gitignore, Makefile, package.json
This PR does the following things:
- Creates a new `BUILDTMP/mocha.js` temporary file during test run, used by karma test only
- Deletes `BUILDTMP` after successful run
- Changed all make test run targets to depend on the new temporary file instead of an updated dist file
- Added `BUILDTMP` to all relevant ignore lists
- Added npm `preversion hook` to run tests and create the mocha.js distribution build artefact, plus stage it, so the build artifacts become a part of the release created by `npm version`
The overall goal of this PR is to only ever have the `mocha.js` browser build artefact generated when creating a new release. We want to avoid that contributors accidentally generate the build artefact during a normal test run and then accidentally check in the updated artefact.
=> Use temporary test-only build of mocha.js for browsers tests

test/reporters/base.spec.js
I am adding 4 new test scenarios for the base reporter.
Coverage diff:
There is one test that covers a specific chaijs scenario related to this [lines](https://github.com/mochajs/mocha/blob/master/lib/reporters/base.js#L212-L213), it was introduced in this [PR](https://github.com/mochajs/mocha/commit/34116d5d67b75fd189637cc773ce550ba956bc36), since I didn't want to add an extra dev dependency to cover this single case I added a comment trying to clarify it.
There is also some clean up that can be done ([see this PR](https://github.com/mochajs/mocha/pull/2681) ) on that file that could make the code cleaner and the coverage increase, but I didn't want to add to many things in one PR.
Hope it helps.
=> Increase tests coverage for base reporter

test/reporters/doc.spec.js
I am adding 9 new test scenarios for the doc reporter. It should be fully covered now.
Coverage diff:
Overall coverage +1% (78->79).
Hope it helps
=> Increase tests coverage for doc reporter

.travis.yml, karma.conf.js, package.json
Fixes #2344.
This moves the selection of the browsers to test to the travis build
script. The number of concurrent travis jobs should be limited to 5
(Saucelabs limit).
This also removes the S3 env variable which does nothing
This uses a fork of karma-sauce-launcher, which contains upated
dependencies, in order to support retries:
https://github.com/karma-runner/karma-sauce-launcher/pull/114
=> chore(Saucelabs): test on IE9, IE10 and IE11.

test/reporters/dot.spec.js, test/reporters/spec.spec.js
I am adding 9 new test scenarios for the dot reporter and 5 for the spec reporter. They should be fully covered now.
I have had to disable colors for these tests due appveyor seeming to have no ANSI color code support.
Dot Coverage diff:
Spec Coverage diff:
Hope it helps
=> Increase tests coverage for spec + dot reporters

test/reporters/nyan.spec.js
I am adding 20 new test scenarios for the nyan reporter (its quite a beefy reporter, added to the 4 that were already there). It should now be fully covered.
AppVeyor does not seem to have TTY support so tests around that.
Coverage diff:
Hope it helps
=> Increase tests coverage for nyan reporter to 100%

test/reporters/xunit.spec.js
I am adding 11 new test scenarios for the XUnit reporter. 
The only branch which is missing is the falsy of the `attr` iterations property check here https://github.com/mochajs/mocha/blob/master/lib/reporters/xunit.js#L158 (which does not seem possible to catch).
Coverage diff:
Hope it helps
=> Increase tests coverage for xunit reporter

test/reporters/json-stream.spec.js, test/reporters/markdown.spec.js, test/reporters/progress.spec.js
Json Stream coverage diff:
Markdown coverage diff:
Progress coverage diff:
(missing statement as unable to set verbose option to `true`)
Overall coverage +2% (not sure why coveralls hasnt recognised it).
Hope it helps
=> Increase tests coverage for json-stream, markdown and progress reporters

test/reporters/landing.spec.js, test/reporters/list.spec.js, test/reporters/min.spec.js, test/reporters/tap.spec.js
Landing coverage diff:
Min coverage diff:
TAP coverage diff:
List coverage diff:
Hope it helps
=> Increase tests coverage for landing, min, tap and list reporters

Makefile
Whilst working on the Reproducible Builds effort [0], we noticed
that node-mocha could not be built reproducibly.
[0] https://reproducible-builds.org/
=> Please make the build reproducible.

bin/_mocha, bin/mocha
There's already a support for `--inspect` option. This extends that support for the option, `--inspect-brk`.
=> Support `--inspect-brk` on command-line

test/integration/fixtures/simple-reporter.js, test/integration/reporters.spec.js
@dasilvacontin How does this look for https://github.com/mochajs/mocha/issues/2772?
=> Adds tests for loading reporters w/ relative/absolute paths

README.md
Followup to @kborchers's email on JSF adopting FOSSA for license scanning. We're currently merging in PRs for scan status into repo READMEs (i.e. webpack/webpack#4768)
Congrats on the passing license scan! In the PR is a green badge and report.
=> Add license report and scan status

karma.conf.js, package.json
- also, reformat a conditional
https://github.com/ariya/phantomjs/issues/14558 was causing seg faults at the time this
change was made; it is no longer causing seg faults, so phantomjs should be the default.
this was prompted by #2759
=> no special case for macOS running Karma locally

.eslintrc.yaml, Makefile, lib/browser/.eslintrc.yaml, package.json, test/.eslintrc.yaml, test/integration/fixtures/simple-reporter.js
Abstractions around ESLint are not widely supported in text editors or IDEs.  For example, I could tell WebStorm to use `node_modules/eslint-config-semistandard/eslintrc.json`, but there's no way for WebStorm to know about the overrides in the [`semistandard` prop of `package.json`](https://github.com/mochajs/mocha/blob/master/package.json#L374), nor the overrides specified for [test files in `Makefile`](https://github.com/mochajs/mocha/blob/master/Makefile#L38).
`semistandard` is arguably easier to use on the CLI, and requires less configuration files, but the cost to users primarily interfacing with ESLint via contextual information in an IDE (like myself!) outweighs the benefit.
cc @kt3k
=> reverts use of semistandard directly (#2648)

bin/_mocha, bin/mocha
Adds support for Node.js’s [`--no-warnings`](https://nodejs.org/dist/latest-v6.x/docs/api/cli.html#cli_no_warnings) and [`--trace-warnings`](https://nodejs.org/dist/latest-v6.x/docs/api/cli.html#cli_trace_warnings) flags.
See also https://github.com/mochajs/mocha/pull/2495.
=> Add `--no-warnings` and `--trace-warnings` flags

test/acceptance/file-utils.spec.js, test/integration/reporters.spec.js
fixes #2802 
`os.tmpdir` was added in 0.9.9 (see https://github.com/hapijs/hapi/issues/3369).
With mocha having a minimum node version of 0.10 it can be dropped without issues.
=> Remove call to deprecated os.tmpDir (#2802)

bin/_mocha
Simpler version of PR #2714 which only eagerly sets the exitcode without playing with the draining semantics
=> Simplified fix for issue #2713

.github/stale.yml
closes #2828.
Issues and PRs will be marked `stale` after 4 mos. of inactivity and closed if there's no activity after 2 more weeks.
*Most* issues with labels are exempt from the check.  I'm not sure how well this is going to work, but we can always change it later.
=> add config for probot-stale integration

test/.eslintrc.yaml
=> Remove not-longer-necessary `run` global in .estlintrc

.eslintrc.yaml
It will prevent config lookup to exit Mocha's project folder.
=> Declare main eslintrc as `root`

bin/_mocha, bin/mocha
This change enables testing of NAPI modules[1]. This is achieved
by passing the appropriate flags to node inside the mocha executable.
[1]: https://nodejs.org/api/n-api.html
=> Pass flags for NAPI modules

.gitignore, .npmrc
This ensures we don't have to deal with `package-lock.json` and `yarn.lock` for now.
=> ignore lockfiles for now

karma.conf.js, package.json, test/jsapi/index.js, test/unit/grep.spec.js, test/unit/hook-async.spec.js, test/unit/hook-sync-nested.spec.js, test/unit/hook-sync.spec.js, test/unit/mocha.spec.js, test/unit/ms.spec.js, test/unit/runnable.spec.js, test/unit/runner.spec.js, test/unit/suite.spec.js, test/unit/test.spec.js, test/unit/utils.spec.js
I think the `package-lock.json` creation created by npm@5 was causing us to be unable to do `npm install` after an `npm install --production`.
=> fix CI; closes #2867

package.json, test/integration/helpers.js, test/integration/hooks.spec.js, test/integration/only.spec.js, test/integration/options.spec.js, test/integration/pending.spec.js, test/integration/regression.spec.js, test/integration/reporters.spec.js, test/integration/retries.spec.js, test/integration/suite.spec.js, test/integration/timeout.spec.js, test/integration/uncaught.spec.js, test/node-unit/file-utils.spec.js
- ensure we can run the test suite with `DEBUG=mocha*` by removing it
when spawning `mocha`
- remove some cruft in the test helpers
=> upgrade to debug@2.6.8; closes #2859

test/unit/mocha.spec.js
Adds a few tests & increases the test coverage of mocha.js
=> increase test coverage of mocha.js

package.json, test/integration/helpers.js
Does NOT fix the Sauce 20,000ms disconnect issue.
Does fix the newer issues that appeared just this past day.
This fixes Travis browser tests (except for the Sauce 20,000ms disconnect issue), #2897 fixes AppVeyor Node 0.10 tests; put them both in master and then merge into anything else that's waiting for CI checks to pass, then hope the Sauce 20,000ms issue stays away for a while, ha.
(For the record: the issue is that readable-stream 2.3.0 breaks Phantom 1.x due to use of `Function.prototype.bind` and breaks IE7 and 8 due to pulling in `safe-buffer`, which uses `Object.keys`.)
=> Fix Travis browser tests dependency

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
=> Added issue, pull request templates.

lib/utils.js, package.json, test/unit/utils.spec.js
I started walking down the path of replacing those myself but once I hit surrogate pairs it seemed to become silly. That's why I went with just adding `he`.
Fixes https://github.com/mochajs/mocha/issues/2955
=> Add `utils.escape` tests and fix unicode escaping

.travis.yml, Makefile, package.json, scripts/travis-before-script.sh
we don't seem to need `istanbul-combine`, as we are only generating coverage from one test run in CI.  the data can then be piped directly to the `coveralls` executable.
=> update coveralls strategy; closes #2984

package.json, scripts/travis-before-script.sh
#2985 cont'd now that my PR has been merged into nyc
=> update nyc to latest; remove workaround in travis script

scripts/dedefine.js, scripts/travis-before-script.sh
I opted to just hack the regex.  There's now a flimsy check *on Travis only* that tries to make sure this doesn't happen again.
cc @ScottFreeCode @FelixHenninger
=> fix AMD bundle by hacking around check in `he` module; closes #3000

lib/utils.js, test/reporters/doc.spec.js, test/unit/utils.spec.js
Fixes a regression introduced in https://github.com/mochajs/mocha/pull/2957. It was too aggressive in its use of named escapes which broke XML files that might not support all of the named escapes available in HTML.
We could try to get support for safe named escapes into `he`. But given that this won't affect the visible output, I focussed on fixing the functionality first.
This makes the HTML output a bit uglier. E.g. it won't use the nice `&quot;` anymore.
=> Use safer XML escaping

test/integration/compiler-globbing.spec.js
Per https://github.com/mochajs/mocha/issues/2493#issuecomment-303929358 and https://github.com/mochajs/mocha/issues/2493#issuecomment-324807709, this ensures that one can use a glob pattern to capture multiple file extensions without `--compilers`.
=> Test glob pattern equivalent of --compilers

browser-entry.js
Fixes #2095, by disabling the `stdout:` prefix with the browser shim.
=> Remove stdout: prefix

.github/CONTRIBUTING.md, README.md
New contributors may wish to review the CLA prior to working on a pull request. Currently, the only obvious way to view the CLA is to open a pull request.
=> Add CLA link

lib/reporters/base.js, test/reporters/base.spec.js
- fix issue #2295
- the purpose of this feature is to make the unified diff
format more readable.  Without it, different portions
of the same actual/expected diff look contiguous even
though they are actually separated by the default
context of four lines.
=> add unified diff separator

lib/runner.js, test/integration/fixtures/options/forbid-only/only-suite.js, test/integration/fixtures/options/forbid-pending/before-this.skip.js, test/integration/fixtures/options/forbid-pending/beforeEach-this.skip.js, test/integration/fixtures/options/forbid-pending/skip-suite.js, test/integration/fixtures/options/forbid-pending/this.skip.js, test/integration/options.spec.js
Followup to #2696; this is going to look crazy when somebody puts `.only` or `.skip` on a suite, but I can live with that (whereas I can't take not having any printout for these failures at all) and if we figure out how to emit one failure per relevant suite we can always tweak that later (whether it has to be semver-major or not).
=> Print failures for pending/only forbidden

bin/_mocha, test/integration/options.spec.js
Allows `--exit` to override and force exit as before. Resolves #2879
=> Switch default from forced exit to no-exit

bin/_mocha
This attempt is a bit rough; we might have to tweak tests to tell Node to suppress the deprecation warning, for instance.
=> Deprecate --compilers

CHANGELOG.md
Fix mocha issues/pr URLs
Just let the links 404
people want to read the changelog of mocha on mocha, not via a plugin
People will be able to click on the links, and get to the content they expected
More traffic to github issues might increase the overall cost to github
N/A
=> Fix mocha issues/pr URLs

package.json
Removes the `preversion` script, which is basically redundant due to `prepublishOnly` running the tests now.
=> remove preversion script; test on publish; closes #2999

package.json
Update growl to 1.10.3
This avoid a warning about an eslint peerDependency on install of mocha:
```
eslint-plugin-node@5.2.0 requires a peer of eslint@>=3.1.0 but none is installed.
```
=> Update growl to 1.10.3

package.json, test/compiler-fixtures/foo.fixture.js, test/integration/fixtures/diffs/diffs.fixture.js, test/integration/regression.spec.js, test/mocha.opts, test/node-unit/stack-trace-filter.spec.js, test/only/bdd.spec.js, test/only/global/bdd.spec.js, test/only/global/qunit.spec.js, test/only/global/tdd.spec.js, test/only/qunit.spec.js, test/only/tdd.spec.js, test/reporters/base.spec.js, test/reporters/doc.spec.js, test/reporters/dot.spec.js, test/reporters/json-stream.spec.js, test/reporters/json.spec.js, test/reporters/landing.spec.js, test/reporters/list.spec.js, test/reporters/markdown.spec.js, test/reporters/min.spec.js, test/reporters/nyan.spec.js, test/reporters/progress.spec.js, test/reporters/spec.spec.js, test/reporters/tap.spec.js, test/reporters/xunit.spec.js
The `should` library has been removed. All tests that were using it are now using expectJS.
Note that I also removed completely the diff integration test, because it was testing the output format provided by `should`.
One less package to worry about.
* This PR solves [issue 3035](https://github.com/mochajs/mocha/issues/3035)
* It shouldn't impact production code as this removes a dev dependency and only tests have been modified
=> Nuke `should` #3035

test/unit/mocha.spec.js
This adds a test case when `mocha.bail()` has  no arguments.
=> Add test for Mocha.bail()

lib/context.js, test/unit/context.spec.js
`Context#inspect()` is a private debugging method which is not consumed by Mocha, nor is it documented anywhere, so away it goes
=> add coverage to Context; remove unused Context#inspect()

MAINTAINERS.md
=> add 1st draft of maintainer guide; closes #2896

lib/context.js, lib/runnable.js, lib/suite.js, test/unit/context.spec.js
This PR adds missing argument checks and adds a couple getters to some of the main classes.
Should fix #3058.
If there are additional getters that I've missed, I can add them.
=> normalize getters and setters (fixes #3058)

lib/reporters/base.js
The `escape` argument for `inlineDiff()` and `unifiedDiff()` in `Base.list()` is always false.
[inlineDiff()](https://github.com/mochajs/mocha/blob/9f204ba2b27e254e70e88ab353e8c4cedc7b67f6/lib/reporters/base.js#L372) and [unifiedDiff()](https://github.com/mochajs/mocha/blob/9f204ba2b27e254e70e88ab353e8c4cedc7b67f6/lib/reporters/base.js#L406) are only used in `Base.list()` .
I think the `escape` argument is unnecessary.
https://github.com/mochajs/mocha/blob/9f204ba2b27e254e70e88ab353e8c4cedc7b67f6/lib/reporters/base.js#L188-L220
=> Remove unused variables

lib/mocha.js
add comment advising deletion from require cache if mocha is invoked programmatically multiple times
Add comment as suggested by @ScottFreeCode in https://github.com/mochajs/mocha/issues/3084#issuecomment-342394332.
N/A
It's a JSDoc comment on a core api.
API doc clarification.
N/A
https://github.com/mochajs/mocha/issues/3084
=> add cache comment

lib/ms.js, test/unit/ms.spec.js
Since `options` argument is unused in Mocha, this removes it.
https://github.com/mochajs/mocha/blob/2303c669ef1b47fef7cf86f5ef486d537033d443/lib/suite.js#L108-L110
https://github.com/mochajs/mocha/blob/2303c669ef1b47fef7cf86f5ef486d537033d443/lib/runnable.js#L82-L84
https://github.com/mochajs/mocha/blob/1bb6b3977a482c144a61d68ea2e499b22a7db01b/lib/reporters/base.js#L324-L326
=> Remove unused argument of lib/ms

lib/reporters/base.js, test/reporters/list.spec.js
instead of delaying until epilogue
An object referred to by a test failure can be mutated between the point of test failing and when the object is converted to a string and output. For instance if an `afterEach` clears the fields in an object pointed to by a `chai.expect.eql` AssertionError's `expected` or `actual` fields then the reporter's error message will be misleading
see https://codepen.io/abrady0/pen/pWGBxR?editors=1111 for running example.
Here is a snippet that assumes 'spec' reporter:
```
describe('example', function() {
var foo = {
a: 'before'
};
afterEach(function() {
console.log('afterEach');
foo.a = 'after';
})
it('should print the error properly', function() {
var bar = { a: 'during' };
console.log('foo2')
// HERE: output *should* say 'before' instead of 'after' for the …
```
=> have Base generate the strings for error messages immediately 

.gitignore, .npmrc, .travis.yml, package-lock.json
- update `.travis.yml` to use npm@5 caching where available
- remove `.npmrc` (now unused)
- remove `package-lock.json` from `.gitignore`
=> introduce package-lock.json; closes #3025

test/integration/diffs.spec.js
Fixes #2801 the brute-force but simple and easy way without refactoring the test design.
=> Ignore difference of newline output in diffing test

appveyor.yml, lib/interfaces/bdd.js, test/integration/fixtures/pending/skip-shorthand.fixture.js, test/integration/pending.spec.js, test/interfaces/bdd.spec.js
Fixes #3142 
The bigger reason for this fix is to ensure consistency across across both active and pending tests (ie `it` and `xit`).
I've also added a test suite for `setting timeout by appending it to test`
We can also remove the return statement to disable this feature in the bdd interface, but i personally favor having it around, maybe even document it after adding some more test cases!
Since @boneskull does not encourage the use of the `this` keyword in writing tests, documenting this change might create a shift to increased usage of arrow functions and less usage of `this`.
**patch**
=> return the created test in `xit` for bdd interface

Gemfile.lock, package.json, scripts/docs-update-toc.js
- update `Gemfile.lock`
- rename `prebuild-docs.js` to `docs-update-toc.js`
- fix `buildDocs`	and `serveDocs` options and ensure TOC is updated
- trim extra newlines from EOF in `index.md` after TOC update is run
=> fix local documentation problems; closes #3157 [ci skip]

lib/reporters/progress.js
Progress reporter had multiple options for configuring the reporter,
but it needed the optional fields under `options` object, while
those fields are provided under `options.reporterOptions`.
This commit enables usage of optional fields from `reporterOptions`.
=> options.reporterOptions are used for progress reporter

lib/reporters/progress.js
This reverts commit 78b686f3663fbe52ecd54827e5c00af0378292ba which introduced a breaking build via PR #2649.  I'm not sure *why*, because the build was passing before it was merged.
=> Revert "`options.reporterOptions` are used for progress reporter"

lib/reporters/progress.js, test/reporters/progress.spec.js
Progress reporter had multiple options for configuring the reporter,
but it needed the optional fields under `options` object, while
those fields are provided under `options.reporterOptions`.
This commit enables usage of optional fields from `reporterOptions`.
Updated test cases as well.
Fix for #2661
=> `options.reporterOptions` are used for progress reporter

.travis.yml
I wasn't able to edit the old PR (https://github.com/mochajs/mocha/pull/3160), so i make this one. As @boneskull requested, i removed the coverage from Node.js 8.
=> Added Node.js 9 support, removed Node.js 7 

.editorconfig, .github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .markdownlint.json, CHANGELOG.md, MAINTAINERS.md, Makefile, README.md, docs/README.md, docs/_includes/backers.md, docs/_includes/sponsors.md, docs/index.md, package-lock.json, package.json
add `@mocha/markdownlint-cli`; closes #3172
- forked [markdownlint-cli](https://npm.im/markdownlint-cli) to fix a glob-related bug; will abandon our version if/when it's merged
- add `.markdownlint.json` config
- remove "allow trailing spaces" for Markdown in `.editorconfig`
- add to `lint` target & create `markdownlint` script in `package.json`, which is dumb, but we're stuck with it for now
- linted the markdown
=> lint the markdown, closes #3172

docs/index.md
add --no-timeouts to docs
Is this all that #3137 is asking for or is there more to be done?
none - doc change only
=> add --no-timeouts to docs; closes #3137 

docs/index.md
=> [Document]: Error/undefined params to the 'done' callback

netlify.toml
The Netlify build configuration currently only resides in their admin panel. This configuration file should hopefully override those settings to allow outside contributors to make refactoring changes
Refs https://github.com/mochajs/mocha/pull/3195
I'm letting this first build run with a non-valid configuration to see it fail. Then I'll switch it over to be in sync with the admin panel. After merge, current PR's can rebase and make changes to it
=> Added Netlify config file

karma.conf.js
Now that we're running our headless tests under Chrome, the ESM tests become more straightforward.
=> update ESM tests to run against headless chrome instead of saucelabs' chrome only

docs/_includes/backers.md, docs/_includes/sponsors.md, package.json
This should add the right class and id definitions as they are currently missing.
Right image dimensions.
Docs
=> fix id and class definition

bin/_mocha, docs/index.md, test/integration/fixtures/options/file-alpha.fixture.js, test/integration/fixtures/options/file-beta.fixture.js, test/integration/fixtures/options/file-theta.fixture.js, test/integration/helpers.js, test/integration/options.spec.js
This is to resolve #3181.
I was a little unsure how to describe this change. I think including something about how these args are ran first should be noted but I'm not exactly sure how best to do that.
Also I didn't do any file path sanitization to anything passed into `--file` nor did I apply `--recursive` to the path as right now I'm of the mind that any file passed to this argument should be explicit and not be effected by any sibling flags.
Happy to change anything that people disagree with.
Also apologies for the trailing whitespace cleanup, that was done by my editor. Happy to remove that change if you want.
Cheers! Excited to contribute! :D
=> Add ability to pass in test files to be ran before positional files via --file

docs/index.md
Re: #3135, some of the features on the index page don't have corresponding links. This PR adds a detail link for one of the features.
N/A
Docs change
More consistent docs and more details re: core features.
Docs only, no real drawbacks
* #3135
=> docs(index): add missing doc link

.editorconfig, .github/CONTRIBUTING.md, docs/index.md, karma.conf.js
- remove stuff from `.editorconfig`
- remove reference in `CONTRIBUTING.md`
- remove reference in `karma.conf.js`
- remove reference in docs in reference to the `doc` reporter
I don't know how this could possibly break the build, but here it is.
=> remove more references to make and Makefile

docs/index.md
`.coffee` doesn't supported now. And I enhance the explanation of glob.
Please check my English sentences.
N/A
`.coffee` doesn't supported now.
Users don't confuse anymore.
N/A
Close #3132
Close #3098
=> update docs for the glob

lib/runnable.js, test/integration/fixtures/multiple-done-with-error.fixture.js, test/integration/multiple-done.spec.js, test/unit/runnable.spec.js
- this means "multiple calls to done" will once again fail to produce a stack trace in the case that those multiple calls happen in separate tasks.
- however, if the `done()` is called with an error, Mocha will emit that error, but also a note about multiple calls
- some reformatting, evidently
- removed some pointless checks of Mocha's exit code from "multiple done" integration tests
=> fix memory leak when run in v8; closes #3119

wallaby.js
Added Wallaby config file as discussed at https://github.com/wallabyjs/public/issues/1490#issuecomment-361173303.
n/a
n/a
Mocha contributors who are using Wallaby can continuously run mocha tests.
n/a
n/a
=> add working wallaby config

package.json
Fixes https://github.com/mochajs/mocha/issues/3248. Thanks @Bamieh and @kumavis!
N/A
Explained in #3248 already.
Mocha will have no licensing issues.
I will become a core contributor to Mocha's package.json, although I'm Pythonista. I hope I'll still find tolerance in the world after this gets merged.
* https://github.com/mochajs/mocha/issues/3248
Regarding major/minor/patch, I'd say it's a patch (fix).
=> Update to correctly licensed browser-stdout version

lib/utils.js, test/node-unit/stack-trace-filter.spec.js
As #3093 ,  when paths in stack trace messages have a current working directory as infix, it should not be replaced.  So, I added `(` in front of `cwd` to replace only in a case of the paths started with `cwd`. I assumed `(` is always be there.
@ScottFreeCode suggested `'escape-string-regexp'` package. However, I don't understand how it fixes this issue.
It is related with display stack trace in mocah.
This is an edge case, so the most of users don't experience the issue. Some users like in docker can see correct path in a stack trace.
If a case of `(` …
=> Persist paths in stack trace which have cwd as infix

lib/reporters/base.js, test/reporters/base.spec.js
PR based on suggestion by @segrey in https://github.com/mochajs/mocha/pull/3201#issuecomment-358933824. Exposed function `generateDiff(expected, actual)` as a static member of `Base`.
The value of `Base.inlineDiffs` is used to determine the form of the diff.
#3201
Allows IDE's to produce nice output when integrated with mocha.
See #3011.
=> Exposes generation of diffs from base reporter

package.json
* Bump dep "diff" to 3.5.0
N/A
diff@3.3.1 has ReDoS vuln: https://snyk.io/test/npm/mocha/5.0.2?severity=high&severity=medium&severity=low
https://snyk.io/vuln/npm:diff:20180305
=> fix: ReDoS vuln in mocha@5.0.2 › diff@3.3.1

lib/utils.js, test/node-unit/file-utils.spec.js
In https://github.com/mochajs/mocha/commit/ec8901a23c5194b6f7e6eee9c2568e5020c944ce , `utils.files` is removed, but it still used in https://github.com/mochajs/mocha/blob/master/bin/_mocha#L532 . So, running mocha with watch mode raised a error with v5.0.2. See #3265 . We should re-release new version.
```sh
mocha --watch
/Users/outsider/temp/mocha-test/node_modules/mocha/bin/_mocha:532
const watchFiles = utils.files(cwd, [ 'js' ].concat(program.watchExtensions));
^
TypeError: utils.files is not a function
at Object.<anonymous> (/Users/outsider/temp/mocha-test/node_modules/mocha/bin/_mocha:532:28)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
at tryModuleLoad (module.js:499:12)
at Function.Module._load …
```
=> restore removed methods which still used

.travis.yml
Seems like `PHANTOMJS_CDNURL` is not needed anymore now that PhantomJS support is [depracated](https://github.com/mochajs/mocha/blob/6a796cbbcd6c9f805e482c424327c82ed0398dbf/CHANGELOG.md#compatibility).
Please ignore if I am wrong.
* Remove `PHANTOMJS_CDNURL` from `.travis.yml` because it is not used anymore.
* Minor edit to comment
* Remove cruft
=> chore(ci): Remove PHANTOMJS_CDNURL, nit

CHANGELOG.md
I was checking the changelog of the latest versions and realized that some PR links had the wrong URL. They were `https://github.com/mochajs/mocha/pulls/:id` and they should be `.../pull/:id`.
This PR fixes those broken links.
=> fix(changelog): fix links to some PRs

lib/interfaces/common.js, test/integration/fixtures/pending/skip-hierarchy.fixture.js, test/integration/pending.spec.js
As my local test for #3184, `describe.skip` without a callback couldn't keep a hierarchy of suites.
For Instance.
```js
var assert = require('assert');
describe("Some tests", function(){
describe.skip("Some disabled test", function() {});
});
describe("Some other tests", function(){
it("should still pass", function(){
assert.equal(1,1);
});
});
```
is show below output.
```sh
Some other tests
✓ should still pass
1 passing (5ms)
```
It is correct. But when omit a callback in `describe.skip`.
```js
var assert = require('assert');
describe("Some tests", …
```
=> keep hierarchy for skipped suites w/o a callback

lib/runner.js, test/integration/fixtures/options/bail-with-after.fixture.js, test/integration/options.spec.js
With bail option, all tests must be stopped after first test failure. However, bail option doesn't stop hooks such as `after` or `afterEach`. 
I have no idea.
It's a bug. It makes bail works correctly.
A user can use bail intentionally.
No.
Fix  #3096 .
It is patch release.
=> fix to bail option works properly with hooks

docs/index.md
Fixes #3133 
Rewording of part of the documentation
Based on the proposed rewording, I proposed the one that makes more sense
N/A
Better understanding for users
None
Bugfix
=> chore(docs): rewording pending tests

package-scripts.js, scripts/travis-before-script.sh, test/bundle/amd.spec.js
As #3208 , I moved checking AMD bundle into `package-script.js`.
I'm not sure the name which is`test.browser.amd` is properly.
I considered between `nps lint.amd` and `npm test.browser.amd`.
I thought it is a kind of testing rather than linting.
See #3208
Developers can run it locally.
N/A
Fix #3208
=> extract checking AMD bundle as own test command

lib/runnable.js, lib/suite.js, test/unit/runnable.spec.js
- all `Runnable`s *should* now have a `file` property (in Node.js)
- filepath is appended to the `Error` message in parens
- DRY-style refactors
* * *
this could be formatted differently.
Because I wanted to send a PR for the oldest issue I could find
Somebody wanted this, once upon a time
Any machine trying to parse these errors may run into difficulties
=> append filepath to "timeout exceeded" exception; closes #627

bin/_mocha
Changes the behaviour of  the `--watch-extensions` option. No longer includes `js` by default, meaning that the specified list becomes an exclusive and not an additional set of extensions.
Closes #3275.
Mocha will not behave as expected for people who rely on `js` files always being watched.
#3275
=> remove default js in "--watch-extensions" option; closes #3275

test/reporters/base.spec.js, test/reporters/doc.spec.js, test/reporters/dot.spec.js, test/reporters/helpers.js, test/reporters/json-stream.spec.js, test/reporters/json.spec.js, test/reporters/landing.spec.js, test/reporters/list.spec.js, test/reporters/markdown.spec.js, test/reporters/min.spec.js, test/reporters/nyan.spec.js, test/reporters/progress.spec.js, test/reporters/spec.spec.js, test/reporters/tap.spec.js, test/reporters/xunit.spec.js
In reference to issue: #3260 
I did my best at refactoring the code. Though the part of the test files that was quite obviously capable to become more modular was the runner events. I could make all of those calls from one function, ie:
```javascript
runner.on = runner.once = function...
// into
runner.on = runner.once = runnerEvent(whatevery necessary parameters);
```
Otherwise I tried to make variables that I noticed were repeatedly called throughout singular files to be called only one time rather then the continual `var something = 'something'` over and over.
I believe that it can still be worked on. It is not perfect. The `runnerEvent` function could be more beautiful/intuitive. Some tests can make more sense. BaseReporter tests run but it is not obvious, I have no idea how i'd …
=> Refactor Reporter tests

.travis.yml
Introduce TravisCI build stages; it's still beta to make our builds more obviously and easier to understand. It groups our builds as `lint` or `test.`
I run linting first and then run tests because linting is much cheaper than tests.
We can add more stages.
For example, we can use a `build` stage instead `before_script` or a `coverage` stage instead `after_success`.
IMO, it's more obviously, but it's tiny.
I'm not sure that we should use this yet. It's still beta.
Easy to understand our build status.
If there are some bugs in this feature or Travis change something, our build might be broken, or we should update our `.travis.yml`.
https://github.com/mochajs/mocha/issues/3292
=> use build stages for Travis CI

.travis.yml, karma.conf.js, package-lock.json, scripts/travis-before-install.sh, scripts/travis-before-script.sh
- fiddle with caching 
- don't cache for smoke tests
- npm@5 comes with node@8 or newer, so cache `~/.npm` as well
- otherwise, don't.
- smoke test for each node.js version (stage 1)
- lint (stage 2)
- tests for each node.js version and browsers (stage 3)
- addons (artifacts, sauce labs, chrome) are only present for browser tests!
YAML aliases are basically voodoo.
=> update stages and build matrices

.travis.yml
This change "warms up"  the npm caches for Node.js 9 jobs, since it will be reused during the build.  It re-enables caching for Node.js 8, 6 and 4, since I RTFM'd more closely. 😬 
From the Travis-CI [docs](https://docs.travis-ci.com/user/caching):
> There is one cache per branch and language version/ compiler version/ JDK version/ Gemfile location/ etc.
1. for the smoke tests, we do a *production only* install per node.js version.  we do NOT want to cache `node_modules` or `~/.npm`, since it should always reflect what a user would get.
1. we warm up the cache; basically this runs a *full* `npm install` for node.js 9 with *no global environment variables*
1. we lint, using the warmed-up cache
1. tests:
- we run node.js tests in 9 *and* browser tests using the warmed-up cache
- we run …
=> improve caching performance in CI

.travis.yml
- cache npm itself
- use `npm ci`
- cache the npm cache
- ignore scripts when installing unless necessary
- cache `node_modules` for `npm install`-using smoke tests
- prefer flags over env vars
=> further build improvements

.travis.yml
there's some weird bug on Travis CI where it doesn't respect the `PATH` as set in `env`.  It may have to do with the thing where it adds `./node_modules/.bin` to the `PATH`, which is travis-ci/travis-ci#8813.
Anyway, this works around the problem.
=> PATH workaround for Travis CI bug

netlify.toml, package-scripts.js
- optimize the output of `npm start` (help) by showing only interesting scripts
- ensure "bundle" tests are running
- move "non-TTY" tests into Node.js tests
- rearrange doc-related scripts
- normalize the descriptions somewhat
Signed-off-by: Christopher Hiller <boneskull@boneskull.com>
=> optimize package-scripts.js

lib/reporters/json.js, test/reporters/json.spec.js
=> fix circular objects in json reporter; closes #2433

lib/reporters/tap.js, test/reporters/tap.spec.js
=> Tap reporter: report thrown error messages

.eslintrc.yml, bin/.eslintrc.yml, docs/.eslintrc.yml, lib/browser/.eslintrc.yml, scripts/.eslintrc.yml, test/.eslintrc.yml, test/reporters/helpers.js, test/unit/grep.spec.js
- we weren't being strict enough about disallowing ES6.  even though we
had `es6: false` in the config, the `parserOptions` were set to use
`ecmaVersion: 8`.  oops
- linted a couple files
- deleted all `.eslintrc.yml` files except for the root one; use `overrides` instead
=> fix ESLint problems and consolidate configuration

test/integration/fixtures/diffs/diffs.fixture.js
`new Buffer()` is set to be run time deprecated in node v10 (see https://github.com/nodejs/node/issues/19079 and https://nodejs.org/api/deprecations.html#deprecations_dep0005_buffer_constructor).
I swapped out the usage of `new Buffer()` for `Buffer.from()` in mocha's integration tests.
This should be semver patch.
=> replace deprecated New Buffer() with Buffer.from()

.eslintrc.yml, .gitattributes, .travis.yml, appveyor.yml, package-lock.json, test/node-unit/file-utils.spec.js
AFAIK Node.js v9.x is no longer maintained as of today.
=> add Node.js v10 to matrix

bin/_mocha
As far as I can tell, this is useless, because [this call](https://github.com/mochajs/mocha/compare/dead-reporter-code?expand=1#diff-789b16a197fe1df6ad7686554bb32265R368) actually does all of that already.
(prompted by @plroebuck's [comment](https://github.com/mochajs/mocha/commit/55ebbdbf6bcc1e4b45f497ff68420df33859cb88#commitcomment-28763932))
=> remove dead code in bin/_mocha

bin/options.js, docs/index.md, test/integration/regression.spec.js, test/mocha.opts
Modified code to strip comment lines [lines beginning with a hash character ('#')] from "mocha.opts" prior to processing its contents. Inline comments are **not** supported.
See related issues in #3370.
One used JS comments '//', but most everyone agreed hash '#' was more fitting.
Others got bogged down attempting to figure out how to support inline comments.
N/A
* Allows user to document the arguments in the options file.
* An argument can now be commented out, but left in file. (user request)
None to knowledge
Fixes #3370
(minor/patch release)? yes
This is an enhancement with no impact on production code; could go with either.
=> 3370: Add support for comment lines in "mocha.opts"

docs/index.md
Remove installing mocha via bower instruction because mocha no longer supports bower installs.
Remove installing mocha via bower instruction because mocha no longer supports bower installs.  See the [comments](https://github.com/mochajs/mocha/pull/3364#discussion_r185073819)
N/A
Mocha no longer supports bower installs
N/A
N/A
#3369
=> Remove bower install instructions

bin/_mocha
I dont see this function used anywhere, also stop now just spits `\u001b[2K` to the stdout for the rerun, I am not sure if it is needed as well.
=> remove play from bin/_mocha

docs/index.md
In [docs](https://mochajs.org/#usage), CLI usage is outdated.
I updated them with current CLI options.
=> update docs with latest cli options

MAINTAINERS.md
I've changed the links to the code of conduct to lead where I expect them (the code of conduct) and not to the changelog.
There is a larger fix to MAINTAINERS.md by https://github.com/plroebuck/mocha/commit/1d8afbf3dc6a6c110b15f6f25fa3b08edad6814c which utilizes much more fancy reference-style links which would probably be nice but I wanted to make as small a change as needed to fix the issue at hand
Helping people find the code of conduct improves life for all. :two_hearts: 
Links in documentation lead where you expect them.
The element of discovery and exploration amidst hyperlinks between documentation is lost.
https://github.com/mochajs/mocha/issues/3450
=> resolves #3450: fixed links to "code of conduct" from MAINTAINERS.md

docs/README.md, docs/index.md
In [mocha homepage](https://mochajs.org/#running-mocha-in-the-browser), the example for browsers is too old. It works but mocha doesn't provide `mocha.js`/`mocha.css` in repo anymore. 
So, beginners are hard to use the example.
Additionally, I found that [docs/README.md](https://github.com/mochajs/mocha/blob/master/docs/README.md) is not updated to use `nps`. I updated the script for users can build the docs on local.
I use [unpkg](https://unpkg.com/#/) as CDN in example. I'm not sure which js CDN is popular in developers. If there is another CDN which developers are familiar, I can update it.
I use [chai.js](http://www.chaijs.com/) in the example. I believe chai.js is more popular than expect.js now.
The example is helpful to beginners.
Developers can use the example and build docs in …
=> Update an example for browsers in docs

lib/reporters/dot.js, test/reporters/dot.spec.js
Although there is [a slow test case](https://github.com/mochajs/mocha/blob/master/test/reporters/dot.spec.js#L98-L107) for dot reporter, 
[coverage](https://coveralls.io/builds/19145852/source?filename=lib/reporters/dot.js#L51) is missed.
Since slow duration is 2(`slow: function() { return 2; }`) and test duration is 2 (`test.duration = 2;`), 
this test is not check slow test actually.
N/A
Tests should be run as intended.
=> fix slow test for dot reporter

lib/mocha.js
Replaced all method headers with more complete documentation, better following recommended styles. Eliminated `@api` tags, as `@access` _should_ imply same. Used `@chainable` to denote class methods returning `this` instance.
Renamed a handful of variables, but **no logic changes**!
N/A
N/A
API documentation will be more useful if more complete.
N/A
semver-patch
=> docs(lib/mocha.js): Update API documentation

.github/CONTRIBUTING.md, README.md
I want to start contributing more to mocha from a code and documentation perspective and thought I'd start the same way I do with any other repo, by reading the CONTRIBUTING.md.  In doing so, I found some broken links, as well as a reference to a node version no longer in LTS.  This PR addresses those issues, as well as adds a link the README.md file, so that the information required to help others contribute is more easily found before they make their first commit.
I think it will be useful to others that wish to contribute.  Broken links and outdated information can be frustrating for folks.
Improved contributing documentation.
None.
semver-patch
=> Improve Contributing Docs

browser-entry.js
As noted by @plroebuck `level` is not used, should be `label` instead.
https://github.com/mochajs/mocha/commit/37193a432119be643b9476f97da557a6f60b7d0f#commitcomment-30530038
=> Remove stdout: prefix from browser reporter logs

lib/runner.js, test/unit/throw.spec.js
Any non-extensible type thrown in an async callback raises an exception in Mocha runner, stopping tests.
See issue #3320
See PR #3321 for additional discussion.
Tests continue and reports errors properly
Fixes #3320
=> #3320 Native types exceptions can crash Mocha runner

.travis.yml, appveyor.yml
Installed binary needed for Linux desktop notification support as part of TravisCI job setup.
Installed binary needed for Windows desktop notification support as part of Appveyor job setup.
N/A
N/A
Misleading Growl-related spawn errors (unrelated to what is being tested) will no longer appear
in TravisCI nor Appveyor job output.
Tests will take slightly longer (<10s) to complete due to APT package install on TravisCI.
Timing not provided for Appveyor.
Fixes #3483
semver-patch
=> 3483: Squelch CI Growl-related spawn errors

test/reporters/base.spec.js
The `Base` reporter's specification verifies reporter can interpret Chai custom error messages.
This test takes ~480ms on my somewhat memory-starved computer, which is _way_ too close to the 500ms timeout.
Change doubles this timeout.
* Could move the Chai require (which is likely culprit), but its scope would expand.
* Could increase timeout, but retain the existing Chai require's test scope.
Prevention of random test failure due to timing issue.
Failure strikes often on Appveyor (for me anyway).
None to knowledge.
Fixes #3524
semver-patch
=> test(base.spec.js): Fix Base reporter test failure due to timeout

bin/_mocha, docs/index.md, package-lock.json, package.json
In `mocha`'s help, it shows nothing if the default value is an empty array. It is confusing for users.
```console
--globals <names>                       allow the given comma-delimited global [names] (default: )
```
[commander v2.19.0](https://github.com/tj/commander.js/releases/tag/v2.19.0) fixed the display of falsy default values in its `--help` output.
This change updates our package dependency to this version of `tj/commander.js`.
N/A
`default: ` without a value is rather meaningless.
Now, it will show:
```console
--globals <names>                       allow the given comma-delimited global [names] (default: [])
```
Fixes #3433
See [tj/commander.js/#855](https://github.com/tj/commander.js/issues/855)
=> update commander to show empty array as default value

bin/options.js
Minor refactoring of existing code.
Improves readability and beefs up documentation, especially of parsing.
N/A
semver-patch
=> refactor(bin/options.js): Improve readability and documentation

lib/reporters/json-stream.js
* Made all output directly use `process.stdout`. 
* `process.stdout` and `console.log` take different routes to get to same place
* Corrected ctor name.
* Updated documentation.
N/A
Consistency. [Don't cross the streams](https://www.youtube.com/watch?v=wyKQe_i9yyo)!
N/A
Fixes #3526
Fixes #3521
semver-patch
=> refactor(json-stream.js): Consistent output stream usage

bin/_mocha, docs/index.md
Previously undocumented that use of `--inspect` would disable timeouts.
N/A
N/A
YA aspect of previously undocumented Mocha is no more.
None.
Fixes #3519
semver-patch
=> Update '--no-timeouts' argument description

.eslintignore, .gitignore
Prettier-ESLint keeps busying itself with the JSDoc output directory, spewing hundreds of errors.
This tells both ESLint and Git to ignore the directory.
Allows local use of JSDoc without it affecting any potential commit.
None
semver-patch
=> build(ESLint/Git): Ignore JSDoc output directory

.travis.yml, appveyor.yml
Node-11 is [freshmeat](https://medium.com/@nodejs/october-brings-node-js-10-x-to-lts-and-node-js-11-to-current-ae19f8f12b51). Node-9 is officially dead -- technically, it reached its sell-by date at the end of June, but it took a while for us to figure out where the smell in the refrigerator was coming from.
As such, CI-wise:
* Node-11 becomes the _new_ default version of Node for build matrix.
* Node-9 removed from build matrix.
Changeover went smoothly -- everything working without issue. 
N/A
N/A
Testing Mocha against all _officially_ supported versions of Node.
None. Trivially reverted
Node.js Foundation RWG - [Release Schedule](https://github.com/nodejs/Release)
=> ci(Travis/Appveyor): Update Node versions in CI matrix

lib/runner.js, test/unit/mocha.spec.js
Using mocha programmatically, the mocha runner doesn't emit start/end event correctly.
Because both events emitted before event listeners are registered. So, this change is fixed to emit events in event loop.
I have no idea.
This is a bug.
Users can get start/end event correctly.
close #2753
=> fix runner to emit start/end event

lib/reporters/xunit.js, test/reporters/xunit.spec.js
XUnit reporter should show diffs as output
XUnit reporter was already in core
You can tell actual vs. expected which is very helpful and the default in the default reporter.
People wrote parsers.
This is an enhancement.
=> Show diff in xunit

test/reporters/doc.spec.js, test/reporters/dot.spec.js, test/reporters/helpers.js, test/reporters/json-stream.spec.js, test/reporters/landing.spec.js, test/reporters/list.spec.js, test/reporters/markdown.spec.js, test/reporters/min.spec.js, test/reporters/nyan.spec.js, test/reporters/progress.spec.js, test/reporters/spec.spec.js, test/reporters/tap.spec.js
As refactoring [dot reporter tests](https://github.com/mochajs/mocha/pull/3486), capturing output for all reporter tests moves to [`test/reporters/helpers.js`](https://github.com/mochajs/mocha/pull/3528/files#diff-04e8353a17acf7c3591b1b83eef5d6b8)(`createMockReporter`). And it has `tee` to show reporter's output in running tests.
N/A
* Greatly simplifies setup/teardown related to capturing screen output, reducing possibility of error.
* Reporter tests are more maintainable and easier to follow.
* Reporter test screen output is no longer echo'd by default, pruning individual test output minutiae.
New contributors will be lulled into thinking writing new tests for Mocha is pretty trivial.  **LOL**
semver-patch
=> Extract runReporter to capture output under tests

package.json
- this will fix a problem with npm (potentially) publishing certain files
which should always be ignored; see npm/npm-packlist#14.
- also fixes issue with growl images not getting published!
PRO TIP: use `npm pack --dry-run` to see what would be included in
published tarball.
=> update list of published files in package.json

lib/runnable.js, lib/utils.js, test/unit/runnable.spec.js
Original PR _partially_ fixed the problem of specifying a timeout value that was too large;
unfortunately, it did not account for string-based timestamp translation.
This corrects that, and updates the function documentation.
N/A
N/A
All timeout values are now range limited, as originally intended.
None.
Fixes #1652
Fixes #2951 
semver-patch
=> Prevent timeout value from skirting limit check

appveyor.yml
GfW developer retired his public website last week, which causes **all** Mocha AppVeyor builds to fail (as they can't download the installer). This patch uses his GitHub URL instead. Additionally, this starts Growl much earlier (after its installation) to allow more time before use. Now displays Windows OS info prior to starting tests.
N/A
N/A
AppVeyor will start working again
None
semver-patch
=> ci(appveyor.yml): Fix Growl install

.travis.yml, appveyor.yml
Mocha's requirement for using `npm-5` in CI scripts was due to `npm-6` dropping support for `Node-4`. As we have since dropped `Node-4` support, we should use the current version of `npm`. This _should_ have been done as part of PR 3364.
Eliminate `npm-5` "Unsupported Node version" warnings when run against current version of Node.
None to knowledge.
See <https://github.com/mochajs/mocha/pull/3350#issuecomment-384703961>
Blocked by #3364 (merge after) 
semver-patch
=> ci(.travis.yml,appveyor.yml): Use current npm version in CI scripts

package-scripts.js
=> use `--forbid-only in CI

lib/reporters/base.js, lib/runner.js, lib/stats-collector.js, test/reporters/helpers.js, test/reporters/list.spec.js, test/reporters/xunit.spec.js
- a very small abstraction of stats collecting into a dedicated module
- "runner" now initiates collecting
- presentation is still handled by reporter
- no context is maintained internally, so invoked as normal function
- an API for querying could be introduced but felt overkill unless others thought it worthwhile
- currently called from Base reporter but if it is useful the reporters could call it directly themselves (so we could interchange collectors).
- I was not sure if this should be called by Base reporter or the runner, so I chose reporter. If anyone else has opinions please let me know
- stats handling is not so closely tied to the Base reporter,
- easier to extend, test, isolate, enhance stats collecting
Fixes #3256
(semver-minor)
=> Refactor statistics

docs/index.md, lib/runner.js, test/integration/fixtures/pending/skip-async-before-hooks.fixture.js, test/integration/fixtures/pending/skip-async-before-nested.fixture.js, test/integration/fixtures/pending/skip-async-before.fixture.js, test/integration/fixtures/pending/skip-async-beforeEach.fixture.js, test/integration/fixtures/pending/skip-async-spec.fixture.js, test/integration/fixtures/pending/skip-sync-before-hooks.fixture.js, test/integration/fixtures/pending/skip-sync-before-nested.fixture.js, test/integration/fixtures/pending/skip-sync-before.fixture.js, test/integration/fixtures/pending/skip-sync-beforeEach.fixture.js, test/integration/fixtures/pending/skip-sync-spec.fixture.js, test/integration/pending.spec.js
This PR contains a possible fix for [Issue 2819](https://github.com/mochajs/mocha/issues/2819).
Let me preface this by saying I'm new to open source contributing, so if I messed something up please let me know. I assure you in advance that it was an unintentional mistake rather than deliberate violation of the rules. :)
I adapted this change from [Elergy's PR](https://github.com/mochajs/mocha/pull/2836/files), since it seemed to be stuck in a limbo. I also referred to [this discussion](https://github.com/mochajs/mocha/pull/2571) regarding skip and hooks. It seems like all the discussions have been inactive for a while, so I'm interested to know if there's been a resolution.
Changes:
- Added integration tests for `this.skip` in `before` that verify hooks don't execute and nested describes …
=> Issue/2819 - Fix / Clarify this.skip behavior in before hooks

lib/interfaces/common.js, test/integration/fixtures/options/forbid-only/only-empty-suite.js, test/integration/fixtures/options/forbid-pending/skip-empty-suite.js, test/integration/helpers.js, test/integration/options.spec.js, test/reporters/base.spec.js
As #2944 , `--forbid-only` didn't catch an empty suite that marked as only because checking `forbidOnly` is happened in [`runTest`](https://github.com/mochajs/mocha/blob/master/lib/runner.js#L435).
So, I added `forbidOnly` check in `runSuite` when there is no greped tests and there are `_onlySuites`. To run `forbidOnly` check in `runTest`, I made new empty test here.
Not delegate `runTest` for `forbidOnly`,  throw forbid error in `runSuite`?
If there is an empty suite that marked only, tests will be passed with `--forbid-only` option.
If I added an empty test with no title, there is no test name in output. It looks a little bit weired. Any idea?
```
nothing
1)
0 passing (3ms)
1 failing
1) nothing
:
Error: `.only` forbidden
at Runner.runTest (lib/runner.js:436:8)
at …
```
=> --forbid-only and --forbid-pending now handle suites properly

lib/utils.js, test/unit/utils.spec.js
isPromise would crash if given `null`, so I made it check for null too.
---
This is an enhancement.
=> make isPromise support null as a parameter

docs/index.md, package-lock.json, package.json
Close #3610
https://mochajs.org/ is down because static files is not generated under `docs/_dist`.
I don't know why updating assetgraph-builder is missing is https://github.com/mochajs/mocha/commit/8750ef892b8b8013d637e2b80517158e5afc90c4 and why the static files is not generated with assetgraph-builder v5.x.
=> update assetgraph-builder to latest

lib/stats-collector.js
Unless we have a good reason to do so, I think new APIs should default to private.
@craigtaub what are your thoughts?  Is there any valid use case for this (outside of how we're using it) that you can think of?
`semver-minor` since it's new stuff anyway, but doesn't really matter.
=> make lib/stats-collector a private API

lib/cli/run-helpers.js
* Fix for 'Unable to terminate tests manually, e.g via Ctrl+C when running tests in a terminal.'
* refer issue #3570 
* Updated the SIGINT handler.
* A function property set to check if 'SIGINT' was called first time.
* if 'SIGINT" is called first time,keep the current behavior. 
* invoke 'SIGINT' again after 2 seconds which will kill the current process if still running. 
see #3570
=> modified SIGINT handling #3570

lib/reporters/xunit.js, test/reporters/xunit.spec.js
Per http://reflex.gforge.inria.fr/xunit.html#xunitReport a failure and an error are different concepts and must be counted as such. Some parsers will fail if the number of expected tests do not add up.
=> Dont count xunit failures as errors

docs/index.md, lib/runner.js, test/integration/fixtures/options/bail-async.fixture.js, test/integration/fixtures/options/bail-with-afterEach.fixture.js, test/integration/fixtures/options/bail-with-before.fixture.js, test/integration/fixtures/options/bail-with-beforeEach.fixture.js, test/integration/fixtures/options/bail-with-test.fixture.js, test/integration/fixtures/options/bail.fixture.js, test/integration/options.spec.js, test/unit/runner.spec.js
It hasn't been clearly defined yet wether `after`/`afterEach` hooks should run after a failing test. Since merging issue #3278 `after`/`afterEach` hooks are not beeing executed anymore.
This was a big change in event behavior and quite a few users complained about.
Reading many posts (of maintainers also) I dare to claim that those hooks should run in order to guarantee a correct cleanup.
current pattern with failing test:
- --bail: the `end` event is triggered twice (which is bug). The first time `after`/`afterEach` hooks are not executed, with the second `end` event they are actually called.
- --bail and --exit: none of the `after`/`afterEach` hooks is called.
proposed pattern: (required changes are marked **bold**)
- `before` hook:
- `bail: false`: failed `before` hook skips all tests …
=> Behavior of after/afterEach hooks with --bail flag

test/reporters/xunit.spec.js
Changed spelling from "truthly" to "truthy".
semver-patch
=> Fix spelling

.wallaby.js, lib/utils.js, package-scripts.js, test/unit/utils.spec.js
Mainly trying to get coverage up.
Also a tweak to Wallaby config, and one to coverage computation which will zap `.nyc_output/` between `npm test` runs to ensure the data isn't stale.
=> add more tests for utils.deprecate

test/node-unit/cli/run-helpers.spec.js
I was testing Mocha's compatibility with the upcoming version of Unexpected. For that version we remove support for satisfying against a function as that has confused people. 
I found one test that will fail with the next version as it was using `to throw` to satisfy against an error. This test will actually just call `TypeError` with the throw error, so it wont really check anything. This PR fixes the test to assert that the throw error is a `TypeError`.
Bugfix.
None
=> Fixed wrong use of to throw that will fail with unexpected v11

lib/mocha.js
#3634 suggests removing this warning because this warning has been around for 5 years (see https://github.com/mochajs/mocha/commit/1a4ab63f55b0af7305361396a520058e3779203d) so it is unlikely anyone still depends on it.
N/A
N/A
Fewer branches to cover and less unnecessary code.
Someone upgrading directly from 1.x to 6.x may be confused where their reporter went.
#3634, patch release
=> remove teamcity reporter warning (#3634)

docs/_includes/head.html, docs/index.md
Provide a description for search engines, they tend to like it.
=> Description meta tag

lib/cli/run-helpers.js, lib/utils.js, test/integration/glob.spec.js
Previously would print a warning for each missing file/dir, then an error if no valid files were found.
Now prints slimmer warnings and errors only if no tests found.
Tests cover both scenarios.
Print an error for each missing file/dir (and no final error). Still exit if no valid files were found.
Nasty as flags everything as an error even if there is a passing test
Command: `mocha`
New output:
```
Error: Cannot find any files matching pattern "test/"
```
Previous output:
```
Warning: cannot find any files matching pattern "test/": 'test/'
✖ No test files found
```
Difference = No warning and slimmer message
Command: `mocha -R json-stream --no-config "test/integration/fixtures/glob/**/*-none.js"`
New output:
```
Error: Cannot find any files matching pattern …
```
=> Fix message if no files found

lib/utils.js
No order is implied via fs.readdir(). Different OS/filesystem combinations can give different results via readdir(3) which returns directory entries in traversal order (e.g., on macOS, HFS+ uses lexical order and APFS uses filename hash order).
This patch updates our API documentation to denote this.
Closes #3599
=> Update API documentation concerning fs.readdir()

lib/mocha.js, lib/suite.js, test/unit/suite.spec.js
Currently every suite with an empty string title "" has set its property `suite.root === true`, see [here](https://github.com/mochajs/mocha/blob/master/lib/suite.js#L69). This is a bug since there can be only one root suite and a deficient test tree would be the result.
```js
'use strict';
var emptyTitleSuite1;
describe('suite1', function() {
var rootSuite = this.parent;
console.log('title rootSuite: %s, root: %s', rootSuite.title || '""', rootSuite.root);
console.log('title suite1: %s, root: %s', this.title, this.root);
describe('', function() {                 <<<<< empty title
emptyTitleSuite1 = this;
console.log('title emptyTitleSuite1: %s, root: %s', this.title || '""', this.root);
console.log('rootSuite === emptyTitleSuite1:', rootSuite === this);
});
});
describe('', function() { …
```
=> Set "root" property on Suite correctly

package-lock.json, package-scripts.js, package.json
- fix prettier settings
- add `cross-env`
cc @juergba
=> fix test running on windows

lib/cli/run.js, test/integration/options.spec.js
#3656 added a couple utils for setting `code` on errors. I fixed a couple here and wanted to make sure I was on the right track before making more changes.
N/A
Codes help identify errors as mocha errors at a glance without using custom error types, and better DX is always good.
:point_up: 
None that I can see
#3656, #3125. semver-patch
=> Fix couple errors missing codes

test/integration/reporters.spec.js
* Added test for invalid reporter option for `tapVersion`
* Updated other TAP tests' cmdline args to use `--reporter-option` instead of `--reporter-options`
NA
NA
This test was missing from PR which introduced the `tapVersion` reporter option.
Increased coverage!
NA
SeeAlso #3552
semver-patch
=> Add test for TAP reporter when given invalid reporter option

lib/cli/run-helpers.js, test/integration/glob.spec.js
Scenario where multiple files (all) are not found only show a single message.
I feel its useful for debugging to keep the message if only 1 file is not found. Happy to remove if others don't agree.
No changes where at least 1 is found (still prints msg).
See PR https://github.com/mochajs/mocha/pull/3650 for full details
Command: `mocha`
Output:
```
Error: No test files found: "test/"
```
Command: `mocha -R json-stream --no-config "test/integration/fixtures/glob/**/*-none.js"`
Output:
```
Error: No test files found: "test/integration/fixtures/glob/**/*-none.js"
```
Command: `mocha -R json-stream --no-config "test/integration/fixtures/glob/**/*-none.js" "test/integration/fixtures/glob/**/*-none-again.js"`
New output
```
Error: No test files found
```
Previous output
```
Error: Cannot find …
```
=> Fix messages for file lookup issues - error scenario

.travis.yml, lib/cli/run-helpers.js
When inside `process.on('exit')`, calling `process.exit()`
stops other `exit` event listeners from being invoked.
This has lead to issues with coverage generation with `nyc`
because a fallback exit detection mechanism in it that relies
on internal Node.js APIs was accidentally disabled in Node v11.7.0,
leaving `nyc` with no way to detect process exit.
No alternatives were considered.
`process.on('exit')` handlers are run even if `exitMochaLater` is used. At least `nyc` relies on this behaviour.
I guess running extra code while exiting could have drawbacks.
This fixes https://github.com/nodejs/node/issues/25650 (which is already closed, but because Node.js is (possibly temporarily) reintroducing monkey-patching for the internal method in question, not because the underlying cause was …
=> do not recursively call `process.exit()`

test/node-unit/cli/options.spec.js, test/unit/mocha.spec.js
Avoid the use of the `was called with` assertion from unexpected-sinon. It has been deprecated for two years and will soon display warnings or even be removed.
See discussion here: https://github.com/unexpectedjs/unexpected-sinon/issues/32
Not relevant.
Not applicable, this is just a change to the test suite.
Due diligence so we don't have to deal with this later when upgrading unexpected-sinon.
None.
None.
=> Tests: Avoid the 'was called with' assertion

lib/cli/options.js, test/integration/invalid-arguments.spec.js
What was happening here was that yargs-parser's default command does error checking *but does not return the errors*.  instead, it would act like *no such argument was provided*.  this means that if you used `--ui`, it would act as if you passed nothing, then go and grab whatever the default is (in this case, `bdd`).
using the `detailed()` function of yargs-parser solves this problem.
added a test
=> ensure invalid arguments are not ignored when using bin/mocha; closes #3687

lib/runner.js, test/integration/fixtures/current-test-title.fixture.js, test/integration/fixtures/hooks/after-hook-deepnested-error.fixture.js, test/integration/fixtures/hooks/after-hook-nested-error.fixture.js, test/integration/fixtures/hooks/before-hook-deepnested-error.fixture.js, test/integration/fixtures/hooks/before-hook-nested-error.fixture.js, test/integration/fixtures/hooks/before-hook-root-error.fixture.js, test/integration/fixtures/options/bail-with-after.fixture.js, test/integration/fixtures/options/bail-with-before.fixture.js, test/integration/hook-err.spec.js, test/integration/hooks.spec.js, test/integration/multiple-done.spec.js, test/integration/options/bail.spec.js, test/unit/runner.spec.js
Mocha shows an incorrect test-title if a nested `before` hook fails. For `after` hooks the second part of the message is completely missing.
```js
describe('Top-level describe', () => {
it('Top-level it', () => { });       // the failing before-hook is pointing to this test
describe('Nested describe', () => {
before(() => {
throw new Error();
});
it('Nested it', () => { });        // but it should point to this test
});
});
```
```
Top-level describe
✓ Top-level it
Nested describe
1) "before all" hook for "Top-level it"       <<<incorrect
```
Root problem: see [#1638](https://github.com/mochajs/mocha/issues/1638). `hook.ctx.currentTest` is set incorrectly in the hook before emitting the hook event:
- `before` hook: currentTest is undefined or points to the outer test already past …
=> Fix Hook Test Names

bin/mocha, lib/utils.js, package-lock.json, test/assertions.js, test/integration/fixtures/__default__.fixture.js, test/integration/helpers.js, test/integration/options/debug.spec.js, test/unit/utils.spec.js
- add some handiness to the integration test helpers
- update docstrings in integration test helpers
Found this when looking at #3681.
=> ensure --debug becomes --inspect; closes #3697

lib/browser/growl.js, lib/growl.js
When I run exclusive tests with like `only`, growl notification show total tests count instead test count which I ran.
IMO, it should be test's count which I ran.
N/A
Growl notification show total test cases which users ran.
N/A
=> Show total test cases correctly in growl

lib/utils.js, test/unit/runner.spec.js
if the stack trace begins with a large error message (>= 20k charactors), and user leaves `--full-trace` disabled, `utils.stackTraceFilter()` takes ages to finish. Large error messages is quite possible when user makes containment assertions such as `expect(content).to.contain(word)`.
simplified the regex used in `utils.stackTraceFilter()` to boost performance therefore prevent ReDoS if the stack contains large error message.
It's possible to skip check error message in stack by skipping the first line but the regex fix won't change any behavior hence it is chosen.
well, it's a bug introduced by the stack filtering feature.
mocha won't hang even if users make assertions with large error messages, which is quite possible because containment check is used a lot.
None
#3416 looks like one …
=> fix regex in utils.stackTraceFilter to prevent ReDoS #3416

test/unit/runner.spec.js
Refactored portions of tests for (hopefully) increased clarity.
NA
NA
Easier to follow maintenance-wise... well, to me anyway.
None to knowledge
#3686
semver-patch
=> test(unit/runner.spec.js): Minor tweeks related to #3686

test/unit/runner.spec.js
Ensure that all listener function arguments were distinct from the variables being passed to emitter.
Added some additional assertions.
NA
NA
At least one test's assertions were expecting the variable against itself... (L245)
None
semver-patch
=> Eliminated variable shadowing from test event listeners (runner.spec.js)

.mocharc.yml, bin/mocha, lib/cli/node-flags.js, lib/cli/options.js, package-lock.json, package.json, test/assertions.js, test/integration/helpers.js, test/integration/options/debug.spec.js
~~this is rebased onto the branch from #3698 and thus depends on it.~~
This seems to make `--inspect` work properly with or without a parameter (`--inspect=0.0.0.0:12345`).  The `=` is required, as it's required by `node`.
In v6 of Node, `--debug --port=12345` should also work as expected.
**UPDATE** #3698 was merged
=>  fix --inspect and its ilk; closes #3681

lib/cli/run.js, test/integration/fixtures/options/reporter-with-options.fixture.js, test/integration/options/reporter-option.spec.js
adds tests for comma-separated k/v pairs and repeated `--reporter-option` usage
=> fix --reporter-option to allow comma-separated options; closes #3706

lib/cli/run-helpers.js, lib/mocha.js, test/node-unit/mocha.spec.js, test/unit/mocha.spec.js
Adds a feature which allows unloading test files from `require` cache programmatically.
This feature simplifies rerunning tests since there is no need to recreate the Mocha instance.
Currently handled by one of these options:
1. The user has to implement same logic in his own code.
1. The user has to create a new Mocha instance before each run.
A potentially more complete design could take a snapshot of the cache before testing begins and remove _everything_ added afterwards. Prefer to see how well this implementation does before going further.
1. Because it allows reuse of object instances.
1. Provides missing half of Mocha's public API referenced [here](https://github.com/mochajs/mocha/blob/d1902a20663a6766ffaae646f155a884fcf3e141/lib/mocha.js#L579-L585).
1. (Hopeful) reduction of user …
=> Add ability to unload files from `require` cache (redux)

test/integration/helpers.js
Remove unnecessary post-processing code because it does not have any effect.
```js
// test/integration/helpers.js
mocha.on('close', function(code) {
fn(null, {
<<<<<<< issues/3708
output: output,
=======
output: output.split('\n').join('\n'),
>>>>>>> master
code: code,
args: args
});
});
```
`split('\n').join('\n')` always returns the original value.
```js
> var foo = '\n\n\n\nasd\n\nasd\n\nasd\n\n\n'
> var bar = foo.split('\n').join('\n')
> foo === bar
true
```
Fixes #3708 
semver-patch
=> remove a post-processing code having no effect; closes #3708

lib/mocha.js, test/unit/mocha.spec.js
Mocha constructor (via `.globals`) creates `this.options.globals` array containing `undefined` element (which it shouldn't). Corrected `.globals` by removing falsy values.
Cleaned up Mocha unit test specification in the process.
Better error checking of arguments could have prevented the problem.
NA - already in core
Existing code has bug. This fixes it.
None.
Closes #3668 
semver-patch
=> Fix `.globals` to remove falsy values

test/reporters/json.spec.js
Uppercased JSON reporter name in `describe` title.
NA
NA
All of the other reporter test suites
Used to laugh and call him names...
None
semver-patch
=> Uppercase JSON reporter name in `describe` title

lib/cli/run.js
The old glob 'test' would allow "test.js" to be used by default (rather than requiring spec file be
placed inside "test" directory).
In minimalist repos, users were simply using "test.js" rather than "test/\<file\>.js", allowing...
```sh
$ mocha
```
NA
NA - already there
Restore compatibility with previous releases.
Prevent a boatload of more issues from minimalist repositories using Mocha.
None
Fixes #3750
semver-patch
=> Revert default glob to match Mocha-5.2

lib/interfaces/common.js, test/integration/suite.spec.js
This just kills the deprecation as I suggested [here](https://github.com/mochajs/mocha/issues/3744#issuecomment-465853188).
=> backout deprecation of value returned from suite; closes #3744

package-lock.json, package.json
Updates ['karma-browserify'](https://www.npmjs.com/package/karma-browserify) module to eliminate Karma middleware warning.
```console
WARN [middleware:karma]: Invalid file type, defaulting to js. browserify
```
As shown in the output below, the 'karma-browserify'-5.3.0 was creating its temporary file with the extension name ".browserify". This is the cause of the Karma middleware warning. 
```sh
$ TMPDIR=/tmp/karma DEBUG=*,-log4js:* karma start --log-level debug --no-auto-watch --single-run karma.conf.js
[SNIP]
22 02 2019 09:49:28.103:DEBUG [plugin]: Loading plugin /var/tmp/mocha-ya/node_modules/karma-browserify.
[SNIP]
22 02 2019 09:49:28.651:DEBUG [framework.browserify]: created browserify bundle: /tmp/karma/d188a37070bebec4a6e48de4cce2e645.browserify
22 02 2019 09:49:28.670:DEBUG …
```
=> Eliminate "noise" Karma middleware warning 

lib/cli/node-flags.js, lib/cli/options.js, test/integration/options/node-flags.spec.js, test/node-unit/cli/node-flags.spec.js
maybe not the most elegant solution, but it seems to work.
cc @nknapp @janpot
=> fix handling of bareword args matching node flags; closes #3761

lib/cli/options.js, test/node-unit/cli/options.spec.js
nobody is going to put `"_": ["file", "file"]` in a config file, *but if they do*, we have them covered.
also noticed specifying the same positional arg across various configs and such resulted in dupe filenames, so fixed that too.
=> fix broken positional arguments in config; ensure positional args are unique; closes #3763

lib/reporters/base.js, lib/reporters/doc.js, lib/reporters/dot.js, lib/reporters/html.js, lib/reporters/json-stream.js, lib/reporters/json.js, lib/reporters/landing.js, lib/reporters/list.js, lib/reporters/markdown.js, lib/reporters/min.js, lib/reporters/nyan.js, lib/reporters/progress.js, lib/reporters/spec.js, lib/reporters/tap.js, lib/reporters/xunit.js
Change allows for passing settings to _any_ reporter.
The same `options` parameter is passed to abstract `Base` superctor.
Fixed/standardized some of JSDoc as well.
Only means to pass settings to reporters.
NA
Immediately, none. Prerequisite step to further upgrades.
None, since changes only allow possibility of future changes.
semver-patch
=> Make reporter ctors support optional 'options' parameter

lib/cli/node-flags.js, test/node-unit/cli/node-flags.spec.js
Fixes support for multiple node flags. Previously, the node flags were splatted onto a single string rather than separate elements in an array of strings.
=> closes #3787 Allow passing multiple node flags

lib/browser/template.html
Use HTML5 syntax for charset declaration in "/lib/browser/template.html".
NA
NA
HTML5
None
semver-patch
=> Use HTML5 syntax for charset declaration in browser template

lib/runner.js, test/integration/fixtures/pending/skip-async-before-hooks.fixture.js, test/integration/fixtures/pending/skip-async-before-nested.fixture.js, test/integration/fixtures/pending/skip-async-before.fixture.js, test/integration/fixtures/pending/skip-async-beforeEach.fixture.js, test/integration/fixtures/pending/skip-async-spec.fixture.js, test/integration/pending.spec.js
The async call of `this.skip` in a `beforeEach` hook results in an error.
```js
'use strict';
describe('skip in beforeEach', function () {
beforeEach(function (done) {
var self = this;
setTimeout(function () {
self.skip();
done();
}, 0);
});
it('should skip this test', function () {
throw new Error('never run this test');
});
it('should not reach this test', function () {
throw new Error('never run this test');
});
it('should not reach this test', function () {
throw new Error('never run this test');
});
});
```
```
skip in beforeEach
- should skip this test
1) "before each" hook
0 passing (19ms)
1 pending
1 failing
1) skip in beforeEach
"before each" hook:
Uncaught async skip; aborting execution
```
The async `this.skip` does not abort the hook/test (as the sync version does). This is …
=> Fix this.skip() async calls

docs/_includes/default.html, docs/css/style.css
[x] Fix empty `<title>` tag
[x] Remove the favicon `<link>` tag "shortcut" relation
[x] Mocha logo `<img>` tag modifications
[x] Replace illegal footer `<span>` tag with `<div>` tag
[x] Add "home" relation to `<a>` tag for Mocha URL. Append slash ("/") to end of URL.
[x] Use "https" protocol for CC license `<a>` tag "href" URL
[x] Convert the `<p>/<em>` tags with the following `<dl>` embedding `<time>`
[x] Annotate all links to outside URLs with these relations:  "external", "noopener"
NA
NA
Cleaner, more semantic HTML5 with less errors, more security.
None to knowledge.
Fixes #3783 
Closes #3784
semver-patch
=> Completed website HTML tweaks

lib/runner.js, test/unit/runner.spec.js
When passing `--allow-uncaught`, uncaught exceptions thrown inside hooks are not surfaced. This PR enables that. Original issue: https://github.com/mochajs/mocha/issues/2302
The hook-runner is the best place to set this flag, since it has to be read from the parent context (Runner). I can't see any other way of doing given that strong dependency.
It is a missing feature, already marked as a confirmed bug (#2302 )
Tests authors can be more strict about not accepting code that throws errors as side effects. Debugging failing hooks becomes easier.
There shouldn't be drawbacks. Tests that throw errors within their hooks are most likely not setting `allowUncaught`, otherwise the browser would hang. So it remains an opt-in feature.
closes #2302 , patch release
=> set allowUncaught on hooks

lib/cli/cli.js, lib/cli/options.js, package-lock.json, package.json
as of v13.2.2, yargs has un-un-supported Node.js v6, so we can now consume it, as well as avoid the deprecation by passing the parser configuration via `parserConfiguration()` method.
=> update yargs; closes #3742

scripts/markdown-magic.config.js
* Quoted pathname used in exec, allowing for embedded spaces
* Changed codefence language to 'text'
* Saved `markdownTOC` output to variable prior to output
NA
NA
Code can now run on Windows if pathname contains spaces.
None to knowledge.
semver-patch
=> MarkdownMagic script updates

lib/mocha.js, lib/suite.js, test/unit/mocha.spec.js
IMO `Suite#timeout` should eventually do nothing if its parameter is `undefined`.  it should not be up to Mocha's constructor to guard against this.
=> guard against undefined timeout option in constructor; closes #3813

example/config/.mocharc.yml
Adds comments to `.mocharc.yml` to clarify that `--package` can be specified as a CLI argument but will be ignored within a `.mocharc` file.
Alternatively, mocha could support `package` within config files.  Then it would merge the config from package.json with the config from `.mocharc`.  But that doesn't seem useful.
N/A; this is a docs tweak.
Better docs.
N/A
N/A; this is a docs tweak.
=> Remove "package" flag from sample config file because it can only be passes as CLI arg

lib/cli/config.js, lib/cli/options.js, package-lock.json, package.json, test/node-unit/cli/config.spec.js, test/node-unit/cli/options.spec.js
This PR replaces findup-sync with find-up, which reduces mocha's startup time. Related to #3743.
An informal benchmark shows it reduces startup time by about 30%:
https://github.com/cspotcode/repros/tree/mocha-find-up-perf
https://github.com/cspotcode/repros/runs/76724994 (pardon the verbose logging; you can search for the word "real" to jump to the `time` invocations)
I considered using cosmiconfig, but this is a more minimal change that preserves mocha's existing diagnostic logging.  https://github.com/mochajs/mocha/issues/3743#issuecomment-466132812 …
=> Replace findup-sync with find-up for faster startup

lib/runner.js
In addition to #3745 
> it also appears we need this around 390
```js
if (err instanceof Pending) {
if (name === HOOK_TYPE_BEFORE_EACH || name === HOOK_TYPE_AFTER_EACH) {
if (self.test) {
self.test.pending = true;
}
} else {
```
> When Pending is thrown async like this, we might no longer have a test, which causes its own exception.
=> Fix this.skip() async calls: "self.test" undefined in Browser

docs/css/style.css
cannot pass nothing to `markdown-it-anchor` so passing span
min-height on span tag or defaults to 0 and svg doesn't show
could remove svg all together and pass link icon but then it looks too far to the left
just a doc patch
cleaner look
pretty sure span won't effect anything but i could be wrong
bug fix #3714
=> Remove pound icon showing on header hover on docs #3714

lib/suite.js, test/unit/suite.spec.js
Issue #3847 describes how reruns of the same test suite changes the test title.
This pull request fixes that issue, by making sure to copy the root property from the original suite.
The bug present in the core makes the API work in non-intuitive ways. This would remedy that.
The API will work as advertised.
N/A
- closes #3847
- Bug fix -> Patch release
=> Copy Suite root when cloning

docs/index.md, lib/runner.js, test/integration/fixtures/pending/skip-sync-after.fixture.js, test/integration/pending.spec.js
There have been long discussions about the behavior of `this.skip()` in hooks. The `before` hooks have already been clarified and fixed in #3225. The purpose of this PR is to make a decision about the behavior of `after` and `afterEach` hooks.
https://github.com/mochajs/mocha/pull/2571#issuecomment-265416756
> Skipping a test/suite after running it is a bit counter logical. The only purpose would be marking it as pending. Which is not very clean because you've already emitted `pass`/`fail` events for such test. Not sure there's value in changing the test state/outcome post-mortem.
I propose to emit a DeprecationWarning when `this.skip()` is used in `after` and `afterEach` hooks and to remove it in a future release. Besides marking an already passed/failed test as pending, there are …
=> Deprecate this.skip() for "after all" hooks

lib/cli/cli.js, test/node-unit/cli/run.spec.js
Yargs exports a global singleton by default. Using it directly will break testing apps using yargs themselves.
I followed the [best-practice example in yargs' documentation](https://github.com/yargs/yargs/blob/master/docs/advanced.md#using-the-non-singleton-interface). One test had to be adjusted slightly, using a separate yargs instance which has been reset: this is [what yargs does internally](https://github.com/yargs/yargs/blob/master/lib/command.js#L188) and required, because `run.builder()` calls `.positional()` which cannot be called on the outer yargs instance.
Makes mocha compatible with other projects depending on yargs.
If we need access to mocha's yargs instance, we'll have to expose it ourselves, instead of relying on the global one.
I think this should be a bug fix (patch …
=> Fix yargs global pollution

docs/index.md
Several doc links specified an invalid anchor, so this PR fixes `#configuring-mocha-node-js` to `#configuring-mocha-nodejs`.
Um... I don't know how this could have be done in an alternate way.
If affects documentation navigation.  
Documentation navigation will be correct.   
None 
Documentation patch
=> fixed anchors to configuration section

docs/api-tutorials/custom-reporter.md
Broken links modify to enable in the documentation,
page link below
https://mochajs.org/api/tutorial-custom-reporter.html
N/A
N/A
link enable  in the documentation
None
Fixes #3855
=> Broken links in docs

test/reporters/landing.spec.js, test/reporters/list.spec.js, test/reporters/nyan.spec.js, test/reporters/progress.spec.js
In reporter tests, shallow cloning could affect other test cases. With [sinon's sandbox](https://sinonjs.org/releases/v7.3.2/sandbox/), clean up objects after testing.
Without sinon?
Shallow cloning could be error-prone. And the code with sandbox is more readable than before.
Removed verbose code to cache previous object and recover them
Fix #3554
=> Use sinon sandbox for reporter tests

docs/index.md
Now that we have https://github.com/mochajs/mocha-examples lets point people (who are seeking help in a specific area) to the right link.
Have made a small update to the "programmatic usage" (https://github.com/mochajs/mocha/wiki/Using-Mocha-programmatically) wiki.
Same as those in https://github.com/mochajs/mocha-examples/pull/1
https://github.com/mochajs/mocha/issues/2359
=> Adds doc links for mocha-examples

lib/cli/cli.js
In [cli/cli.js](https://github.com/mochajs/mocha/blob/master/lib/cli/cli.js#L63) the arguments of the config files are passed incorrectly:
`.parse(argv, loadOptions(argv)); `
The signature: `Yargs#parse([args], [context], [parseCallback])`
The config object is passed as "context" parameter instead of as config object. One consequence is that the `coerce` function is not triggered.
Use Yargs `--config` option.
closes #3826
=> Fix parsing of config files with "_mocha" binary

test/reporters/base.spec.js, test/reporters/doc.spec.js, test/reporters/dot.spec.js, test/reporters/helpers.js, test/reporters/json-stream.spec.js, test/reporters/json.spec.js, test/reporters/landing.spec.js, test/reporters/list.spec.js, test/reporters/markdown.spec.js, test/reporters/min.spec.js, test/reporters/nyan.spec.js, test/reporters/progress.spec.js, test/reporters/spec.spec.js, test/reporters/tap.spec.js, test/reporters/xunit.spec.js
* Reworked tests to use `sinon` stubs
* Proper terminal-related stubs
* Added logic to (hopefully) rethrow errors if "stdout" stubbed
* Event constants
* Noise reduction
* Various mods for consistency
Various. Continue with homegrown solutions.
NA
**No noise in test output!**
**All tests now show _green_ checkmarks!** Well, locally -- cannot explain Travis...
* [before](https://travis-ci.org/mochajs/mocha/jobs/524512200#L2216-L2810)
* [now](https://travis-ci.org/mochajs/mocha/jobs/524494319#L2216-L2516)
None to knowledge...
semver-patch
=> Rework reporter tests

docs/index.md, example/config/.mocharc.yml, lib/cli/run-helpers.js, lib/cli/run-option-metadata.js, lib/cli/run.js, test/integration/fixtures/options/ignore/fail.fixture.js, test/integration/fixtures/options/ignore/nested/fail.fixture.js, test/integration/fixtures/options/ignore/nested/pass.fixture.js, test/integration/fixtures/options/ignore/pass.fixture.js, test/integration/options/ignore.spec.js
- Renamed all occurrences of `exclude` to `ignore`, as the latter is now the canonical name
- Updated docs to reflect change
=> rename "exclude" to "ignore" and create alias; closes #3871

lib/cli/options.js, lib/cli/run-helpers.js, lib/utils.js, test/integration/file-utils.spec.js, test/node-unit/cli/options.spec.js
Also fixes some issues in the options unit tests and adds coverage around `spec` handling.
This needs some manual testing, as I had to monkey with `watch` a bit.
cc @dedene
=> fix extension and spec handling; closes #3808

test/node-unit/cli/node-flags.spec.js
With newer versions Node flags can be written with "-" or "_":
f.e. `--abort-on-uncaught-exception`  <==> `--abort_on_uncaught_exception`
The same rule works for the two Node flags
- `--preserve-symlinks` (since v6.3.0) <==> `--preserve_symlinks`
- `--preserve-symlinks-main` (since v10.2.0) <==> `--preserve_symlinks_main`
Mocha treats both flags as special cases, since they haven't been part of `process.allowedNodeEnvironmentFlags` before Node v12.
Update unit test.
closes #3896
=> Node v12 and preserve-symlinks/-main flags

docs/index.md
Extends documentation describing option to define custom report name for xunit reporter
Based on #2628
=> Document option to define custom report name for xunit reporter

lib/cli/options.js, lib/cli/run-option-metadata.js, lib/cli/run.js, test/integration/duplicate-arguments.spec.js, test/integration/fixtures/options/slow-test.fixture.js, test/integration/fixtures/passing-async.fixture.js, test/integration/fixtures/passing-sync.fixture.js, test/integration/invalid-arguments.spec.js, test/integration/options/timeout.spec.js, test/node-unit/cli/options.spec.js
This fixes two problems:
1. ~~Duplicate values are no longer allowed on the command line, and an error will be thrown (e.g., `--timeout 0 --timeout 0`)~~
1. String values of `timeout` and `slow` (e.g., `1s`, `500ms`) are no longer evaluated to `NaN` (because their type was set to `number`).  It appears that a value of `NaN` would cause timeouts to be disabled.
Ref: #3817 
UPDATE: Duplicate arguments are now allowed; the last value is chosen.
=> fix timeout/slow string values and duplicate arguments

lib/utils.js, test/integration/file-utils.spec.js
* fix (my) regession: in some cases directories are returned, but only files are expected.
* fix existing bug: in some cases `glob.sync` returns directories, but only files are expected.
Directories can be excluded with options `{nodir: true}`.
BTW: Mocha's flag `--recursive` has no effect in our `glob.sync` implementation, but the same result can be achieved by using the glob pattern `**`, eg. "test/**/*"
* implement: a filename can be entered without extension. In this case all matches with option `extension[]` are returned. Currently only a constant extension `.js` is used.
#3834
=> Fix regression/bug in "lookupFiles()"

lib/cli/run-helpers.js, lib/cli/watch-run.js
As per @juergba’s suggestion in #3912 we extract the `watchRun` code into its separate module to prepare for #3912.
We move `watchRun` from `lib/cli/run-helpers` to `lib/cli/watch-run`. We also don’t use default values for the options anymore. The defaults are handled by `runMocha` and we want to avoid the default values getting out of sync. No other code has changed.
=> Extract `watchRun` into separate module

lib/mocha.js, test/unit/mocha.spec.js
Fixes https://github.com/mochajs/mocha/issues/3913
[The docs](https://mochajs.org/#-global-variable-name) say: 
`Updated in v6.0.0; the option is --global and --globals is now an alias.`
and [the inline docs](https://github.com/mochajs/mocha/blob/master/lib/mocha.js#L79) say:
` * @param {string[]} [options.global] - Variables expected in global scope.`
(Note the singular options.global)
but when creating a Mocha instance programmatically, only options.globals is accepted. Test repo here: https://github.com/pascalpp/mocha-globals-repro
n/a
Minor change to Mocha instance API to match documentation.
Users who expect `options.global` to work the same as the command-line option will not wonder why it doesn't.
Not sure. All existing tests pass with this change. I also added some new tests to …
=> modify Mocha constructor to accept options.global or options.globals

bin/mocha, lib/cli/cli.js
This is *likely* a quick win, but there may be unforeseen consequences.
If we don't detect any flags that must be sent to `node`, *don't spawn a child process*; instead, pass the unparsed arguments directly to `lib/cli/cli.js` for handling by `yargs`.
This means two things:
1. Depending on the use-case, there's no extra overhead.  This decreases the time spent running our `node`-specific tests:
```shell
$ nps test.node  143.66s user 33.77s system 100% cpu 2:56.31 total
$ nps test.node  115.04s user 26.46s system 97% cpu 2:25.53 total
```
1. Users leveraging debuggers which invoke `node --inspect` (VSCode does this, likely Webstorm too) can now execute `bin/mocha` instead of needing to specify `bin/_mocha`.  
It also means that we're a step closer to killing `bin/_mocha` entirely.  Instead …
=> do not fork if no node flags present

.travis.yml, appveyor.yml
Update CI configuration files to use current version of Node.
* AppVeyor's images still do not have pre-built Node-12 so changed script to use alternative install method.
* Changed Travis browser test to use Node-10 so we can use pre-built "canvas" package.
NA
Code tested against current Node release.
Code **not** being tested against current Node release.
Use of Node-10 for browser test can be revisited once we determine AG-B dependency updates for Node-12. See further explanation [here](https://github.com/mochajs/mocha/pull/3940#issuecomment-499559492), but as noted, the Node version is essentially meaningless for this test anyway.
semver-patch
=> Update CI config files to use Node-12.x

test/integration/fixtures/options/watch/dependency.fixture.js, test/integration/fixtures/options/watch/test-file-change.fixture.js, test/integration/fixtures/options/watch/test-with-dependency.fixture.js, test/integration/helpers.js, test/integration/options/watch.spec.js
We want to further extend the test coverage of the watch feature and prepare the code so that we can easily write tests for the features described in #3912.
To extend the test coverage for mocha in watch mode we add the following two tests:
* Check that test files are reloaded
* Check that watched dependencies are reloaded
To support this change we consolidate `runMochaJSONWatchAsync`, `runMochaJSONRawAsync`, and repeated code in tests into `runMochaWatch`. We introduce `invokeMochaAsync` in `test/integration/helpers` as an async alternative to `invokeMocha`.
We also eliminate the test for the cursor control character in the output. Its usefulness is dubious as it relies on an implementation detail and the other tests cover the intended behavior.
We are also more explicit which test …
=> More, improved integration tests for watching

.eslintrc.yml, lib/reporters/base.js, lib/reporters/doc.js, lib/reporters/dot.js, lib/reporters/landing.js, lib/reporters/list.js, lib/reporters/progress.js, lib/reporters/spec.js, lib/reporters/xunit.js, test/reporters/base.spec.js, test/reporters/xunit.spec.js
Small fix so that users can silence their own code (focused on just console.log's).
```js
// yuck.spec.js
it('should do, but it do not', function() {
// user wants to hide output generated by console.log calls in fn 'foo'
console.log = function() {};
foo();
});
```
We can still stub its underlying mechanism. 
Decided this small fix offers enough for now. Let me know if others feel strongly that its not.
Thinking more about how to unify the reporters (and `process.stdout.write`). 
#3604
=> Base reporter store ref to console.log

lib/cli/collect-files.js, lib/cli/run-helpers.js, lib/cli/run.js, lib/cli/watch-run.js
As part of the improvements to file watching (#3912) we want Mocha to pick up test files that are added while mocha is running in watch mode. This PR makes the necessary preparation to be able implement this behavior.
Our goal is to make the `watchRun` function responsible for collecting the tests files so that it can decide to collect test files again in the future.
Currently test files are collected with the `handleFiles` function in the `handler` in `lib/cli/run`. The collected files are then passed to `watchRun` and `singleRun`. We change this by having `watchRun` and `singleRun` collecting the test files.
We rename `handleFiles` to `collectFiles` and move it to a separate module. (This is necessary because `watchRun` and `singleRun` live in different modules.) The implementation …
=> Collect test files later

lib/cli/collect-files.js, test/integration/options/file.spec.js
Check if there are no files to load *after* we've added files from `--files`. This fixes #3941.
None
Fixes bug involving `--file`.
Fixes #3941.
None that I can think of.
#3941
This would be a bug fix (patch release).
=> Fix No Files error when file is passed via --files

lib/cli/run-helpers.js, lib/cli/watch-run.js, test/integration/options/watch.spec.js
* Fix #2027
* Remove unexplained and unneeded code
* Clearer separation of responsibilities and dependencies.
We remove code that called `mocha.grep(null)` on watch re-runs if the `--grep` option was not supplied. The code seems to serve no purpose and is the cause of #2027.
N.A.
Fixes #2027
We consolidate CLI option handling. The majority of CLI options are handled by the `Mocha` constructor. But this reponsibility is shared with `watchRun` which changes behavior based on a CLI option. With this change we reduce the reliance of `watchRun` on the CLI options, a point that was brought up in https://github.com/mochajs/mocha/pull/3953#discussion_r294672564. To finish this it would make sense to follow up with a PR that makes the use of the `ui` option unnecessary.
The code might actually …
=> Don't re-initialize grep option on watch re-run

lib/cli/options.js
When arguments are not following for CLI string flags, currently mocha show stacktrace.
Stacktrace is useless here because it is a valid validation. 
So, this PR show only error message for users like:
Handle these kinds of a message in yargs or other places.
The current behavior is unfriendly to users.
Users can easily realize what is a problem.
=> Hide stacktrace when cli args are missing

mocha.css
The `line-height` is already set in the `font` shorthand declaration.
N/A
N/A
N/A
N/A
N/A
=> fix: remove duplicate line-height property

lib/reporters/base.js
Thanks for reviewing this PR. I'm the maintainer of [mocha-parallel-tests](https://github.com/mocha-parallel/mocha-parallel-tests) - a wrapper on top of mocha which runs mocha tests in either parallel processes forked via `child_process` or in parallel threads created with `worker_threads`.
Recently I added an opportunity to run mocha tests via `worker_threads` if the API is available (IIRC this should be node@12). I got a couple of reports saying that [tty.getWindowSize is not a function](https://github.com/mocha-parallel/mocha-parallel-tests/issues/247). I spent a big amount of time investigating the issue and I discovered that the root cause is the `worker_threads` environment. While I understand this is probably not an issue with mocha because it never runs in `worker_threads`-created …
=> tty.getWindowSize is not a function inside a "worker_threads" worker

docs/css/prism.css, docs/css/style.css, docs/index.md
1. remove unnecessary white background color for an operator in a code block
2. make bold configuration file format like others
3. fix broken markdown syntax for [quotes](https://mochajs.org/#-debug-inspect-debug-brk-inspect-brk-debug-inspect)
4. add style inline code block like GitHub
N/A
Users can easy to read the document
=> fix styles on mochajs.org

docs/index.md
The fact that code inside of a skipped suite is executed, is potentially
counter-intuitive.  By using alternative phrasing, we make it clear how
mocha handles code in skipped suites.
Closes #3932
=> Clarify effect of .skip()

lib/runner.js
Remove private function `extraGlobals()` since the support of Node v0.9.11 has been dropped years ago.
=> remove extraGlobals()

.travis.yml
In addition to #3885 which still runs `Smoke` with Node v6.
=> Travis: don't run Smoke with Node v6

package-lock.json, package.json
Fixes Prototype Pollution vulnerability of `lodash` via `yargs-unparser`.
closes #3965
=> Update yargs-unparser to v1.6.0

lib/runner.js, test/integration/fixtures/pending/skip-async-spec.fixture.js, test/integration/fixtures/pending/skip-sync-spec.fixture.js, test/integration/pending.spec.js
The current hook pattern is incorrect. When a test is skipped at runtime, all `beforeEach` hooks have already been executed, nevertheless all `afterEach` hooks are ignored completely.
As a general rule: when a `beforeEach` hook runs, the corresponding `afterEach` should run also for correct cleanup. This same pattern has already been implemented with failing hooks, `this.skip()` in `beforeEach`  and also while using the `--bail` option.
The correct hook pattern should be:
- run all `beforeEach` hooks ("A", "B")
- abort test execution and set test to `pending`
- run all corresponding `afterEach` hooks ("Y", "Z")
By contrast: tests skipped at compile-time with `it.skip()` do not run neither `beforeEach` nor `afterEach` hooks.
```js
describe('outer', function() {
beforeEach(function() { …
```
=> Fix hook pattern of this.skip() in it() tests

bin/mocha
The package `esm` is not loaded correctly when `--require esm` is passed via **configuration file**.
However the result is as expected when passing it via **CLI** .
This is a regression.
We handle `--require esm` as Node option: `node --require=esm mocha`:
- we add `esm` to the Node option `require`
- we remove `esm` from the Mocha option `require`
This way Node is extended with `esm` before Mocha is launched in a child-process.
closes #3975
=> Package 'esm': spawn child-process for correct loading

docs/index.md, example/config/.mocharc.js, example/config/.mocharc.json, example/config/.mocharc.jsonc, example/config/.mocharc.yml, lib/cli/options.js, lib/cli/run.js, test/integration/options/opts.spec.js
Since v6.0.0 configuration via `mocha.opts` is considered "legacy".
- a deprecation warning is printed when `loadMochaOpts()` is called, the file `mocha.opts` exists and is loaded successfully.
- in the help text (`mocha -h`) `--opts` is labeled as deprecated
- examples of configuration files: `opts` is set to `false`
- docu update
#3910 partially
=> Soft deprecate configuration via "mocha.opts"

.github/CODE_OF_CONDUCT.md
First task for https://github.com/mochajs/admin/issues/7. Just a blanket copy-paste from [here](https://github.com/openjs-foundation/cross-project-council/blob/master/CODE_OF_CONDUCT.md).
Let me know if you think there is a nicer format or way to do this.
=> Adopt the OpenJSF Code of Conduct

docs/index.md, lib/mocha.js, lib/runner.js, test/unit/mocha.spec.js, test/unit/runner.spec.js
When Mocha is launched via CLI a whole bunch of options is dumped into the `mocha` instance, like canonical / canonical camel-cased / alias / alias camel-cased versions of option names. This is prone to errors, but not part of this PR ==> see #4011.
When the user manually calls the `Mocha` constructor, there are some bugs to be fixed.
Furthermore we remove two deprecated options.
- remove deprecated `enableTimeouts` option
- remove deprecated `useColors` option
- remove `ignoreLeaks` option: this option does not exist and is redundant to `checkLeaks`
- fix `inlineDiffs` option: `useInlineDiffs` does not exist
- fix `diff` option: `hideDiff` does not exist
- fix `reporterOption` option: its alias `reporterOptions` was processed instead
- fix `fullTrace`: `fullStackTrace` does not exist
- …
=> Mocha constructor: some fixes and cleanup

lib/runner.js, test/integration/fixtures/regression/issue-1327.fixture.js, test/integration/fixtures/uncaught-fatal.fixture.js, test/integration/regression.spec.js, test/integration/uncaught.spec.js, test/unit/runner.spec.js
Per default Mocha tries to recover from `uncaughtException` and to map the exception to the correct test case. It's not possible to recover gracefully if a Runnable has already passed successfully and then fails asynchronously.
Firing an `EVENT_RUN_END` out of a suite **other than the root suite** is wrong and will result in the emission of double `EVENT_RUN_END` events. The first event will not abort the runner and a second event will be fired by the root suite. We already had a similar issue, see #3617.
To prevent double test epilogues the reporters have been "fixed" in the past by using `runner.once(EVENT_RUN_END, ...)`.
Following tests were ineffective:
- test\integration\fixtures\uncaught-fatal.fixture.js:
```
√ should bail if a successful test asynchronously fails
1) should bail if …
```
=> uncaughtException: fix double EVENT_RUN_END events

lib/runnable.js, lib/runner.js, test/integration/fixtures/options/allow-uncaught/this-skip-it.fixture.js, test/integration/options/allowUncaught.spec.js, test/unit/runnable.spec.js
```js
describe('test suite', () => {
it('test1', function () { });
it('test2', function () {
this.skip();
});
it('test3', function () { });
it('test4', function () {
this.skip();
});
});
```
`mocha --allow-uncaught test.js` silently aborts execution after the first `this.skip()`:
```
test suite
√ test1
```
Our docu states:
> [...] It's also important to note that calling `this.skip()` will effectively abort the test.
We achieve this abortion of the test/hook execution by throwing a `Pending` exception. In async scenarios this results in an intended `uncaughtException` which has to be swallowed somehow. Obviously `--allow-uncaught` does not distinguish correctly between "bad" `uncaughtException` (user code) and "good" `uncaughtException` (`this.skip()`).
- independently of …
=> uncaughtException: fix "--allow-uncaught" with "this.skip()"

lib/reporters/html.js
Fixed the iteration of the HTMLCollection object in the unhide function of the html reporter. Since the length of the HTMLCollection changes as the elements' class names get updated (as HTMLCollection works 'live'), it cannot be updated using an index-based for loop.
Changed the index-based for loop iteration to a while loop, updating the first element while the length of the HTMLCollection is larger than 0.
It a bug (although minor) that makes filtering by passes/failures doesn't work properly as expected.
Filtering by passes / filters in html reporter works properly even after unhiding objects.
None
Closes #4048
=> Make unhide function work as expected in html reporter

lib/cli/node-flags.js, test/node-unit/cli/node-flags.spec.js
this adds a special case when `unparseNodeArgs()` detects `require`; it removes the `=`, which is apparently required for everything else but prohibited in Node.js v8.
=> special-case parsing of "require" in unparseNodeArgs(); closes #4035

lib/reporters/base.js, test/reporters/base.spec.js
```js
describe('suite', function() {
it('should report the first of multiple exceptions', function(done) {
process.nextTick(() => {
console.log('first');
throw new Error('first');
});
process.nextTick(() => {
console.log('second');
done(new Error('second'));
});
});
});
```
The first error is not reported at all, instead the output shows two copies of the second error.
```
suite
first
1) should report the first of multiple exceptions
second
2) should report the first of multiple exceptions
0 passing (10ms)
2 failing
1) suite
should report the first of multiple exceptions:
Error: second
[...]
2) suite
should report the first of multiple exceptions:
Error: second
[...]
```
- `test.err`: currently is storing just one error per test, in case of multiple errors it's the last one. I haven't …
=> uncaughtException: report more than one exception per test

docs/index.md, lib/mocha.js
Update documentation to include usage instructions on how to specify the reporter for browser tests.
This was absent, despite hinting that it could be done.  It took quite awhile of digging through source to figure out how this could be correctly.  This information should be available.
Thought about not including the list of possible strings, but decided I should because otherwise people will have to guess on that front as well.
Because it's documentation.
Save people time and frustration.
None.
Issue #1592
=> Added documentation on how to specify the reporter for browser mocha

docs/_includes/sponsors.md, docs/css/style.css
If sponsors use white-tone logo, users can't see the sponsor's logo.
So, I added grey background to sponsors.(And align them center)
I knew it is not pretty design, but grey is best for both light-tone and dark-tone logos. I thought making sponsor logos readable is more important than pretty design.
Another color or design?
close #3736
=> fix sponsors background color for readability

lib/mocha.js, test/unit/mocha.spec.js
The browser setup can result in an error when the option and its corresponding function don't match in their name, eg. `--diff`<==> `hideDiff()`.
see [comment](https://github.com/mochajs/mocha/pull/4026#issuecomment-541265091)
Mocha options are used in different contexts:
- via CLI: options can be set with canonical / alias / camel-cased canonical / camel-cased alias names.
The parser autocompletes the names and the whole bunch of options is dumped into the `mocha` instance.
eg. `--timeout 200` results in: `{timeout: 200, t: 200 timeouts: 200}`
- using Mocha programmatically: Mocha constructor accepts and processes only canonical or their camel-cased option names,
eg. `{timeout: 200, checkLeaks: true}`
- browser: setup() calls public function where option name matches function name.
```js …
```
=> Mocha constructor: improve browser setup

lib/runner.js, test/integration/fixtures/options/allow-uncaught/propagate.fixture.js, test/integration/fixtures/uncaught-pending.fixture.js, test/integration/options/allowUncaught.spec.js, test/integration/uncaught.spec.js, test/unit/runner.spec.js
```js
describe('test', () => {
it('test1', () => {
setTimeout(() => {
throw new Error('Uncaught');
}, 3);
});
it('test2', function () { this.skip(); });
it('test3', function () { this.skip(); });
it('test4', function () { this.skip(); });
});
```
**output with exitCode: 0**
```
test suite
√ test1
- test2
- test3
- test4
1 passing (34ms)
3 pending
```
`Runner#uncaught`:
- per default Mocha tries to map `uncaughtException`s to the correct test case, to recover and keep the `runner` working. This is done on a "best effort" basis. Currently the user has no possibility to escape this recovery effort, not even with the `--allow-uncaught` option. 
Now `--allow-uncaught` throws an error and exit Mocha's process. 
- current test is pending: when an `uncaughtException` bubbles up, we …
=> uncaughtException: fix when current test is pending

.github/FUNDING.yml
With this change, GH will show a Sponsor button at the top.  [Here's how GitHub described the feature:](https://github.blog/2019-05-23-announcing-github-sponsors-a-new-way-to-contribute-to-open-source/)
> Open source projects can also express their funding models directly from their repositories. When .github/FUNDING.yml is added to a project’s master branch, a new “Sponsor” button will appear at the top of the repository. Clicking the button opens a natively rendered view of the funding models listed in that file.
=> Add GH Funding Metadata

docs/index.md
I was trying to build docs, I found the alert messages which are `Language does not exist sh` and `Language does not exist text`. When I use `npm start docs`, the alert messages come because of `eleventy` like below :
```shell
Hyunsangs-MacBookAir:mocha temp$ npm start docs
> mocha@6.2.0 start /Users/temp/Downloads/exercise/mocha
> nps "docs"
nps is executing `docs` : nps docs.prebuild && nps docs.api && eleventy && nps docs.linkcheck && nps docs.postbuild
nps is executing `docs.prebuild` : rimraf docs/_dist docs/_site && nps docs.preprocess
nps is executing `docs.preprocess` : md-magic --config ./scripts/markdown-magic.config.js --path docs/index.md
Starting markdown-magic docs/index.md
✔ docs/index.md Updated
Transforms run
⁕ usage:executable=bin/mocha
⁕ toc:maxdepth=2&bullets=-
⁕ …
```
=> Change sh to bash for code block in docs/index.md

docs/index.md
Please see commit message. Thanks!
=> docs: clarify invalid usage of done()

docs/README.md
To try to contribute to Mocha docs, I proceeded with the installation  as described in [**README.md** of docs](https://github.com/mochajs/mocha/blob/master/docs/README.md) directory. However, when I tried to use `npm start docs` after installing, the following error occurred:
```
nps is executing `docs.postbuild` : buildProduction docs/_site/index.html --outroot docs/_dist --canonicalroot https://mochajs.org/ --optimizeimages --svgo --inlinehtmlimage 9400 --inlinehtmlscript 0 --asyncscripts && cp docs/_headers docs/_dist/_headers && node scripts/netlify-headers.js >> docs/_dist/_headers
Guessing --root from input files: file:///Users/temp/Downloads/exercise2/mocha/docs/_site/
✔ 0.006 secs: logEvents
✔ 1.320 secs: loadAssets
✔ 0.008 secs: bundleWebpack
✔ 0.063 secs: populate
✔ 0.015 secs: …
```
=> Add a description for installing GraphicsMagick or ImageMagick in docs/README.md

test/integration/fixtures/uncaught.fixture.js
One of our CI [tests](https://github.com/mochajs/mocha/blob/master/test/integration/fixtures/uncaught.fixture.js) is unstable and fails occasionally.
- it should fail while the runner is still active which resulted in an `exitCode` of 2 (number of failing tests).
- sometimes it fails too late, after the EVENT_RUN_END event when all tests have finished. Then it is caught by the `uncaughtException` handler and exits with `exitCode` of 7.
Since 2 (expected) !== 7 (actual) ==> the test fails.
We use `process.nextTick()` instead of `setTimeout()`.
related #4103
=> Fix unstable CI uncaughtException test

.travis.yml, appveyor.yml
=> Add Node v13 to CI test matrix

lib/cli/watch-run.js, package-lock.json, package.json
- update to v3.3.0
- `npm audit --fix`
- simplify our code due to changelog v3.1.0:
> Dotfiles are no longer filtered out by default. Use ignored option if needed.
=> Update Chokidar to v3.3.0

.eslintrc.yml, karma.conf.js, package-scripts.js, package.json
Some modules of our code base are not used by Mocha's browser environment.
See also `env: browser: no` in `eslintrc.yml`
Currently these modules are eslint-parsed by ES6 rules. 
- we update the eslint parsingOption from ES6 to ES2017 in order to make available `async`/`await`.
The default remains ES5 for IE11 reasons.
As soon as we drop Node v8 support (end of life: 2019-12-31) we should update to ES2018.
Browserify: regarding ignored files
We have three different configuration settings defining files to be ignored. I guess we have some redundant information here, but I'm unsure about that. To stay on the safe side we update all of them:
- `browser` field in package.json
- `ignore()` in `karma.config.js`
- the browserify script with its `--ignore` option
It's unclear to me why we ignore …
=> Update eslint parsing from ES6 to ES2017

PROJECT_CHARTER.md
This is a draft charter.  It's important all maintainers give their OK on this.  In addition, I think it needs to be ratified by the CPC (which I'll deal with).  But before that happens, we need to make sure it's ok.
Open to any suggestions and can hopefully answer any questions we have.  See #4087 for issue.
cc @jorydotcom
I've added the four other active maintainers to the list of reviewers, but anyone from @mocha/core (or anyone from the community, even) is welcome to offer feedback.
=> initial draft of project charter; closes #4087

bin/mocha, test/integration/fixtures/options/slow-test.fixture.js, test/integration/options/timeout.spec.js
Mocha disables timeouts while debugging in order to avoid timeout errors.
This is true:
- when the Node debugging flags are set via Mocha
- with `bin/mocha` executable (not `bin/_mocha`)
In some cases the disabling of the timeouts did not work due to the option's order.
- correct: `--timeout 2000 --inspect-brk`
- fails: `--inspect-brk --timeout 2000`
closes #4110
=> Fix timeout handling with `--inspect-brk`/`--inspect`

docs/index.md
Broken links modify to enable in the documentation.
Typescript and Babel example is inside mocha-examples/packages.
Link enables in the documentation
=> Broken links in docs 

package-lock.json, package.json
node-environment-flags 1.0.5 and lower do not contain a LICENSE file which can make compliance difficult. This pull request updates the patch release of node-environment-flags to incorporate https://github.com/boneskull/node-environment-flags/pull/5.
Removing the dependency on node-environment-flags.
To ensure the entire dependency chain of Mocha has dependencies contains valid copyright and licenses.
I don't think there are any.
> * Mocha follows semantic versioning: http://semver.org
> 
> * Is this a breaking change (major release)?
> * Is it an enhancement (minor release)?
> * Is it a bug fix, or does it not impact production code (patch release)?
It's a bug fix, fixing licensing.
=> Update node-environment-flags to 1.0.6

lib/reporters/base.js, lib/reporters/xunit.js, test/reporters/xunit.spec.js
This bugfix addresses a crash in the XUnit reporter, which produced no output because the assertion library used in the ticket provided numerical diff values rather than string values, causing an error during diff generation. To safeguard against unexpected crashes such as these, the same input-checks that the Base reporter uses have been implemented in the XUnit reporter, and exceptions during XUnit diff generation are returned by the reporter.
Fixes #4022.
=> XUnit reporter should handle exceptions during diff generation

lib/runner.js, test/integration/fixtures/pending/skip-async-beforeEach.fixture.js, test/integration/fixtures/pending/skip-sync-beforeEach-cond.fixture.js, test/integration/fixtures/pending/skip-sync-beforeEach.fixture.js, test/integration/pending.spec.js
#3745 is required for this PR.
The current hook pattern is incorrect. Skipping a test within a `beforeEach` hook executes all inner `beforeEach` hooks, but skips `afterEach` hooks completely.
Some of the `afterEach`  hooks should run to ensure a correct cleanup. This same pattern has already been implemented with failing hooks and also while using the `--bail` option.
The correct hook pattern should be:
- `beforeEach` runs for each test individually and determines at runtime wether to skip or not.
(The failing hook pattern is different: the first hook failure skips all linked tests.)
- since `this.skip()` aborts hook execution, subsequent inner `beforeEach` should be skipped ("B").
- skipped `beforeEach` => skip corresponding `afterEach` hooks as well ("Y").
- `afterEach` hooks of the …
=> Fix hook pattern of this.skip() in beforeEach hooks

docs/index.md, lib/runner.js, test/integration/fixtures/pending/skip-sync-after.fixture.js, test/integration/pending.spec.js
- remove deprecation message
- fail `after` hook with `ERR_MOCHA_UNSUPPORTED` error
=> Forbid this.skip() within afterAll hooks

docs/index.md
- Reporter part of Mocha docs was so unkind about enable reporter name.
- there are two enable names but current docs makes users confused.
- Add **enable names** to docs clearly
- Unite reporter name to call a reporter type
*before*
The "progress" reporter implements a simple progress-bar:
*after*
**Enable Names:** `Progress`, `progress`
The Progress reporter implements a simple progress-bar:
fix #4054 
fix #4134
=> Add reporter names enable and Unite names into one

lib/runner.js, test/integration/fixtures/uncaught/listeners.fixture.js, test/integration/uncaught.spec.js
```js
const mocha = require("mocha");
for (let i = 0; i < 15; i++) {
const r = new mocha.Runner(new mocha.Suite(""+i, undefined));
r.run();
}
```
When using Mocha programmatically with multiple runners, a `MaxListenersExceededWarning` is emitted by Node. For every runner instance an `uncaughtException` handler is registered, but never removed.
This is a regression.
Remove eventual `uncaughtException` handler before starting a new runner instance.
closes #4144
=> Fix leaking global 'uncaughtException' handler

LICENSE, README.md, docs/_includes/default.html, docs/css/style.css
- made footer responsive
- made matomo & openjsf logos responsive
- remove `target="_blank"` since people can decide if they want to open a tab
Ref: #4145
=> update copyright & trademark notices per OJSF; closes #4145

lib/runnable.js, test/unit/runnable.spec.js
Given a test such as:
```js
it('foobars', 4);
```
mocha used to throw the following error: `fn.call is not a function`.
After applying this patch, it will throw a more descriptive error message:
`A runnable must be passed a function as its second argument.`
(Thanks to [ssube](https://github.com/ssube) for helping with the error wording.)
This deals with an error builtin to mocha.
While the previous error is technically true, I have personally spent some minutes of my life chasing what looked like a bug in the test itself, and not in the call to `it`. A …
=> Throw a descriptive error when a non-function is given to a runnable

lib/mocha.js, test/unit/mocha.spec.js
In https://github.com/mochajs/mocha/pull/4004 there was a change to use the documented `reporterOption` in favour of the setting that had always been used in practice called `reporterOptions`. This broke a lot of configurations that used the `reporterOptions`, which was the only way it every worked AFAIK. This is also clear in that all the built-in reporters use this name.
This changes the documentation to specify `reporterOptions` instead and ensure that any one that has switched to `reporterOption` after upgrade, still works.
`reporterOption` could have been chosen as the new preferred way, but objects with options are generally referred to in their plural form in JS. I think the root cause of the confusion comes from the command line option `reporter-option`. I think it makes sense …
=> Fix backwards compatibility break for `reporterOptions`

lib/runnable.js, lib/runner.js, test/integration/fixtures/uncaught/recover.fixture.js, test/integration/hook-err.spec.js, test/integration/uncaught.spec.js, test/unit/runner.spec.js
```js
describe('uncaught', function() {
it('throw delayed error', (done) => {
setTimeout(() => {
throw new Error('Whoops!');
}, 10)
setTimeout(done, 10);
});
it('should wait 15ms', (done) => {      
setTimeout(done, 15);
});
it('test 3', () => { });
afterEach(function() {
console.log('inside afterEach:', this.currentTest.title);
});
});
```
This bug produces very variable results as throwing `TypeError` and failing empty tests. In above example the output is complete nonsense.
```
uncaught
1) throw delayed error                  // first test fails
√ throw delayed error                   // then same test passes
inside afterEach: throw delayed error      // same hook twice 
inside afterEach: throw delayed error
√ test 3                                // second test is missing
√ test 3 …
```
=> uncaughtException: fix recovery when current test is still running

lib/runner.js, test/integration/fixtures/pending/programmatic.fixture.js, test/integration/helpers.js, test/integration/pending.spec.js
Update for #3741.
When a `test` is conditionally set to `pending` by programmatic means (without using `this.skip()`), `errSuite` is `undefined` and the `runner` crashes.
closes #4160
=> Fix: Mocha aborts when 'test' is set to 'pending' programmatically  

browser-entry.js, docs/index.md, lib/runner.js, test/unit/runner.spec.js
- _mocha/browser-entry.js_: Node's `process.on('uncaughtException', fn)` handler is moved to `global.onerror(fn)` in Browser.
```js
Runner.prototype.uncaught = function(err) {
if (err instanceof Pending) {
return;
}
// browser does not exit when throwing in global.onerror()
if (this.allowUncaught && !process.browser) {
throw err;
}
[...]
```
- the result is distinct when an Error is thrown in the handler and `allowUncaught: true`
- **Node**: the process exits and no tests or async tasks are executed anymore.
- **Browser**: the JS script aborts the handler only, but the script keeps running. There seems no way to kill the entire script with its remaining tests and pending async tasks.
==> **test results are incorrect**, since the entire recovery logic of the handler is skipped.
- Node: …
=> Browser: fix 'allowUncaught' handling 

lib/runner.js, lib/test.js, test/integration/fixtures/retries/early-pass.fixture.js, test/integration/retries.spec.js, test/unit/test.spec.js
To re-run a failing test Mocha:
- clones the test for each attempt
- passes the test object of the final attempt to the reporter by emitting an `EVENT_TEST_END`
- DOES NOT: update the original `runner`'s test array `suite.tests` with the latest test object
The result of Mocha's core reporters is correct, since they hook into events and use the latest test object. But third party reporters as _Mochawesome_ relying on `suite.tests` may show incorrect test results.
We update `runner`'s `suite.tests` after the final attempt when the `EVENT_TEST_END` is emitted and replace the first failing test by the test object of the last attempt.
closes #2188
=> Fix: programmatic API cannot access retried test objects

docs/_includes/default.html, docs/css/style.css
To use Netlify's Open Source plan, I added [Netlify badge](https://www.netlify.com/press/#badges) on the footer as [their policy](https://www.netlify.com/legal/open-source-policy/). There are 4 rules but we already met 3 of them.
This PR address 3rd rule.
1. [x] Open Source Initiative approved license
1. [x] Code of Conduct
1. [ ] feature a link to our service
1. [x] must not be a commercial project
Netlify badge can be next to the OpenJS foundation logo, but I think the footer is better since Netlify badge is much smaller.
We can use Netlify open source plan.
=> docs: show Netlify badge on footer

lib/runner.js, test/unit/mocha.spec.js
`mocha.run()` returns a `runner` instance. Since the `EVENT_RUN_BEGIN` (`start`) event is emitted synchronously, it's impossible to register an `EVENT_RUN_BEGIN` listener in time. The event is emitted, but never catched.
When no tests are provided - eg. by a too restrictive `grep` expression - then neither `EVENT_RUN_BEGIN` nor `EVENT_RUN_END` (`end`) events can be listened to.
```js
var mocha = new Mocha();
mocha.addFile("../eventStart.js");
mocha.run()
.on(EVENT_RUN_BEGIN, () => console.log('start'))    // never runs
.on(EVENT_RUN_END, () => console.log('end'));       // never runs when no tests are provided
```
We delay the start of the root Suite by `Runner.immediately`. The order of the event emissions remains unchanged.
#3395 (backed out)
#3331 
#3065
closes #2753
=> Fix: listen to 'start' and 'end' events when using Mocha programmatically

.eslintrc.yml, .github/CONTRIBUTING.md, .travis.yml, appveyor.yml, docs/README.md, docs/index.md, package.json
I removed support to v8 in CI and documentation as explained in #4163
N/A 
Bump minimum Nodejs version
No need to worry about support for Node v8
N/A
Close #4163
=> Drop node.js v8 support

lib/mocha.js, test/jsapi/index.js, test/unit/mocha.spec.js
- nodeVersion : v10.15.1
- os : MacOS 
I removed deprecated Method and tested it. removing something is difficult like love but it is neccessery
- Mocha.prototype.ignoreLeaks 
- Mocha.prototype.useColors
- Mocha.prototype.useInlineDiffs
- Mocha.prototype.hideDiff
Why it is be removed? 
because `Mocha.prototype.checkLeaks` is Take on a role and do better
After I removed, It is worked
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Mocha Tests</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="stylesheet" href="https://unpkg.com/mocha/mocha.css" />
</head>
<body>
<div id="mocha"></div>
<script src="https://unpkg.com/chai/chai.js"></script>
<script src="./mocha.js"></script> 
<script class="mocha-init"> …
```
=> Remove deprecated methods

.github/CONTRIBUTING.md, docs/README.md, docs/index.md, karma.conf.js, lib/cli/init.js, lib/reporters/xunit.js, package-lock.json, package.json, test/integration/file-utils.spec.js, test/reporters/xunit.spec.js
- Replace `mkdirp` with `fs.mkdirSync` using `{recursive: true}`
- Drop the dependency `mkdirp` from Mocha
There is also a way to update to the latest `mkdirp` version, but Node.js version 10.12.0 has already added a native support for `mkdirSync` to create a directory recursively with `{recursive: true}` option as the following:
```js
fs.mkdirSync(pathname, { recursive: true });
```
So, there is no longer necessary to depend on third-party packages. `fs` module is enough to us.
`mkdirp` depends on an old version of `minimist`, and it has a prototype pollution vulnerability.
Can create a new directory and any necessary subdirectories at the directory **without mkdirp**.
Can't think of any.
I think it have to be released with **`semver-major`(maybe v8.0.0)**, because the `{recursive: …
=> Drop mkdirp and replace it with fs.mkdirSync

lib/runnable.js, lib/runner.js, test/integration/fixtures/pending/skip-async-before-hooks.fixture.js, test/integration/fixtures/pending/skip-sync-before-hooks.fixture.js, test/integration/fixtures/pending/skip-sync-before-inner.fixture.js, test/integration/pending.spec.js
```js
describe('outer suite', function() {
before(function() {
console.log('** before-1');
this.skip();
});
before(function() { console.log('** before-2'); });  // second before hook should not run
it('outer pending test', function() { });
describe('inner suite', function() {
before(function(done) {              // inner async before hook should not run
console.log('**** before: done');
done();
});
it('inner pending test', function() { });
after(function(done) {               // inner async after hook should not run
console.log('**** after: done');
done();
});    
});
after(function() { console.log('** after'); });
});
```
```
outer suite
** before-1
** before-2                  // second before hook should not run
- outer pending test
inner suite
**** before: done            // inner …
```
=> Improve hook pattern of 'this.skip()' in beforeAll hooks

lib/runnable.js, lib/runner.js, lib/utils.js, test/unit/runner.spec.js, test/unit/utils.spec.js
- `Runnable#inspect`: this function is never referenced
- `utils.ngettext`: pointless twist-simple-to-complex function, used once
=> Remove Runnable#inspect and utils.ngettext

lib/interfaces/common.js, lib/test.js, test/unit/test.spec.js
#3689  recommended to enhance encapsulation by introducing an instance method appendOnlyTest to the Suite class. This was already done and merged in #3707 .
Going a step further, the Test class should expose an instance method markOnly() which would do the call on its parent so this is not accessed directly by an other class.
The Test class handles calls on his own data resulting in a higher degree of abstraction and encapsulation. 
#3689
=> Issue 3689: Refactoring improving encapsulation

.eleventy.js, .markdownlint.json, docs/css/style.css, package-lock.json, package.json, scripts/markdown-magic.config.js
grouped these together:
- Site can now use emoji :party:
- Using the `.single-column` class will render a `ul` element as a "normal" list
- Suppress the warning about `text` being an unknown language coming out of 11ty/Prism/markdown-it
Ref: #4198
=> enable emoji on website; enable normal ul elements

lib/reporters/landing.js, test/integration/helpers.js, test/integration/options/exit.spec.js
- `landing` reporter befouls the terminal up if `SIGINT` is issued
- `--exit` test used an incorrect description, and also did not reliably handle `SIGINT` when running
Ref: #4198
=> fixes some signal handling

.travis.yml, appveyor.yml
=> CI: add job names, add Node.js v14 to matrix

bin/mocha, lib/cli/config.js, lib/cli/options.js, lib/cli/run-helpers.js, lib/runner.js
- make sure that template strings aren't used in debug statements, since they are eager
Ref: #4198
=> better debug output

lib/runner.js
> If an exception/assert error occurs in a hook, karma-mocha stops immediately due to an unhandled exception.
[...]
karma-mocha is passing a hook object as the param with a 'test end' event.
[...]
The hook doesn't have a retriedTest method, so it throws "Uncaught TypeError: test.retriedTest is not a function"
Emitting a `test end` event for a `hook` is wrong. We add a type check before calling `retriedTest()` in order to prevent an uncaught exception.
closes #4250 
closes #4227
=> Fix: karma-mocha hangs when there's a exception in a hook

test/unit/runner.spec.js
straightforward check for #4251.  we really shouldn't need to do this; I hope someone created an issue in karma-mocha.
=> add test case for #4251

package-scripts.js
We sometimes get HTTP 429 responses from unpkg.com when checking the links to mocha and chai assets we use in a cope/pasteable code reference for how to run mocha in a browser.
These checks should still run, but if we know that we might get HTTP 429 because unpkg is temporarily overloaded we should not fail the build.
Example of such a failure: https://app.netlify.com/sites/mocha/deploys/5ea2e0db7751000007185cf1
Adding a `--todo` match on the error we get in hyperlink allows that particular response to fail without failing the build
=> Mark HTTP 429 responses as allowed failures in hyperlink check

lib/cli/run-helpers.js, lib/errors.js, test/node-unit/cli/fixtures/bad-module.fixture.js, test/node-unit/cli/run-helpers.spec.js
- add `createInvalidPluginError` for reporters, UIs, and future plugins
- ensures the original error is output if the module exists, but it throws (see `test/node-unit/cli/fixtures/bad-module.fixture.js`)
- remove unneeded `process.cwd()` from call to `path.resolve()`
Ref: #4198
=> refactor validatePlugins to throw coded errors

docs/index.md
Fixes configuration files mistakenly being referred to as `mocharc.js` and `mocharc.cjs` instead of `.mocharc.js` and `.mocharc.cjs`.
=> Fix missing dot in name of configuration file

package.json
Did you know that if you click on the "testing" icon on npmjs.com, Mocha is completely absent?
It wants the keyword `testing`, which we do not have.  So I added that and a bunch more.  Since all of
the other major test frameworks seem to use keywords of others, might as well join that arms race.
=> adds a bunch of keywords

.mocharc.yml, example/config/.mocharc.yml, lib/mocha.js, test/integration/diffs.spec.js, test/integration/fixtures/uncaught/listeners.fixture.js, test/integration/options/watch.spec.js, test/node-unit/cli/config.spec.js, test/node-unit/cli/options.spec.js, test/node-unit/mocha.spec.js, test/unit/hook-timeout.spec.js, test/unit/runner.spec.js, test/unit/throw.spec.js, test/unit/timeout.spec.js
- increase default timeout for wiggle room
- specify `watch-ignore` in case we run our own tests in watch mode
- reformat `.mocharc.yml`
- `integration/fixtures/uncaught/listeners.fixture.js`: reduce number of listeners created to avoid max listener warning
- `integration/fixtures/options/watch.spec.js`: do not use context object; be more specific about spawn options
- `integration/fixtures/diffs.spec.js`: do not pass `-C`; the helper already does this
- `node-unit/mocha.spec.js`: do not actually create files; it's a unit test after all.
- `node-unit/cli/config.spec.js`: rewiremock fixes
- `node-unit/cli/options.spec.js`: rewiremock fixes; increase timeout
- `unit/hook-timeout.spec.js`: do not override default (configured) timeout
- `unit/runner.spec.js`: leverage …
=> assorted test fixes & refactors

test/assertions.js, test/integration/helpers.js, test/integration/options/watch.spec.js
- enables `RawResult` (the result of `invokeMocha()` or `invokeMochaAsync()`) to check the exit code via `to have code` assertion
- add passed/failing/pending assertions for `RawRunResult` (the result of `runMocha()` or `runMochaAsync()`)
- expose `getSummary()`, which can be used with a `RawResult` (when not failing)
- reorganize the module a bit
- create `runMochaAsync()` and `runMochaJSONAsync()` which are like `runMocha()` and `runMochaJSON()` except return `Promise`s
- better trapping of JSON parse errors
- better default handling of `STDERR` output in subprocesses (print it instead of suppress it!)
- do not let the `DEBUG` env variable reach subprocesses _unless it was explicitly supplied_
- add an easily copy-paste-able `command` prop to summary
- add some missing docstrings
Ref: …
=> test helper improvements

lib/cli/cli.js, lib/mocha.js
`module.paths` was not defined when Mocha was run in an serverless environment. Probably due to the absence of `node_modules` folder. I had bundled the test using a bundler.
I added a check to make sure it doesn't throw an error.
Not sure if there are any other alternatives but open to suggestions.
I don't think userland should mock `module.paths`.
It would not throw an error during the execution of tests in a serverless environment.
I don't see any.
Fixes #2505 
This should be a bug fix
=> fix: check if module.paths really exists

.nycrc, docs/index.md, lib/context.js, lib/mocha.js, lib/runnable.js, lib/suite.js, lib/test.js, test/integration/fixtures/timeout-override.fixture.js, test/integration/timeout.spec.js, test/unit/context.spec.js, test/unit/mocha.spec.js, test/unit/runnable.spec.js, test/unit/test.spec.js, test/unit/timeout.spec.js
Removed `enableTimeout` stuff. Use the latest `timeout` value to determine if enabled/disabled + its value. (disabled is value of 0, else is enabled).
Also fixes issue of tests not timing out when timeout is re-enabled. See associating issue https://github.com/mochajs/mocha/issues/4254.
Fixes https://github.com/mochajs/mocha/issues/4254
Could remove `enableTimeouts` from public-facing and use it internally, however it is easiest to have a **single source of truth** (the value) and mirror what the user uses. Having 2 different states which are very similar gets confusing.
Simplify the codebase. 
There are use-cases where it is useful to be able to re-enable and make use of a previously disabled timeout. Also seems pretty important that the feature behaves as a user would expect.
You can no …
=> Remove enableTimeout api + allow overriding a disabled timeout

lib/runner.js, test/unit/hook.spec.js
`Function.prototype.name` is not available in IE11, and will cause the browser tests to fail.
Ideally, we could catch this with ESLint, but here's hoping we don't need to do that.
cc @nicojs
=> fix test/unit/hook.spec.js

.eslintrc.yml, lib/cli/cli.js, lib/cli/config.js, lib/mocha.js, lib/utils.js, package-lock.json, package.json, test/node-unit/fixtures/wonky-reporter.fixture.js, test/node-unit/mocha.spec.js, test/node-unit/utils.spec.js, test/unit/mocha.spec.js
also: reorganize, add, and refactor a bunch of problematic unit tests for `lib/mocha.js`.  better isolation except where we can't really do that (calling `require`)
there's still missing tests in here, but this is an improvement.
@craigtaub this touches some stuff regarding warnings for invalid reporters.  it looks like the conditionals were backwards?
=> fix improper warnings for invalid reporters

lib/cli/run-helpers.js, lib/cli/run.js, lib/mocha.js, lib/utils.js, test/integration/fixtures/options/require/root-hook-defs-a.fixture.js, test/integration/fixtures/options/require/root-hook-defs-b.fixture.js, test/integration/fixtures/options/require/root-hook-defs-c.fixture.js, test/integration/fixtures/options/require/root-hook-defs-d.fixture.js, test/integration/fixtures/options/require/root-hook-test-2.fixture.js, test/integration/fixtures/options/require/root-hook-test.fixture.js, test/integration/options/require.spec.js, test/node-unit/cli/run-helpers.spec.js, test/node-unit/utils.spec.js, test/unit/mocha.spec.js, test/unit/utils.spec.js
> (documentation will be in another PR; this depends on #4237)
Adds "root hook plugins", a system to define root hooks via files loaded with `--require`.
This enables root hooks to work in parallel mode.  Because parallel mode runs files in a non-deterministic order, and files do not share a `Mocha` instance, it is not possible to share these hooks with other test files.  This change also works well with third-party libraries for Mocha which need the behavior; these can now be trivially consumed by adding `--require` or `require: 'some-library'` in Mocha's config file.
The way it works is:
1. When a file is loaded via `--require`, we check to see if that file exports a property named `mochaHooks` (can be multiple files).
1. If it does, we save a reference to the property.
1. After Yargs' …
=> add Root Hook Plugins

.eslintrc.yml, docs/index.md, lib/cli/run-helpers.js, lib/esm-utils.js, test/integration/fixtures/options/require/esm/package.json, test/integration/fixtures/options/require/esm/root-hook-defs-esm.fixture.js, test/integration/fixtures/options/require/root-hook-defs-esm.fixture.mjs, test/integration/options/require.spec.js
Allow files/modules specified in `--require` to be ESM.
CommonJS loading is still supported and the default.
closes https://github.com/mochajs/mocha/issues/4281
Support `--require`ing ESM files in config. Current behavior is to fail on `ERR_REQUIRE_ESM`.
Re-use existing "require or import" logic for loading test files to load required files.
Pipe requiring the ESM file through something like [esm](https://www.npmjs.com/package/esm) or [ts-node](https://www.npmjs.com/package/ts-node). Although that seems much more complicated and overkill.
Requiring JS files before the test suite is a core part of Mocha's functionality. This extends that support to ESM-first codebases, which is natively supported via `"type":"module"`, or `--exerimental-module`.
Allows developers more freedom in choosing …
=> Support --require of ESM; closes #4281

docs/index.md
> (this PR needs the changes from the `boneskull/issue/2839-11ty-changes` branch)
Build might not work until that one gets merged
=> add docs for parallel and root hooks

docs/index.md, lib/cli/cli.js, lib/cli/run.js, test/integration/fixtures/options/require/root-hook-defs-esm-broken.fixture.js, test/integration/options/require.spec.js
This PR conflates two things, and I apologize.  
I've updated the docs to show how to use ESM with root hook plugins.
I've also added a fix in the case that the `middleware` fails.  It looks like yargs does not handle async middleware rejections properly--it fails to trap any error, and instead prints an unrelated problem.  So, if `handleRequires` or `validatePlugin` fails, we need to trap that error ourself and print it, then force yargs to exit before the `fail` handler can take over.
Also contains refactors of `test/integration/options/require.spec.js`, which was driving me nuts due to the nondeterministic parallel tests.  It was also confusing as hell _anyway_, so hopefully the result is a little easier to stomach (it's still a hack).
=> fix unfriendly error; add ESM examples for root hook plugins; closes #4310

lib/interfaces/common.js, lib/suite.js, test/integration/options/forbidOnly.spec.js, test/unit/suite.spec.js
The handling of the `--forbid-only` option is currently inconsistent for the`Test` and `Suite` classes. Suites that are marked as only and excluded by `--grep`  or `--fgrep` don't throw an error. Test that are marked as only but excluded by `grep` or `f-grep` do throw an error. 
Following the discussion in #4256 it was suggested that due to the nature of the `--forbid-only` option it should not matter if a suite or test is excluded by a grep. An error should be thrown either way to protect the user from forgetting to remove `.only()` statements from his test code. I moved the changes concerning this inconsistency, including a refactoring of the Suite class to use a `markOnly()` instance method, into this PR to separate them from the fix #4256 for bug #3840.
An alternative to make it …
=> Consistent handling of --forbid-only for suites and tests

docs/index.md, lib/mocha.js, lib/utils.js, package-lock.json, test/integration/esm.spec.js
Fixes #4297. It seems that Mocha works with Node v10. So I enabled it to work in Node v10, but added documentation to say that it isn't officially supported and use at your own risk.
=> enable esm support in Node v10

.travis.yml, appveyor.yml
Node v13 is end-of-life: June 1st / 2020
=> Remove Node v13 from CI test matrix

.mocharc.yml, package-scripts.js
Having run benchmarks against our unit tests and integration tests, I've found that the unit tests do not benefit from parallel mode--and in fact, they run more slowly.  Integration tests still see a 50% performance boost, so we will use parallel tests for those only.
=> disable parallel mode by default

docs/_data/supporters.js
After merging #4318 , building our docs are failed with `Error: Unsupported image type`. See [here](https://app.netlify.com/sites/mocha/deploys/5ee47f8ed28ad60008aa8f19) or [here](https://app.netlify.com/sites/mocha/deploys/5ee3de46550b6a0008874fc1)
One of our backers(id is `7mywxoz3-409rl6ka-anpvenbd-j7gk85ag`)'s avatar URL is <https://images.opencollective.com/andréleifeld/97285d0/avatar/32.png>. Because `é` character in path, cloudflare return blocked HTML page instead avatar image.
This HTML page is `Sorry, you have been blocked. You are unable to access opencollective.com`. So, the image has `png` extension but it is not an image. 
I'm not sure whether it is [needle](https://www.npmjs.com/package/needle)'s problem or cloudflare's problem.
But, we should encode avatar URL before …
=> Fix wrong sponsors images from OC

docs/index.md
Newer versions of Node.js introduce the `--enable-source-maps` flag which, when enabled, caches source-maps and provides accurate stack traces to users running transpiled code, e.g., TypeScript.
Many users of Node.js are writing TypeScript, this allows them to receive better stack traces in mocha without installing any dependencies.
There's still work to be done to polish this feature in Node.js (would very much appreciate getting feedback).
=> docs: document Node.js' --enable-source-maps flag

.github/workflows/nightly-site-deploy.yml
This sets up a job to run at 00:00 UTC every day, which rebuilds the site from the `mochajs.org` branch.  This keeps the list of supporters up-to-date.  It relies on a secret env var to do its thing.
Will try to figure out how to test this...
=> trigger netlify deploy nightly

CHANGELOG.md
A commit was missed in v8.0.0 changelog. See https://github.com/mochajs/mocha/compare/v7.2.0...v8.0.0.
=> Add missing commit in v8.0.0 release

browser-entry.js
There seem to be 2 issues currently with the `delay` option in the browser usage.
1. setting `mocha.setup({delay: false})` actually enables the delay - this is because `delay` does not work with an argument.
2. calling `ui` before `delay` does not apply the delay  (see issue). 
```javascript
// this does not work
mocha.setup({ui: 'bdd', delay: true});
```
This fix runs `delay` flag separately to the others.
Could update `delay` to work with an argument. Thought it was slightly better to apply a fix just to the browser-based code. Also that would not have been enough to fix the issue with the ordering.
Could not see a way to get it to work like the CLI as mocha handles options differently for cli + browser (e.g. whats available for the constructor).
Currently no HTML reporter tests so is …
=> Browser usage issues with `delay` option

lib/browser/progress.js, lib/cli/collect-files.js, lib/interfaces/common.js, lib/mocha.js, lib/nodejs/parallel-buffered-runner.js, lib/nodejs/serializer.js, lib/pending.js, lib/runnable.js, lib/runner.js, lib/suite.js
We should not document any globals in the context of programmatic usage, which is the target for the api docs.
The **Members** and **Methods** we have listed live are currently mostly wrong and sometimes sending people down the wrong path. By removing them we remove confusion.
I have given an explicit module directive name to fix the **Methods**, the other half of **Members** were manual tags.
We could remove the module directive from the "interfaces/common" module, which leaves just the hooks (after/afterEach/before/beforeEach). 
But I decided it was better to have either ALL of the available globals given, or none of them.
https://github.com/mochajs/mocha/issues/4317
=> Remove GLOBALS in api docs

netlify.toml, package-scripts.js, scripts/netlify-headers.js
- non-production builds will now publish from `docs/_site`
- branches and production contexts will use production build
- `npm start docs` now does _not_ run in production build
- use `npm start docs.production` for production build
- `scripts/netlify-headers.js` now requires a path
- fixed duplicate message in `scripts/netlify-headers.js`
- add `RUBY_VERSION` to netlify env
=> do not run production build on netlify for PRs; closes #4356

lib/cli/cli.js, test/integration/init.spec.js
`yargs.exit()` is not always present, apparently. it will throw in this case--we don't need to be calling it anyway.
before this change, you see the following when running `mocha init` w/o the `<path>`
```
mocha init <path>
create a client-side Mocha setup at <path>
Positional Arguments
path                                                       [string] [required]
Other Options
--help, -h     Show usage information & exit                         [boolean]
--version, -V  Show version number & exit                            [boolean]
✖ ERROR: Not enough non-option arguments: got 0, need at least 1
/Users/boneskull/projects/mochajs/mocha/node_modules/yargs/yargs.js:1172
else throw err
^
TypeError: yargs.exit is not a function
at Array.<anonymous> …
```
=> fixes failure output in mocha init w/o target

package-lock.json, package.json
package.json's javascript-serialize 3.1.0 to 4.0.0
Mocha can prepare for serializing bigint later.
https://github.com/yahoo/serialize-javascript/releases/tag/v4.0.0 
related to #4375
=> Update javascript-serialize 3.1.0 to 4.0.0

lib/cli/watch-run.js, test/integration/fixtures/options/watch/hook.fixture.js, test/integration/options/watch.spec.js
Tests with root level hooks are ignored when running in watch mode.
This occurs on initial & subsequent runs.
- updated `lib/cli/run-watch` to re-initialise rootHooks
As we have swapped out the root suite it is necessary to re-initialize
root level hooks again.
- Extended integration tests for watch to take into consideration
hooks
- mochajs/mocha/issues/4347
=> Fix #4347 | Ensure root level hooks are called when running in watch mode

lib/reporters/base.js
looks like maybe a bad merge, but `isBrowser()` was used incorrectly
=> fix window width problem; closes #4393

rollup.config.js, test/browser-specific/esm.spec.mjs
To apply UMD pattern, Mocha module was located in `mocha` as module name. But browsers are be able to access Mocha as global variable with this change.
I added *rollup config* `footer` to assign Mocha module to global variable. I hope that this would be the alias to acutal Mocha module,  not deep cloning another Mocha.
in `browser-entry.js` from line `213`
```javascript
mocha.Mocha = Mocha;
mocha.mocha = mocha;
```
I would like to suggest like next
```javascript
global.Mocha = Mocha;
global.mocha = mocha;
```
OR,
```javascript
mocha.Mocha = Mocha; …
```
=> fix: add Mocha to global variable

.github/CODE_OF_CONDUCT.md
"Code of conduct governance" text and link seem to be connected incorrectly. It has been updated.
Before: https://github.com/openjs-foundation/bootstrap/blob/master/proposals/stage-1/CODE_OF_CONDUCT/FOUNDATION_CODE_OF_CONDUCT_REQUIREMENTS.md
After: https://github.com/openjs-foundation/cross-project-council/blob/master/FOUNDATION_CODE_OF_CONDUCT_REQUIREMENTS.md
N/A
N/A
People will be able to click on the links, and get to the content they expected.
N/A
N/A
=> fix: update Code of Conduct governance document link in CODE_OF_CONDUCT.md

.eleventy.js, .gitignore, docs/.eleventyignore, docs/API.md, docs/_data/files.js, docs/api-tutorials/custom-reporter.md, jsdoc.conf.json, package-lock.json, package-scripts.js, package.json
because the files generated by jsdoc were output to `docs/_site`, they were not processed as liquid templates, which meant the custom reporter tutorial was broken (the included "simple reporter" fixture file was not loaded, and the raw template tag was output instead).
to fix this, we needed to:
1. change the output directory of jsdoc to `docs/api` (just somewhere else)
2. add this to `.gitignore`, obviously
3. tell eleventy to _ignore_ `.gitignore` (just rely on its `.eleventyignore` file)
4. tell eleventy to pass-through all assets underneath `docs/api` (css, images, etc)
5. update the file-loading 11ty data script to output a raw file
6. update the tutorial to use a fenced code block (jsdoc markdown plugin seems to strip html?) and tell Prettier to ignore the liquid template directive …
=> fix broken template processing in jsdoc output

lib/cli/node-flags.js, lib/cli/run-option-metadata.js, test/node-unit/cli/node-flags.spec.js
- no more `require` special-case
- future-proofs `mocha` against the introduction of conflicting flags in `node`
Fixes #4417 
Ref: https://github.com/nodejs/node/pull/34852
=> prefer all mocha flags over node flags; closes #4417

package-lock.json, package.json
See #4412.  Changes made by @sujin-park were published in `@mocha/docdash` v3.0.1, which this PR pulls in.
=> update @mocha/docdash to latest version

lib/cli/cli.js, lib/cli/index.js, lib/cli/lookup-files.js, lib/cli/options.js, lib/mocha.js, lib/nodejs/file-unloader.js, lib/utils.js, package-lock.json, package-scripts.js, package.json, test/browser-specific/fixtures/webpack/webpack.config.js, test/browser-specific/fixtures/webpack/webpack.fixture.mjs, test/unit/mocha.spec.js, test/unit/utils.spec.js
- fixes API documentation for all of these (and `module:lib/cli.main`) via JSDoc aliasing
- aliases `lib/cli/cli.js` to `module:lib/cli`; `module:lib/cli/cli` is no longer a thing
- the `lib/cli/options.js` and `lib/cli/lookup-files.js` _modules_ (not necessarily their _contents_) are now private
example usage:
```js
const {loadRc, loadPkgRc, loadOptions, lookupFiles} = require('mocha/lib/cli');
```
**UPDATE**
- restores `lookupFiles` to `lib/utils` to un-break the breaking change introduced in v8.1.0.
- use of `lookupFiles` in `lib/utils` will print a deprecation notice directing the consumer to the new path
- use of `lookupFiles` in `lib/utils` _in a browser_ (since it's accessible) will throw an exception.
**ANOTHER UPDATE**
- moves `require.cache`-touching code out of `lib/mocha.js` …
=> alias lookupFiles, loadRc, loadPkgRc and loadOptions to lib/cli module; fixes #4398

CHANGELOG.md
I found there is a type in user id and link in 8.1.2 changelog.
=> Fix typo in 8.1.2 changelog

docs/_includes/default.liquid
After executing ```docs.production``` script without ```trim``` on ```wallaby-logo```, the logo  takes 126 bytes.
However, with ```trim```, the logo takes 271bytes and it is not shown properly.
So I think it is better to remove trim operation option on ```wallaby-logo.png``` in ```default.liquid```
The reason why the logo is not shown properly after ```trim``` is a bug with ```impro``` used by ```assetgraph-builder``` that execute ```trim``` operation with ```gm```, not ```sharp```. So, it is actually a bug with ```gm```. I created another pr on …
=> Fix: Broken wallaby logo on mochajs.org #4430

test/browser-specific/fixtures/webpack/webpack.config.js
Right now `npm start test.browser.webpack` creates `dist/main.js` which is likely to be accidentally committed.  Put the output in a temp dir
=> redirect webpack test output to a temp dir

README.md
Add npm and node version badges to the README
To at least partially address https://github.com/mochajs/mocha/issues/2346
Info easier for users to access
N/A
https://github.com/mochajs/mocha/issues/2346
=> Add npm and node version badges to README

lib/reporters/json-stream.js, lib/reporters/json.js, test/reporters/json-stream.spec.js, test/reporters/json.spec.js
I modified the ` -R json` option to show speed.
N/A
#4226 
You can see speed result in `json reporter `
N/A
Fixes #4226
=> Add speed in -R json option (#4226)

lib/utils.js, package-lock.json, package.json, test/browser-specific/fixtures/esm.fixture.mjs, test/browser-specific/fixtures/webpack/webpack.fixture.mjs
Updating ESLint version from v6.8.0 to v7.8.1
N/A
Because it is updating ESLint version of mocha core.
ESLint v7.0.0 drops support for Node.js v8 as well. After updating, it will be possible to update other plugins.
Lint rules are changed.
N/A
=> Update eslint version

.wallaby.js, lib/hook.js, lib/nodejs/parallel-buffered-runner.js, lib/nodejs/reporters/parallel-buffered.js, lib/nodejs/worker.js, lib/runnable.js, lib/runner.js, lib/suite.js, lib/test.js, lib/utils.js, package-lock.json, package.json, test/node-unit/parallel-buffered-runner.spec.js, test/node-unit/reporters/parallel-buffered.spec.js, test/unit/mocha.spec.js, test/unit/runner.spec.js, test/unit/suite.spec.js, test/unit/utils.spec.js
@segrey please see this one.  It will allow a reporter to call `runner.linkPartialObjects(true)` (see example in docstring) to replace duplicated deserialized objects with references.  The objects themselves are still shallow, but if there's a particular property you need that is missing, we can likely add it.
I didn't test this too hard, but please let me know if this would help.  I'm not sure about the missing `root` prop issue...
Ref: #4403 
- fixed an issue in rollup config causing weird problems
- changed how we define `global.Mocha` in `browser-entry.js` (tangential)
- removed `object.assign` polyfill (tangential)
- renamed misnamed `buffered-runner.spec.js` to `parallel-buffered-runner.spec.js`
=> parallel mode: enable custom worker reporters and object references

lib/nodejs/buffered-worker-pool.js, package-lock.json, package.json, test/integration/options/parallel.spec.js
- updates workerpool to v6.0.2, which guarantees child processes exit before `Pool#terminate()` resolves
- cleanup `test/integration/options/parallel.spec.js`
@segrey this will make the guarantee about the worker processes you were asking about in #4403.
=> make guarantees about orphaned processes

lib/nodejs/serializer.js, test/node-unit/serializer.spec.js
After the implementations of https://github.com/mochajs/mocha/pull/3467 and https://github.com/mochajs/mocha/pull/3666, there are a few instances in the code that do not use error codes yet. This PR addresses the instances in the serializer code and does not cover all remaining instances of lack of error codes (I mainly wanted to make sure I was on the right track here before trying to change as many remaining errors as possible). 
N/A
Using codes is a best practice like in Node.js, codes help identify errors as mocha errors at a glance
Using codes is a best practice like in Node.js, codes help identify errors as mocha errors at a glance
None I'm aware of
Contributes to https://github.com/mochajs/mocha/issues/3656, semver-patch
=> Change serializer errors to use error codes

lib/nodejs/serializer.js, lib/runner.js, lib/utils.js, test/node-unit/utils.spec.js, test/unit/utils.spec.js
- Existing `utils.type()` is renamed to `utils.canonicalType()`
- Call from `utils.canonise()` is changed to `canonicalType()`
- New function `type()`added to the `utils` implementing generic type retrieval based on [MDN:DataStructures](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures) and several additional cases: Error => 'error' and String = > 'string', aiming to replace `Array.isArray()`, `typeof` and `Buffer.isBuffer`.
Diff functionality, as suggested in the related issue, should be separated in its own module. 
The only difference is that this PR implies incremental changes.
An alternative could be to instead implement `isType(value, type)` due to the use intentions.
- It is part of the core functionality
- Lays foundation for future `utils` refactoring
- Adds …
=> refactor: utils.type()

lib/cli/lookup-files.js, test/integration/file-utils.spec.js
Allow `extensions` configuration option to support multipart extensions, ex: `test.js`. extension matching support is currently implemented by matching against [node's `path.extname`](https://nodejs.org/api/path.html#path_path_extname_path) which
> returns the extension of the path, from the last occurrence of the . (period) character to end of string in the last portion of the path.
This prevents support for multipart extensions like `.test.js`.
By instead using [`String.prototype.endsWith`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Referen …
=> Support multipart extensions like ".test.js"

docs/index.md, lib/cli/lookup-files.js, test/integration/file-utils.spec.js, test/integration/options/extension.spec.js
- update documentation for the feature and multipart extensions
- rename integration test `file-utils.spec.js` to `lookup-files.spec.js` and "modernize" it
Ref: #4442
=> support leading dots in --extension

lib/cli/run-helpers.js
When users run mocha with ```--parallel``` option wihtout ```--jobs``` option, ```undefined``` was passed to the parallelRun method.
I changed options.jobs to the number of CPU cores less 1 when options.jobs was false.
**AS-IS**
**TO-BE**
in ```lib/cli/run-helpers.js``` from line ```179```
**AS-iS**
```javascript
options.jobs
```
**TO-BE**
```javascript
options.jobs ? options.jobs : workerpool.cpus - 1
```
It's a confirmed bug as described in #4415. 
Users can know exact current concurrent job count instead NaN.
N/A
#4415
=> fix: the number of concurrent job with --parallel option in mocha:cli:run:helpers

test/unit/mocha.spec.js
these were duplicated in the node unit tests, but they were causing problems in the browser tests.
=> remove duplicated/problem reporter tests; closes #4469

lib/nodejs/parallel-buffered-runner.js, package-lock.json, package.json
This is a workaround for https://github.com/npm/cli/issues/1113; see #4474 for how this impacts Mocha.  It's very odd behavior indeed.
After this change, running `npm install --production` with `mocha` in the `devDependencies` does _not_ install any of Mocha's production deps nor its transitive production deps.
I don't have a great strategy for automating the testing of this this (yet), but what you can do is:
1. Pull this PR into a working copy
1. Run `npm install`
1. Run `npm pack` which will result in a `.tgz`
1. Grab https://github.com/danludwig/npm-module-bug-reports and navigate into `mocha-2020-10-bug` directory
1. In this dir, update `mocha` in `package.json` to point to the tarball on disk (relative or absolute path) and `rm package-lock.json; rm -rf node_modules` to be sure it's …
=> replace promise.allsettled with @ungap/promise-all-settled; closes #4474

package-lock.json, package.json
- Upgrade to `chokidar@3.4.3`.
- Pinned `@ungap/promise-all-settled` for consistency.
Perhaps use `^` in dependencies as well.
New chokidar version fixes infinite loops on circular symlinks: https://github.com/paulmillr/chokidar/blob/master/.github/full_changelog.md
Better deduping in consumer projects, as most of the ecosystem uses ^ and picks up the latest of that major.
New versions always have the possibility of a regression.
None.
=> chore(deps): chokidar@3.4.3, pin @ungap/promise-all-settled

docs/example/debug-hanging-mocha.js, test/integration/diffs.spec.js, test/integration/fixtures/current-test-title.fixture.js, test/integration/fixtures/diffs/diffs.fixture.js, test/integration/fixtures/no-diff.fixture.js, test/integration/fixtures/retries/early-pass.fixture.js, test/integration/fixtures/uncaught/listeners.fixture.js, test/integration/no-diff.spec.js
I removed deprecated methods and tested it. ```equal, deepEqual``` methods are deprecated since v.9.9.0. [Assert Reference](https://nodejs.org/api/assert.html#assert_assert_equal_actual_expected_message)
I used ```strictEqual, deepStrictEqual``` instead.
**deprecated**
```javascript
assert.equal(getTitle(this), undefined);
assert.deepEqual(sock.address().family, 'IPv4');
```
**changed**
```javascript
assert.strictEqual(getTitle(this), undefined);
assert.deepStrictEqual(sock.address().family, 'IPv4');
```
For now, PR's just changed methods that was …
=> Change assert module's deprecated methods in testing files

docs/index.md
Minor documentation update.
https://mochajs.org/#global-fixtures shows
> New in v9.0.0
Whereas global fixtures was recently introduced in v8.2.0 https://github.com/mochajs/mocha/blob/v8.2.0/CHANGELOG.md
This pr corrects this nit.
=> Correct global fixtures release version in documentation

lib/errors.js, lib/runner.js, test/integration/fixtures/uncaught/unhandled.fixture.js, test/integration/uncaught.spec.js, test/unit/errors.spec.js
This is not intended as a _fix_ for #4481, since it's possible that Mocha's behavior in v8.2.0 uncovers false positives.  In other cases--depending on the use-case--they are not false positives at all, but rather annoyances that depended on the pre-v15 behavior of Node.js to only issue warnings.
This PR changes the behavior of Mocha so that it will re-emit unhandled rejections to `process` _if_ they did not generate from Mocha.  If the rejection generated from Mocha, then we treat it as an uncaught exception, because Mocha should not be in the business of ignoring its own unhandled rejections.  The logic for detecting an "error originating from Mocha" is not exhaustive.
Once an unhandled rejection is re-emitted to `process`, Node decides what to do with it based on how it is configured to …
=> delegate to Node on non-Mocha unhandled rejections

lib/cli/watch-run.js, test/integration/helpers.js, test/integration/options/watch.spec.js
- Mocha instance needed a `dispose()` call before re-instantiation
- Exposed `sleep()` in integration test helpers
Ref: #4495
=> properly dispose Mocha instance in watch mode; closes #4495

test/assertions.js, test/integration/README.md, test/integration/helpers.js
- refactor assertion types
- add `test/integration/README.md`
- add support for `MOCHA_TEST_KEEP_TEMP_DIRS` env var
=> handful of improvements to integration tests

README.md
I just found we only show travis build status badge on our README.
But we already moved most our build and test to GH actions except browser tests and we will move out all of them from travis-ci.
So, travis-ci build status badge doesn't show our build status.
And I reformatted HTML for badges so that we can read HTML and diff easily.
We can show the current master's build status to users.
ref: https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/adding-a-workflow-status-badge
=> Add GH Actions workflow status badge

.github/workflows/mocha.yml, package-lock.json, package.json
- prevent tests from being triggered twice (by the `push` and `pull-request` events).
- browser test:
- is flaky: update dependency `karma-sauce-launcher`. This could help, maybe.
- job regularly runs 360m until cancelled by github => sets `timeout-minutes` to 20m.
- Growl test:
- fails => temporarily removes download/installation/start of Growl on Windows.
=> Improve CI tests workflow

.github/workflows/mocha.yml
When a maintainer pushes a commit to this repo, two events (`push` and `pull-request`) are triggered and the same CI tests run twice. But the `pull-request` event should trigger the tests only for PR's from forked repos (no `push` event).
- my previous fix did not work, since `branches` contains the `into` branch name (`master`),
and not the `from` branch name (`user:branch-name`).
- jobs are skipped now with a `if` conditional.
Drawback: the skipped jobs are listed in the workflow job matrix, but at least the don't run anymore.
=> Fix workflow filter on pull-request events

bin/mocha, lib/cli/options.js, package-lock.json, package.json, test/node-unit/cli/options.spec.js
We have been using rather old versions of these dependencies. It's time for an upgrade.
There have been breaking changes in _**yargs**_' handling of array typed options, especially when supplied via configuration object `config()`. In order to avoid double entries when combining array values, I had to remove aliased options from the parsed result.
=> Update dependencies yargs and yargs-parser

docs/index.md
It's broken JavaScript syntax when we explain the root hook migration.
=> fix javascript syntax errors

.github/workflows/purge-expired-artifacts.yml
Since recently the ESLint Check in GH actions is failing:
`Error: HttpError: Failed to generate URL to download artifact`
`Error: Failed to generate URL to download artifact`
GH does not delete expired artifacts.
`https://api.github.com/repos/mochajs/mocha/actions/artifacts` shows aprox. 20 artifacts, all of them expired.
When _eslint-plus-action@v3.4.2_ is trying to download an expired artifact, it fails.
It's unclear to me why we have artifact at all on that job.
```
{
"total_count": 20,
"artifacts": [
{
"id": 24440022,
"node_id": "MDg6QXJ0aWZhY3QyNDQ0MDAyMg==",
"name": "eslint-cache-key-lint-results-Tests-4498",
"size_in_bytes": 5477,
"url": "https://api.github.com/repos/mochajs/mocha/actions/artifacts/24440022",
"archive_download_url": …
```
=> GH actions: purge expired artifacts

package-lock.json, package.json
Our CI tests are failing with Node v15.8
```
node:internal/validators:158
throw new ERR_INVALID_ARG_TYPE(name, 'Object', value);
^
TypeError [ERR_INVALID_ARG_TYPE]: The "options" argument must be of type object. Received an instance of Array
at ChildProcess.target.send (node:internal/child_process:716:7)
at Array.forEach (<anonymous>)
at dispatchQueuedRequests (/home/runner/work/mocha/mocha/node_modules/workerpool/src/WorkerHandler.js:262:21)
at ChildProcess.<anonymous> (/home/runner/work/mocha/mocha/node_modules/workerpool/src/WorkerHandler.js:221:7)
at ChildProcess.emit (node:events:378:20)
at emit (node:internal/child_process:920:12)
at processTicksAndRejections (node:internal/process/task_queues:82:21) {
code: 'ERR_INVALID_ARG_TYPE'
}
```
Upgrade workerpool to v6.1.0
=> Deps: update workerpool to fix failing CI tests

lib/esm-utils.js, test/integration/esm.spec.js, test/integration/fixtures/esm/syntax-error/esm-syntax-error.fixture.mjs
According to issue #4551 (I verified that it is true), when there is a syntax error in an ESM file, the error thrown by Node.js contains only the error, but not the location (file and line number) where this problem happened. 
While the error doesn't include this information, we have the filename and can "inject" it into the error artificially. At least until Node.js fixes the problem. This change is local to ESM as it is only in the ESM importing code.
The only alternative I can see is to get Node.js to fix the problem.
Because plugins can't fix this.
It is currently difficult to figure out on which test file the syntax error happened. This helps a lot by at least giving the file where the syntax error is. Usually, in the IDE, the developer can figure out what the problem is.
The code …
=> Add file location when SyntaxError happens in ESM (fixes #4551)

lib/utils.js, test/unit/utils.spec.js
Fixes #4090, adds a new case to the _stringify function in utils so it can handle the BigInt case.
There were two choices considered in the issue `BigInt<123>` or `123n` i went with the latter because it's the standard way JS presents BigInts
Nice way of representing BigInts in errors.
Support for Stringify-ing BigInts
I had to add `/* global BigInt */` at the top of the spec file, i don't know if that is the best place for it.
Fixes #4090
=> Adds BigInt support to stringify util function.

docs/index.md
Quick docs update showing a workaround with some common issues run into w/data-driven tests.
Namely, it's very hard to run a single testcase from an IDE because tests inside a `.forEach` callback aren't detected, Compare
with
N/A (docs update)
N/A (docs update)
This approach has been useful for me & my team - hope it can be useful for someone else too
Slightly more verbose than pure data-driven approach.
=> docs: Add example of generating tests with a HOF

docs/_includes/supporters.md
Currently, [mochajs.org](https://mochajs.org/#sponsors) doesn't show any sponsors or backers. 
I'm not sure when this problem occurred. 
[This commit](https://github.com/mochajs/mocha/commit/cf736fedfb15203824c0d21af7900112354f5804#diff-e4c53b7172f4257db299fa9e7502d3ced0348c61013f8816258218a223649186R39-R40) introduced `SPONSOR_TIER` and `BACKER_TIER` constants and then [this commit](https://github.com/mochajs/mocha/commit/df8e9e6f0108cd06925ea745bb26771ed458c7cb#diff-e4c53b7172f4257db299fa9e7502d3ced0348c61013f8816258218a223649186R229-R230) use these constants for `supporters`'s child properties name.
So, we used `supporters.sponsors` and `supporters.backers` previously but, now it changed to `supporters.sponsor` and `supporters.backer`. However we didn't change `supporters.md`.
=> match supporter's properties with supporter.js

package-lock.json, package.json, rollup.config.js
Mocha provides a bundle that can be used directly in the browser. For compatibility with Internet Explorer 11, the bundled code is transpiled using Babel. When using `async` functions (or generator functions) as Mocha started in 12db9db (8.2.0), Babel adds the `regenerator-runtime` module to the bundle, which relies on unsafe eval to access the global scope in strict mode, which in turn makes Mocha incompatible with environments that don't allow unsafe eval.
In this PR, I implement a workaround that prevents `regenerator-runtime` from using unsafe eval. First I had to update `regenerator-runtime` since the currently used version relies on `this` in an unbound function referring to the global object which we don't have any control over, while the new version instead exploits implicit …
=> Fix EvalError caused by regenerator-runtime (#4535)

lib/mocha.js, test/integration/common-js-require.spec.js, test/integration/fixtures/common-js-require.fixture.js, test/integration/fixtures/parallel/test1.mjs, test/integration/fixtures/parallel/test2.mjs, test/integration/fixtures/parallel/test3.mjs, test/integration/parallel.spec.js
Fixes the issue where `import { describe, it } from 'mocha'` doesn't work with `--parallel` when using es modules by proxying `describe`, `it` and friends to their actual contextual counterpart.
There is not much else we can do I think, other than going full blown esm (for example, using [package exports](https://nodejs.org/api/packages.html#packages_exports)).
Its imported from core (bare `'mocha'`).
Allows `import {...} from 'mocha'` in an es module setting with `parallel`
More code to maintain
Closes #4559, should be a patch release.
=> fix(esm): allow `import` from mocha in parallel

.github/workflows/mocha.yml
Now [GH actions officially support [skip ci]](https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/). So, we don't need this workaround anymore. 
If commit message contains `[skip ci]`, `[ci skip]`, `[no ci]`, `[skip actions]`, or `[actions skip]`, GitHub actions workflow never run. It means there are no logs it was skipped. Just skipped.
=> Remove [skip ci] workaround for GitHub Actions

karma.conf.js
This patch contains modifications to the `karma.conf.js` to include build ids to the tests. This will fix the invalid badge on the Readme which now shows `unknown` because no new builds have been created for a while.
None, build id is required to display correct badge information
Because the readme lives in this repo.
Showing up to date build status promotes MochaJS being a stable testing framework.
None.
It is a documentation update.
=> Add build to GH actions run

example/config/.mocharc.js, example/config/.mocharc.json, example/config/.mocharc.jsonc, example/config/.mocharc.yml
I tried to add reporter options as `reporterOptions` or `reporterOption` and failed miserably for quite a while until I accidentally found out that it needs to be specified like in the example below.
I think it's worth adding an example to the documentation to save other people's time.
=> Add reporter options example

docs/_data/blocklist.json, docs/_data/supporters.js, docs/_includes/supporters.md, docs/index.md
Our site [mochajs.org](https://mochajs.org/) is listing the avatars/links of our financial contributors at _OpenCollective_:
- all (active and cancelled) contributors are shown
- the distinction between sponsor and backer is incorrect. At the moment we only have one active sponsor.
- The majority of monthly contributions (ORDER) has been cancelled by the contributors (ACCOUNT).
We only select orders with `ORDER.status===ACTIVE` and ignore the cancelled ones.
- We use `ORDER.tier` set by _OpenCollective_ for correct distinction (`sponsors`, `backers`).
closes #4595
=> Filter active sponsors/backers and categorize correctly

docs/index.md
Now we suuport `.js`, `.cjs` and `.mjs`.
We missed these extensions for the glob pattern under the `test` directory.
fix #4593
=> docs: update missed default extensions

lib/interfaces/bdd.js, lib/interfaces/common.js, lib/interfaces/qunit.js, lib/interfaces/tdd.js
We remove `test.retries(n)` from our interfaces `common`, `bdd`, `tdd`, `qunit`.
This function has never been used/implemented correctly as shown by coverall's excited reaction. Furthermore the signature is weird and somewhat incomplete.
This PR _does not affect_:
- `this.retries(n)` within `suite`s and `test`s
- `it(title, fn).retries(n)`
=> Remove unused and incorrect `test.retries(n)`

docs/index.md
With `top-level await` test data can be collected in a dynamic and asynchronous way, while the test file is loaded and before the test `runner` is created. Since ESM files are already loaded in an asynchronous way, no changes to our code base are needed.
Requisite:
- `top-level await`: since Node >= v14.8.0
- `ESM` (ECMAScript module) test file
=> docs: dynamically generating tests with `top-level await` and ESM test files

.github/workflows/browser-test.yml, .github/workflows/mocha.yml
It is the only way I found to run browser tests on forked PR. 
After reviewing code of a forked PR, maintainers can attach [a `run-browser-test` label](https://github.com/mochajs/mocha/labels/run-browser-test).
Maintainers should check there is no malicious code to steal our secrets or do something bad on our repository.
This `Browser Tests` workflow will run based on forked PRs with writing repo and access secrets permissions. So, it can be  dangerous if the forked PR has malicious code.
I've tested `pull_request_target` event.
When users open a pull request, `push`, `pull_reqeust` and `pull_request_target`  will be run automatically. But `pull_request_target: types: [labeled]`(in this case `Browser Tests`) will not be run because `labeled` type.
If maintainers attach a label except …
=> Run browser tests on forked PRs by a dedicated label

lib/cli/watch-run.js, test/integration/helpers.js, test/integration/options/watch.spec.js
In watch mode, the watcher crashed when there are syntax errors in test files during `require('test file')`.
It only happens in serial mode and Node v15+.
This `try - catch` statement removed [when we introduce parallel mode](https://github.com/mochajs/mocha/commit/2078c3203f55ee0e1783dc2fc9e20ac51dcb6896#diff-14a1e3aa193d6f208b9ffdfeec1876f2cbc0e51007d061a87644e9ea9df59676L94).
I think we need `try - catch` here.
And I added test cases for the crash case to prevent regression.
Watching should be worked.
Users can use watch mode when the test code is broken.
Fix #4580
=> Watch for test files are crashed

.github/workflows/mocha.yml, .github/workflows/stale.yml
Replaces Node v15 by v16.
End-of-life of v15 is 2021-06-01.
=> GH actions: add Node v16

lib/mocha.js
#closes #4575
The root hooks aren't executed when Mocha is run programmatically and in parallel.
In parallel mode it's necessary to pass the path of the `rootHooks` plugin to the `mocha` instance as this information is not available via IPC to the worker processes.
We add `options.require` to the API docs for the Mocha constructor. No code change is required.
=> Docs: add "options.require" to Mocha constructor for root hooks on parallel runs.

lib/cli/config.js, lib/cli/options.js, lib/errors.js, test/node-unit/cli/config.spec.js, test/node-unit/cli/options.spec.js, test/unit/errors.spec.js
After the implementations of https://github.com/mochajs/mocha/pull/3467 and https://github.com/mochajs/mocha/pull/3666 and https://github.com/mochajs/mocha/pull/4464, there are a few instances in the code that do not use error codes yet.
Open to other names for this error code
Using codes is a best practice like in Node.js, codes help identify errors as mocha errors at a glance
Using codes is a best practice like in Node.js, codes help identify errors as mocha errors at a glance
None I'm aware of
Contributes to https://github.com/mochajs/mocha/issues/3656, semver-minor
=> Change CLI file parsing errors to use an error code

.github/workflows/mocha.yml, docs/index.md, package.json, test/integration/parallel.spec.js
We drop support of Node v10 with end-of-life: 2021-04-30
=> Drop support of Node v10

lib/reporters/base.js
I used the `log-symbols` instead of the code for win32.
No alternate designs
Mocha already uses `log-symbols`, so we can remove duplicated code and maintain consistency.
I also deleted the `dot` case, But I don't know if the size difference between dot for win32(`.`) and dot for the others(`․`) is a problem.
So I think this might be a problem.
* Enter any applicable Issues here.
https://github.com/mochajs/mocha/issues/4353
The above issue is not directly related to the PR.
But I think you may want to use alphabets rather than `log-symbols` to resolve the issue.
like this
```
success : v or o
fail : x
```
Please leave a good comment or question at any time :)
* Is this a breaking change (major release)? no
* Is it an enhancement (minor release)?  maybe, yes
* Is it a bug fix, or does it …
=> Refactoring: Consuming log-symbols alternate to code for win32 in reporters/base.

.github/workflows/delete-runs.yml
We add a GH action to delete old workflow runs. There is no sense in keeping thousands of run logs.
- GH action: [delete-workflow-runs](https://github.com/marketplace/actions/delete-workflow-runs)
- manually triggered
- retain days: 120 days
=> GH actions: delete old workflow runs

lib/reporters/base.js, test/reporters/base.spec.js
Before, The order of the previous processing is as follows
1. error message is function
2. error include inspect parameter
3. empty
After
1. check include inspect custom function
2. error message is function
3. empty
So developers can custom error message if they want
I have been found util.inspect.custom API, but if set up util.inspect.custom that changed error format 
So this pr only change ordering with err.inspect function and err.message 😭 
Developer can custom error message handling in mocha …
=> Fix: control stringification of error message

docs/index.md, lib/esm-utils.js, test/integration/fixtures/exit.fixture.js
Test files can be either CJS or ESM. Up to now, we used the following method to support both: first require, and if that fails with `ERR_REQUIRE_ESM`, then use import.
This was a necessity so long as some supported Node versions did not support ESM. Now that all supported versions of Node support ESM, we can go to a better import-first method, whereby we first try using `import(file)` and only if that fails, do we try `require`.
This is a big change, which is theoretically transparent, but could result in unforeseen behavior. **We should do this in a SEMVER_MAJOR change.**
Figure out whether the file is CJS or ESM: unfortunately, the algorithm is complex and basically should replicate Node's, which is practically impossible.
Because no plugin can do this.
Allowing ESM loaders to transform …
=> import-first loading of test files

lib/reporters/base.js, test/reporters/base.spec.js
Mocha prints its own diff on assertion errors by stringifying `err.actual` and `err.expected`, then passing both strings to [jsdiff](https://github.com/kpdecker/jsdiff) for generating a diff-patch. For big strings this synchronous process can take several minutes.
_jsdiff_ has some known performance issues, so in mid-term we evtl. should evaluate a _jsdiff_ alternative.
On the other hand it's not a good idea to calculate a diff for two huge strings, even with a faster algorithm. We should limit the size of the input strings, as eg. done by Node's `assert` as well.
- no change: stringify `err.actual` and `err.expected`
- new: when too big, truncate the resulting strings and add a message `... Lines skipped`
closes #3675
=> Limit the size of 'actual'/'expected' strings before generating a diff

lib/runner.js, test/unit/runner.spec.js
We deprecate following signature of the `Runner` constructor: `Runner(suite: Suite, delay: boolean)`
Instead use an option object: `Runner(suite: Suite, {delay: boolean})`
=> [API docs](https://mochajs.org/api/runner)
=> Deprecate "new Runner(suite: Suite, delay: boolean)"

docs/index.md, lib/cli/run-option-metadata.js, lib/cli/run.js, lib/mocha.js, lib/runner.js, lib/utils.js, test/integration/fixtures/options/dry-run/dry-run.fixture.js, test/integration/options/dryRun.spec.js, test/integration/reporters.spec.js, test/reporters/json-stream.spec.js, test/unit/mocha.spec.js, test/unit/utils.spec.js
Adds a `--dry-run` option, which executes the `runner` and makes all `tests` pass without actually running any `hook`/`test`.
- add option `--dry-run`
- pass it to the `mocha`, then `runner` instance
- do not execute any `hook` or `test`
- other options as `skip` or `only` work as in a normal run
additionally:
- remove `utils.dQuote()` and `utils.sQuote()`
- use `template strings` instead
=> Add new option "--dry-run"

lib/esm-utils.js
Fixes #4652.
The version check in `hasStableEsmImplementation` returns `true` for any version that has minor component >= 22 (e.g. for version 10.24.x which is currently the latest one in the 10.x branch).  Even though Node.js v10 is officially not supported, I still see a lot of sense to fix this and make `hasStableEsmImplementation` work properly.
None
A lot of CI tasks are still using 10.x for compatibility reasons.
No unintended breaking change to Node.js v10.24.x users.
None known.
#4652
=> fix: proper version check in hasStableEsmImplementation

.eslintignore, .eslintrc.yml, .gitignore, karma_no-ie11.conf.js, package-scripts.js, package.json, rollup_no-ie11.config.js
We add a second browser bundle `mocha-es2018.js` to our package for modern browsers:
- in javascript ES2018, since it isn't transpiled to ES5
- this is an experimental step towards freezing Mocha's support of IE11.
=> Browser: add separate build for modern browsers

.browserslistrc, .github/workflows/delete-runs.yml, .github/workflows/mocha.yml
When pushing a new Mocha version/release to our `master` branch, the identical CI tests run twice. Once for the new commit and a second time for the new version tag. With this PR `push` events on new tags get ignored and no CI tests are triggered.
=> GH actions: don't run CI tests for 'push' events on tags

karma.conf.js, karma_no-ie11.conf.js, package-scripts.js
Some days ago I added a second browser bundle to our package:
- `mocha.js` transpiled to ES5
- new: `mocha-es2018.js` without transpilation
When customizing our browser tests I ended up with executing the _karma_ tests twice, using the same bundle `mocha.js`. So the new `mocha-es2018` currently remains untested.
I could not find a way to convince _karma-mocha_ to run a browser bundle other than named `mocha.js`.
Therefore I rename the two bundles accordingly before launching _karma_.
=> Fix: 'karma-mocha' should run both browser bundles

lib/esm-utils.js, test/integration/esm.spec.js, test/integration/fixtures/esm/dir-cjs-require/index.js, test/integration/fixtures/esm/test-that-uses-dir-cjs-require.fixture.js/index.js
When falling back on CJS when loading test files, ensure that `ERR_UNSUPPORTED_DIR_IMPORT` is supported so that `-r <cjs-package>/dir` will work. See #4665 for a more detailed description.
This is a bug fix to return support to what was before enabled.
None
#4665 
* Mocha follows semantic versioning: http://semver.org
* Is this a breaking change (major release)? No
* Is it an enhancement (minor release)? No
* Is it a bug fix, or does it not impact production code (patch release)? Yes
=> Fixes #4665. make "-r <dir>" work with new import-first loading

lib/cli/run-helpers.js, lib/errors.js, test/node-unit/cli/run-helpers.spec.js
see discussion in #4659, thanks to @love-expressen for his analysis.
> When using the `--ui` option together with `--parallel` the `ui` option is not passed to the workers. This causes errors when running test files that depend on the UI being set up in the worker executing the test.
> The root cause of the issue is that mocha refers to external UI:s in the options object as function references and not the UI identifier string. When the options object is being serialized all functions are (thankfully) ignored. This causes the mocha instance in the workers to default to the bdd UI.
Mocha's native interfaces are cached in `Mocha.interfaces` as function references where each key corresponds to an interface name. The interface name can easily be serialized and passed to the parallel workers. …
=> Fix: using custom interface in parallel mode

lib/cli/config.js, test/integration/config.spec.js, test/integration/fixtures/config/mocharcWithThrowError.js
Fixed incorrect comparison operator in `isModuleNotFoundError` function in `lib/cli/config.js` so Mocha rethrows error from cwd-relative path js config file
It is already in core but doesn't work as expected
Mocha rethrows error from cwd-relative path js config file
None that I can think of
Closes https://github.com/mochajs/mocha/issues/4701
Is this a breaking change (major release)? No
Is it an enhancement (minor release)? No
Is it a bug fix, or does it not impact production code (patch release)? Yes
=> Fix error rethrow from cwd-relative path js config file

karma.conf.js
This karma config set CSP header for browser test to prevent evalError regression in future.
When I test it with mocha@8.3.0, `EvalError` occurred as I expected.
```bash
$ npm start test.browser
> mocha@8.3.0 start
> nps "test.browser"
nps is executing `test.browser` : nps clean build test.browser.unit test.browser.bdd test.browser.tdd test.browser.qunit test.browser.esm test.browser.requirejs test.browser.webpack
nps is executing `clean` : rimraf mocha.js
nps is executing `build` : rollup -c
./browser-entry.js → ./mocha.js...
created ./mocha.js in 7.7s
nps is executing `test.browser.unit` : cross-env NODE_PATH=. karma start --single-run --colors
START:
wrote bundle to /Users/outsider/Dropbox/projects/github/mocha/.karma/Edward.kornet/26f394cf-2f4b-442f-b68d-8aafd4fe616e.rollup.js
29 07 …
```
=> Set CSP on karma to prevent evalError regression

.github/workflows/stale.yml
Recently some `stale` labelled PRs haven't been unstaled after adding a comment.
- upgrade _actions/stale_ to v4
- increase `operations-per-run` from default (30) to 200
=> GH actions: update 'Stale/close issues and PRs'

docs/index.md, example/config/.mocharc.js, example/config/.mocharc.yml
The `timeout` option is `typeof string` and the boolean negation does not work.
We remove any reference to `no-timeout` from our sample config files and documentation.
closes #4717
=> Docs: remove unsupported 'no-timeout' option

docs/index.md, example/config/.mocharc.js, lib/mocha.js
The global flag `/g` in a RegExp expression is behaving weirdly with Mocha's `--grep` option. The selection of tests based on the fullTitle seems wrong as tests get lost, but at the end it's just javascript.
```js
let reIgnore = /a/g;
console.log(reIgnore.test("a")); // true
console.log(reIgnore.test("a")); // false
console.log(reIgnore.test("a")); // true
console.log(reIgnore.test("a")); // false
```
Using a flag as `/g` or `/y` doesn't make any sense in this context. 
- improve `Mocha.prototype.grep` for better conversion of `string` into `RegExp`
- clarify documentation
Instead of re-using the same RegExp instance for checking each test, we could construct new instances:
```js
let reIgnore = /a/g;
console.log(new RegExp(reIgnore).test("a")); // true
console.log(new …
```
=> Docs: `grep()` using RegExp with global flag `/g`

docs/index.md, example/config/.mocharc.js, example/config/.mocharc.yml, lib/cli/run-option-metadata.js, lib/cli/run.js, lib/mocha.js, lib/runner.js, test/integration/options/failZero.spec.js, test/unit/mocha.spec.js
We add a new option `--fail-zero` which exits the test script with `exit-code: 1` when no test have been found. Currently the `exit-code` would be zero. This flag is especially useful for CI/CD environments to prevent bugs remaining undetected.
New option `fail-zero`:
- boolean
- default: false
Before an `EVENT_RUN_END` event is emitted, we set `runner.failures = 1`. That way the script exits with `exit-code: 1`
closes #4062
=> Add new option "fail-zero"

docs/index.md, example/config/.mocharc.js, example/config/.mocharc.yml, lib/reporters/base.js, lib/reporters/json.js, test/reporters/json.spec.js
Extends `JSON` reporter with option to write output directly to file instead of a console.
closes #4131
- If output option was provided to JSON reporter:
- On `EVENT_RUN_END` it will write JSON output to given file - single call to `fs.writeFileSync()`
- Directory structure will be recursively created if needed - `fs.mkdirSync()`
- If test runs in browser it will throw unsupported error
- Unit tests has been updated
- Verifies if reporter writes to given file same JSON content as it sets on the `runner` instance
- Verifies if reporter throws error if output option is provided and test runs in browser
- Diff is bigger unless you hide whitespace only changes because existing tests were put into `describe()` group
- Documentation has been updated
`xunit` reporter uses write stream and …
=> Add output option to JSON reporter (#4131)

docs/css/style.css, docs/index.md
I found our homepage width was unnecessarily stretched because of error codes table.
So, I prevent overflow table width and improve readability. Now it works like below.
=> docs: fix broken table width under 450 screen width

docs/index.md, package.json
We add a complete, improved `--delay` example to our docs.
`--delay` is especially useful for dynamically generating tests, when `top-level-await` (only ESM) is not available.
=> Docs: add complete '--delay' example

docs/index.md
Add instructions of how to use `root hook` plugins in the browser.
closes #4639
=> Docs: Usage of 'root hook' plugins in the browser

docs/css/supporters.css
We have backer images with `width<32px`. The current spritesheet looks like this:
After this PR:
We add `-sprite-padding: 0 10;` to the CSS class `backer`. I got this solution from assetgraph-builder maintainers in gitter chanel.
This change has no effect on netlify deploy-previews, since the sprite image is generated for production deploys only.
closes #4752
=> Website: improve backers' sprite image

lib/suite.js, test/unit/suite.spec.js
Other projects (such as [Nigthwatch.js](https://github.com/nightwatchjs/nightwatch)) may be relying on these events in order to be able to extend the test suite object during the parsing cycle. 
None.
These is a minimal risk change and it has been reviewed in https://github.com/mochajs/mocha/issues/4760.
=> Remove listing of EVENT_SUITE_ADD* events as deprecated (#4760)

lib/nodejs/esm-utils.js, test/integration/esm.spec.js, test/integration/fixtures/esm/loader-with-module-not-found/loader-that-recognizes-ts.mjs, test/integration/fixtures/esm/loader-with-module-not-found/test-that-imports-non-existing-module.fixture.mjs, test/integration/fixtures/esm/loader-with-module-not-found/test-that-imports-non-existing-module.fixture.ts, test/integration/helpers.js
When loading test files, there is a heuristic that tries to determine whether to `import` or `require` them. This heuristic failed in the presence of a loader that recognizes filenames that are not `.js/.mjs`. In this case, when `require`-ing the file, Node.js does not throw `ERR_REQUIRE_ESM` (because of the different extension) but rather a `SyntaxError` saying that a CJSJ cannot use `import`.
I added some more code to this heuristic to deal with the problem by checking if the error is the aforementioned syntax error, and if so, throw the original …
=> Fixes #4803: wrong error thrown if loader is used

docs/_data/supporters.js, netlify.toml
Netlify runs on node 12, but 12 is a pretty old version.
- I updated it to Node 16
- _supporter.js_: replace `rmdir` by `rm`
- netlify settings: load netlify build image `focal` instead of `xenial`
=> Run netlify with Node 16

docs/index.md, lib/nodejs/buffered-worker-pool.js, package-lock.json, package.json, test/integration/fixtures/parallel/testworkerid1.mjs, test/integration/fixtures/parallel/testworkerid2.mjs, test/integration/fixtures/parallel/testworkerid3.mjs, test/integration/parallel.spec.js
This change is similar to https://github.com/mochajs/mocha/pull/4463 but is cleaner as is uses a new feature from workerpool (`onCreateWorker`) to override each process environment when each process is launched. I'm copying most of the description.
This change addresses #4456. It adds a MOCHA_WORKER_ID environment variable that is unique for each worker, so that it may be used for by any test resources that need to use global resources (network ports, filesystem paths, etc.) but ensure that these are unique in order to avoid conflicts during parallel …
=> Assign each worker a worker id in parallel mode.

docs/_includes/default.liquid, docs/css/style.css
In the narrow width screen, our sponsor logos disapear except the wallaby logo. 
Now, all sponsor logos are displayed.
Under 320px width, logo size is not good, but it's fine over 320px width.
=> doc: fix to show sponsors in narrow view

.github/ISSUE_TEMPLATE/bug_report.md, lib/cli/config.js, test/node-unit/cli/config.spec.js, test/node-unit/cli/fixtures/bad-require.fixture.js
While loading a js/cjs config file, Mocha uses the cwd-realtive path and as a fallback the module-relative path.
Edge case: a config file is successfully found, but its loading fails due to a bad require. There is no sense in using the fallback for a second file search which results in an incorrect error message.
We add a `require.resolve()` check which throws in case no config file can be found on the cwd-relative path. If it fails, retry again using the fallback path.
closes #4781
=> Fix loading of config files

lib/runner.js, test/integration/fixtures/options/dry-run/stack-size.fixture.js, test/integration/options/dryRun.spec.js
`dry-run` mode: since the tests are not executed, but triggered only into an empty synchronous run, there is a potential risk of `RangeError: Maximum call stack size exceeded`.
For each test we add an asynchronous function call with `Runner.immediately()`. We pay a slight performance costs for this which is insignificant in `dry-run` mode. 
closes #4838
=> Fix: potential call-stack crash when using 'dry-run' option

lib/cli/run-helpers.js, lib/mocha.js, test/browser-specific/fixtures/webpack/webpack.config.js, test/node-unit/cli/run-helpers.spec.js, test/node-unit/mocha.spec.js
When developing a third-party reporter, Mocha misdiagnoses an error coming from within the reporter as the reporter module not being found.
- _lib/cli/run-helpers.js_: fix CLI plugin entry point
- _lib/mocha.js_: fix/simplify `reporter()` when used programmatically via Mocha API
- adapt existing tests
- adapt webpack configuration
closes #3596
=> Fix: wrong error thrown while loading reporter

docs/index.md, lib/nodejs/parallel-buffered-runner.js, lib/runner.js, package-lock.json, package.json
11ty has upgraded to [1.0.0](https://github.com/11ty/eleventy/releases/tag/v1.0.0).
I checked diff for our docs between current docs and new docs with 1.0.0. It's the same.
There were a few changes for 11ty 1.0.0.
1. `include` need quotes
2. parseError with `@param {{files: string[], options: Options}}` jsdoc. So, I specified details of opt object. 
```bash
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] > Having trouble rendering liquid template ./docs/api/nodejs_parallel-buffered-runner.js.html
`TemplateContentRenderError` was thrown
[11ty] > unexpected token at ": string[], o...", file:./docs/api/nodejs_parallel-buffered-runner.js.html, line:317, col:13
`ParseError` was thrown
[11ty] > unexpected token at ": string[], o..."
`AssertionError` was thrown:
[11ty] …
```
=> docs: upgrade 11ty to 1.0.0

.browserslistrc, .github/workflows/browser-test.yml, .github/workflows/mocha.yml, docs/index.md, package.json
We drop support of Node v12 which will be end-of-life: 2022-04-30
=> Drop support of Node v12

lib/reporters/html.js
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
It would also be possible to use `substring()` instead of `slice()`
Best to not use deprecated functions
No more deprecated functions
None
None so far
=> chore: replace deprecated String.prototype.substr()

package-lock.json, package-scripts.js, package.json
- we remove **coffee-script** which is deprecated
- and add **coffeescript** which transpiles to ES6 (we dropped IE11)
=> devDeps: upgrade 'coffee-script' to 'coffeescript'

docs/_data/supporters.js
Our site is deployed every night in order to add the newest backers. The download of our backers' logos from OpenCollective has recently failed in dozens of cases with `Error: socket hang up`. 
- `open_timeout` (alias of `timeout`): we raise this value to 30000ms in order to avoid connection timeouts when dozens of requests run concurrently with _needle_.
- we fix bug in calculation of `successRate`.
- we raise `PRODUCTION_SUCCESS_THRESHOLD` to 90%.
I have `cherry-pick`ed this commit to the `mochajs.org` branch for an immediate fix of our site.
=> Site: fix supporters' download

lib/runner.js, test/unit/runner.spec.js
In Mocha v9.0.0 the Runner constructor signature `Runner(suite: Suite, delay: boolean)` has been deprecated, see #4646.
We remove mentioned `Runner(suite: Suite, delay: boolean)`.
Instead use an option object: `Runner(suite: Suite, {delay: boolean})`.
=> Remove deprecated Runner signature

docs/index.md, package-lock.json, package.json, scripts/karma-rollup-plugin.js, test/integration/options/ignore.spec.js
This is a **breaking change** and applies to the usage of `--ignore` (alias: `--exclude`) option in **Windows**.
see [Minimatch docs](https://github.com/isaacs/minimatch#windows)
> **Please only use forward-slashes in glob expressions.**
Though windows uses either `/` or `\` as its path separator, only `/` characters are used by this glob implementation. You must use forward-slashes **only** in glob expressions. Back-slashes in patterns will always be interpreted as escape characters, not path separators.
Note that `\` or `/` will be interpreted as path separators in paths on Windows, and will match against `/` in glob expressions.
So just always use `/` in patterns.
| dependencies | from | to |  |
|------------|----------|----------|----------|
| minimatch | 4.2.1 | 5.0.1 | breaking …
=> Deps: upgrade 'minimatch'

.github/workflows/mocha.yml
In order to reduce CI waste, we ignore changes to `*.md` and `docs/**` files on `push` and `pull_request` events.
Our CI tests aren't executed anymore, however the netlify/deploy-preview will still be build.
=> CI: don't run tests for changes on documentation files

docs/index.md
Hi, I was reading through the documentation and I noticed that `--fgrep` link was redirecting to the localhost. The link is located in the `Parallel` section, right under [Exclusive tests are disallowed](https://mochajs.org/#exclusive-tests-are-disallowed)
- Updates the link with to link the just header without the host.
- Remove the localhost reference
=> fix: docs parallel fgrep url fix

.github/workflows/mocha.yml
When a maintainer pushes a commit to a feature branch linked to an open PR, two events `push` and `pull_request` are emitted. To prevent our workflow `Tests` from executing twice, we skipped the `pull_request` workflow.
As a consequence `coveralls` doesn't work correctly anymore since it's based somehow on the `pull_request` event.
For forked PR's there is only one event emitted which is `pull_request`. 
On a `push` event we check with `gh-find-current-pr` wether an open PR exists. If yes, then we skip the `push` workflow. So before this PR, we skipped the `pull_request` event, now we skip the `push` event.
=> CI: conditionally skip 'push' event

lib/nodejs/esm-utils.js, test/integration/diffs.spec.js, test/integration/glob.spec.js, test/integration/no-diff.spec.js
Node version v12 has been dropped in #4845.
We remove ESM code which adressed Node versions <= 12.
=> ESM: remove code for Node v12

.github/workflows/mocha.yml
Replaces Node v17 by v18.
End-of-life of v17 is 2022-06-01, see [the release schedule.](https://nodejs.org/en/about/releases/)
=> ci: add Node 18

docs/index.md, lib/cli/commands.js, lib/cli/run.js
Github has deprecated git.io and will be [disabling all links on April 29th](https://github.blog/changelog/2022-04-25-git-io-deprecation/).
This PR replaces all git.io shortened links with the URL they redirect to.
=> refactor: replace git.io short link

lib/nodejs/parallel-buffered-runner.js, package-lock.json, package.json
We've introduced [@ungap/promise-all-settled](https://www.npmjs.com/package/@ungap/promise-all-settled) in #4476. 
And Node.js support [Promise.allSettled](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled) in Node 12.9.0.
So, we don't need polyfill anymore because we support Node 14+.
We don't need polyfill anymore.
dependency is reduced.
N/A
=> Use standard Promise.allSettled instead polyfill

lib/utils.js
Fix the regular expression for function `clean` in `utils.js` to avoid potential Regular Expression Denial of Service (ReDoS) vulnerabilities.
The ReDoS vulnerabilities of the regex  `/^function(?:\s*|\s+[^(]*)\([^)]*\)\s*\{((?:.|\n)*?)\s*\}$|^\([^)]*\)\s*=>\s*(?:\{((?:.|\n)*?)\s*\}|((?:.|\n)*))$/` are mainly due to the overlapped sub-patterns `\s+[^(]*`  and `((?:.|\n)*?)\s*`.
We can ignore `\s` first, because in the end, we can also deal with `\s` using the `trim` function (see the code below）https://github.com/mochajs/mocha/blob/8421974e8d252e2ef11602d15bed178e4f5f4534/lib/utils.js#L92
So I am willing to suggest that you replace the ReDoS-vulnerable regex  `/^function(?:\s*|\s+[^(]*)\([^)]*\)\s*\{((?:.|\n)*?)\s*\}$|^\([^)]*\)\s*=>\s*(?:\{((?:.|\n)*?)\s*\}|((?:.|\n)*))$/` with the safe …
=> fix the regular expression for function `clean` in `utils.js`

lib/browser/progress.js, mocha.css
Adds CSS to support prefers-color-scheme: dark as well as a small bit of JavaScript for the progress indicator.
Change the progress indicator to use SVG which can by styled by CSS. But one change at a time suggests that should be a separate change.
Because bright screens can be annoying in certain situation. The motivation for adding a dark mode was I was working on a flight. All the window shades are pulled down. All the terminals and editors I run were in dark mode but then when I went to run the tests, BOOM!, I'm lighting up all the seats around me. …
=> Support color scheme dark

mocha.css
Adds the increased visual emphasis as mentioned in #4911.
<table>
<thead>
<tr>
<th>Light mode</th>
<th>Dark mode</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
n/a
n/a
Users can more easily see the replay buttons.
n/a
* Fixes #4911
* Patch, bugfix
=> fix: increase contrast for replay buttons

karma.conf.js
I contacted Saucelabs for support and was adviced to temporarily pin the version of the Firefox GeckoDiver to 0.30.0 while waiting for Karma's issue to be resolved.
fixes #4930
=> CI: workaround for firefox error

.github/workflows/stale.yml
[GitHub Actions deprecated Node.js 12](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) and [actions/stale support Node.js 16](https://github.com/actions/stale/releases/tag/v5.0.0).
Updating `actions/stale` to v6 will [the deprecation warning](https://github.com/mochajs/mocha/actions/runs/3246673616).
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/stale
=> ci: update stale action

docs/index.md
The "Command-Line Usage" section is split in 2 without any gain, as can be seen in the screenshot below.
I'm removing the "Command-Line Usage" which is written in the middle of the "Command-Line Usage" section.
---
Original header: https://mochajs.org/#command-line-usage
Duplicated header: https://mochajs.org/#command-line-usage-1
N/A
N/A
Make documentation on using the command line easier to read.
N/A
It does not impact production code, only documentation.
=> docs: remove duplicated header "command-line usage"

package-lock.json, package.json
Remove unused 3 dependencies.
* [configstore](https://www.npmjs.com/package/configstore)
* It introduced in https://github.com/mochajs/mocha/commit/21371633e704c0735c54909f92cc3afed7eefdb6 . But It appears to have been added by mistake from the beginning.
* [through2](https://www.npmjs.com/package/through2)
* It was introduced in https://github.com/mochajs/mocha/commit/a81e5558f086808b682b6d196b80893d2c8926f8 7 years ago for browserify. But I couldn't find where to use it in this commit.
* It looks like removed in [this commit](https://github.com/mochajs/mocha/pull/4293/files#diff-a08fedcb4437f2d1b8f2cc51ea58b2495f52e88e2134817342fcd645f7a73e2a) when we drop the browserify.
* [watchify](https://www.npmjs.com/package/watchify)
* It was introduced at …
=> deps: remove unused deps

lib/mocha.js, lib/nodejs/esm-utils.js, test/node-unit/esm-utils.spec.js, test/node-unit/mocha.spec.js
This PR adds ability to decorate ESM-module name right before it will be imported by passing `esmDecorator` function to `loadFilesAsync` method.
It helps to deal with ESM cashing issues just by adding some query parameters to modue name:
```js
mocha.loadFilesAsync({
esmDecorator: file => `${file}?foo=bar`
})
```
And it backwards compatible.
Note though that the sub-dependencies of the test files will not be reloaded.
- https://github.com/mochajs/mocha/issues/4655
It is an enhancement (minor release).
=> feat: ability to decorate esm module name before importing it

.github/workflows/browser-test.yml, .github/workflows/mocha.yml
Fix deprecation warnning on GitHub Actions
* Node.js 12 actions are deprecated on [browser test](https://github.com/mochajs/mocha/actions/runs/3613741323).
* `set-output` command is deprecated on [tests](https://github.com/mochajs/mocha/actions/runs/3669300442).
`set-output` will be removed on June 1st and Node.js 12 will be unsupported in this summer.
There are still warns for `coverallsapp/github-action@master`. But coveralls don't update their actions yet. We should wait it or consider another option.
=> Fix deprecated warn gh actions

.github/workflows/mocha.yml, package.json
Add Node v19 to test CI matrix.
Initial release: 2022-10-18
=> Add Node v19 to test matrix

package-lock.json, package.json, scripts/karma-rollup-plugin.js
=> chore: remove uuid dev dependency

lib/utils.js, package-lock.json, package.json, test/unit/utils.spec.js
=> chore: remove nanoid as dependency

package-lock.json, package.json, test/integration/helpers.js
Remove touch as dev dependency.
=> chore: remove touch as dev dependency

docs/index.md
It looks like `mocha/bin/mocha` isn't there anymore.
=> docs: use mocha.js instead of mocha in the example run

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/04-repository-tooling.yml, README.md
Fixes up issue query links. It was easier to merge to `master` then get make sure each issue query was correct in "production".
Also I noticed we'd been using `🛠️ Tooling: ` as the effective tooling issue title prefix, so updated the template to use that... then updated it to the even shorter `🛠️ Repo:` so folks don't get confused between it and end-user Mocha tools.
=> docs: touchups to labels and a template title post-revamp

docs/_includes/default.liquid
Adds alt text matching the image's current contents.
=> fix: add alt text to Built with Netlify badge

.github/workflows/compliance.yml
Brings in https://github.com/mtfoley/pr-compliance-action with two customizations to the default settings:
* `body-auto-close: false`: to be a bit more gentle to PRs
* `ignore-team-members: false`: in case we typo, we should be caught too
=> chore: add mtfoley/pr-compliance-action

eslint.config.js
Bumps the lint preset version so we can use `?.`.
=> chore: bump ESLint ecmaVersion to 2020

lib/reporters/base.js, lib/runner.js, test/reporters/base.spec.js, test/unit/runner.spec.js
Appends the full error stack chain for errors with causes.
Prior to the Error cause standardization, there was `VError` which I did a PR for supporting some years ago #2381. That one as primarily closed because an aversion to supporting random module hooks, which this now being a standard changes.
So I think this is now more a matter of:
* Should this be on by default?
* How should this be formatted?
All current browsers supports this property and Node.js as well since `16.x`.
See also eg:
* [V8 blog post](https://v8.dev/features/error-cause)
* [My blog …
=> feat: include `.cause` stacks in the error stack traces

lib/reporters/base.js
Eleventy wasn't being able to parse the JSDocs for the returned type on the getFullErrorStack function. Defining it as a new type and then referencing it on the function fixes the issue.
Running `npm run docs` on this branch should work now.
=> fix: eleventy template builds crash with 'unexpected token at ": string, msg..."'

lib/reporters/xunit.js, test/reporters/xunit.spec.js
Expose test file path for each test case in the `xunit` reporter.
```
<testsuite name="Mocha Tests" tests="2" failures="0" errors="0" skipped="0" timestamp="Tue, 17 May 2022 21:10:34 GMT" time="0.001">
<testcase classname="Array #indexOf()" name="should return -1 when the value is not present" file="/path/to/test/array.js" time="0"/>
<testcase classname="Set #has()" name="should return false when the value is not present" file="/path/to/test/set.js" time="0"/>
</testsuite>
```
The test file path was already added to other reporters in this PR:
* https://github.com/mochajs/mocha/pull/4219
It seems the file path can be added to each reporter as needed.
* Can be easier to find test file from file path instead of just test name, especially when overlapping/similar/identical test names are …
=> feat: add file path to xunit reporter

docs/index.md
Fixes #4868.
Fix documentation about how shell expansion works on UNIX.
I removed incorrect information and added the equivalent correct information. I may have been more verbose than necessary, but it seemed like the documentation was trying to be informative here, so I continued providing the supplemental information.
This is a documentation fix. It removes erroneous information in core which should not be there.
The documentation will be less wrong.
This may result in people being less confused.
#4868
=> docs: fix documentation concerning glob expansion on UNIX

.github/dependabot.yml
Noticed that some of our GitHub Actions are quite outdated. Thought we could try out this little dependabot config before #5055 gets set up
=> chore: activate dependabot for workflows

docs/changelogs/CHANGELOG_V3_older.md, docs/index.md, lib/nodejs/reporters/parallel-buffered.js, lib/nodejs/serializer.js, package-scripts.js, test/integration/README.md
=> chore: fix some typos in comments

package-lock.json, package.json
Compatibility with newer @types/node releases for typescript users
=> feat: allow using any 3.x chokidar dependencies

.github/ISSUE_TEMPLATE/config.yml
I personally think we should allow for blank issues even though we might prioritize them lower. Not all issues fit into pre-defined templates and I know myself that I get very frustrated when I'm being forced to use a template that might not fit the issue that I need to open with the team.
I can take it upon myself to triage all the blank issues if that's the sticking point.
=> chore: allow blank issues

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/01-bug.yml, .github/ISSUE_TEMPLATE/02-documentation.yml, .github/ISSUE_TEMPLATE/03-feature-request.yml, .github/ISSUE_TEMPLATE/04-repository-tooling.yml, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/compliance.yml, MAINTAINERS.md, PROJECT_CHARTER.md, README.md, docs/API.md, docs/README.md, docs/api-tutorials/custom-reporter.md, docs/changelogs/README.md, docs/index.md
Roughly a straightforward find-and-replace.
Once this is approved, I can rename the branches here and in github.com/mochajs/mocha-examples.
=> chore: rename 'master' to 'main' in docs and tooling

package-lock.json, package.json
Adds a `^` range to the following packages related to Yargs:
* `yargs`: no new _minor_ versions available - just new majors
* `yargs-parser`: new minor versions available, up to `20.2.9`
* `yargs-unparser`: latest version; hasn't been updated in 4 years
=> feat: allow ^ versions for yargs packages

docs/index.md
This is a documentation only change.
I couldn't find any reference to `describe` not supporting an async callback. It seems like a natural conclusion to draw, given mocha specializes in async tests, and given `it` and hook do.
I spent considerable time trying to figure out why an async test was failing in one of my modules before I discovered the reason deep in an issue discussion (https://github.com/mochajs/mocha/issues/2975#issuecomment-1004176440)!
This is a documentation change.
I hope that this helps others design their test suites (I saw a number …
=> docs: Add warning about async callback for describe

README.md
=> docs: remove outdated license scan badge

package-lock.json, package-scripts.js, package.json
Although I like the idea of making sure links are correct, this is always failing and we don't change the site much anyway. 
[`hyperlink`](https://www.npmjs.com/package/hyperlink) is rarely used and hasn't been updated in a few years. Long-term it'd be great to move to a system with built-in link checking, like [Docusaurus `onBrokenLinks`](https://docusaurus.io/docs/api/docusaurus-config#onBrokenLinks) / other bits mentioned in https://github.com/withastro/starlight/discussions/946.
=> chore: remove failing hyperlink linkcheck task

.github/workflows/mocha.yml
Ever since the original move to GitHub Actions almost 4 years ago its been `windows-2019` that's been in use.
I'm thinking we should always use `-latest` when possible
=> ci: update to `windows-latest` in actions

lib/nodejs/serializer.js, test/integration/fixtures/parallel/non-circular-error.mjs, test/integration/parallel.spec.js
Turns out there are no existing tests for the case of having both `--parallel` and `--retries` enabled. The problem is that the new circular-reference-breaking logic from #5032 was also being run on other properties in `result` - not just `result.error`.
=> fix: crash with --parallel and --retries both enabled

.eleventy.js, docs/_data/supporters.js
Went through and created a somewhat better filter. A good stopgap measure at least.
=> docs: improve filtering

package.json
Follow up to #5186 / #5189. The release-please changelog entry didn't conform with the markdown linting, lets exclude it (at least for now)
=> chore: fix failing markdown linting

package.json
`prepublishOnly` ran `test`which ran the `test-browser` which tried to run saucelabs tests and that made the build fail and the release not happen.
This removes it the tests, those are handled in other GitHub Action jobs.
=> fix: make release-please build work

LICENSE, README.md, docs/README.md
* Fixes the test badge
* Updates some copyright years
* Removes saucelabs and fossa embeds
* Uses local logo rather than logo from unknown CDN
* Reorders badges so that package related badges are on the top and community related ones below
=> docs: update README, LICENSE and remove outdated

FUNDING.md, README.md
These guidelines were created by us Mocha maintainers with intent of being used for Mocha.
When #5197 is merged, do a follow up that adds the collective funds guidelines badge to the README.
=> docs: adopt Collective Funds Guidelines 0.1

mocha.css
Remove `:is` to prevent CSS breaking in older browsers.
This is also more consistent with older existent CSS which did not use `:is()` in the same file, such as [L318-L319](https://github.com/mochajs/mocha/blob/v10.7.3/mocha.css#L318-L319).
=> fix: remove `:is()` from `mocha.css` to support older browsers (#5225)

docs/index.md
I pinned `chai` to version 4 in the browser example. Since chai@5, the assertion library is distributed as a JavaScript module and doesn't add methods to the global scope. By pinning the version to the previous version 4 we make sure that the example still works.
We could update the example to use chai@5 as a module but I figure this would be a quick fix to the issue.
=> docs: pin chai to version 4 in browser example

docs/index.md
- criterias to criteria, already plural
- priorty to priority, typo
Used Code Spell Checker VS Code extension by Street Side Software to spell-check the file with its default dictionary. Ignored some flagged words like "DSLs" and "behaviour" as I figured those were acceptable.
=> docs: typos in mochajs.org

lib/reporters/html.js
Fix inaccurate suite/test links that may hit unrelated tests:
- Add '^' and ' ' for a suite link so that a link for `Case1` won't hit `Case10 test1`.
- Add '^' and '$' for a test link so that a link for `CSS` won't hit `should fix invalid CSS`.
=> fix: use accurate test links in HTML reporter

lib/cli/options.js, test/node-unit/cli/options.spec.js
Handle the corner case which can happen if:
- You had a perfectly good `package.json` which npm was happy with
- You decided to put `mocha` configuration inside your `package.json`
- You left a stray comma in there, because you are used to more sensible configuration file formats ;-)
- Instead of running `npm test` you ran `mocha` directly (with `npx` or just `mocha.js`)
As detailed here: https://github.com/dhdaines/mocha-5141
=> fix: handle case of invalid package.json with no explicit config

.github/workflows/nightly-site-deploy.yml, lib/reporters/html.js
Fix as mentioned in the [related issue comment](https://github.com/mochajs/mocha/issues/5102#issuecomment-1966919750).
=> fix: test link in html reporter

.eleventy.js
The `docs/_site` directory isn't being populated with html files. I think it's because Eleventy is respecting `.gitignore` settings that exclude them. Adding this line back in -essentially reverting https://github.com/mochajs/mocha/pull/5191/files#diff-c306e0a99961a16f5c5c83996caa0958b94006d97f97475049ea3a08036bb5b0L49- fixes it locally.
=> chore: fix docs builds by ignoring gitignore again

docs/example/tests.html
Chai 5 does not support CJS. Chai 4 does. 4.5.0 is the latest in that major.
💖
=> docs: downgrade example/tests chai to 4.5.0

lib/cli/lookup-files.js, package-lock.json, package.json, test/integration/options/parallel.spec.js
Bumps the `glob` version range in `package.json`. We can't yet use `glob@11`, as it only supports Node.js 20 up and Mocha 11 still supports Node.js 18.
The only change to JS source code is a manual `'en'` alphabetical sort of `glob.sync` results. This is to preserve the legacy behavior of what order test files are found and run: https://github.com/mochajs/mocha/pull/5250/files#r1840469747.
I tested this on the https://github.com/eslint/eslint and https://github.com/Microsoft/TypeScript projects and all tests reported passing.
=> feat: bumped glob dependency from 8 to 10

.github/CONTRIBUTING.md
Correct an incorrect/outdated `status: accepting prs` link in the Contributing Guidelines. I copied the new link from [line 82](https://github.com/mochajs/mocha/blob/4c558fb83ca5d7e260961b1ebfddcd377017a608/.github/CONTRIBUTING.md?plain=1#L82).
=> docs: correct outdated `status: accepting prs` link in the Contributing Guidelines

docs/index.md
Changes version annotations from "New in vX.Y.Z" to "Since vX.Y.Z".
=> docs: replace "New in" with "Since" in version annotations

lib/cli/cli.js
When node is run with [--frozen-intrinsics], a `TypeError` is thrown when any intrinsic objects or their properties are modified.  This occurs when attempting to set `Error.stackTraceLimit`.  To avoid exiting due to an uncaught exception, catch the exception, debug log it, and continue.
[--frozen-intrinsics]: https://nodejs.org/api/cli.html#--frozen-intrinsics
=> fix: catch exceptions setting Error.stackTraceLimit

docs/_data/usage.js, package-lock.json, package.json
Replaced `strip-ansi` with `util.stripVTControlCharacters`
=> chore: replace `strip-ansi` with `util.stripVTControlCharacters`

.github/workflows/mocha.yml, .github/workflows/npm-script.yml, .github/workflows/release-please.yml
Since LTS version 22.12.0 is causing crashes, pins us to 22.11.0 for now.
We'll want a followup issue to remove the pin once a new LTS version of Node is released.
=> chore: pin node-lts tests to 22.11.0

.github/workflows/mocha.yml, package-lock.json, package.json, test/integration/helpers.js, test/integration/options/watch.spec.js
This updates the codebase to remove two uses of `fs-extra` by newer `fs` built-in functions. The code changes are based on the implementation of `fs-extra@10.1.0` (which is the version of `fs-extra` recorded in the project's lockfile).
=> refactor: replace `fs-extra` with newer `fs` built-ins

lib/runnable.js, lib/runner.js
- Document the `Runner.constants` value used by reporters
- Mention the "missing" documentation in `Runnable` class
- `Runnable.prototype.xyz` calls are not published to the API doc site, leading to confusion about which properties are included in a `Runnable` object, like a `Test` or a `Hook`.
=> docs: improve third-party reporter docs

lib/cli/cli.js, lib/cli/collect-files.js, lib/cli/options.js, lib/cli/run-helpers.js, lib/cli/run.js, package-lock.json, package.json
Per the issue, switches from [`ansi-colors`](https://www.npmjs.com/package/ansi-colors) to the smaller [`picocolors`](https://www.npmjs.com/package/picocolors) for colorization. It seems to be a drop-in replacement.
=> fix: switch from ansi-colors to picocolors

docs-next/public/example/Array.js, docs-next/public/example/tests.html, docs-next/src/content/docs/index.mdx
Copies the file over to the [Astro `public/` directory](https://docs.astro.build/en/basics/project-structure/#public) with only one, minimal change: changing the favicon extension to the new site's `.svg`.
Note that the new link in `docs/index.mdx` doesn't work locally because the local site is still configured with a base path of `next/`. I couldn't figure out how to get the relative link to work for both a local base path and a deployed site. But this should point to the right link in production, I think.
=> docs: add example/tests.html to docs-next

lib/cli/watch-run.js, package-lock.json, package.json
Current chokidar is bundled with tons of spam deps including `braces` which trigger some audit alert.
All test are working. It supports globs unlike https://github.com/mochajs/mocha/pull/5215
=> fix(deps): update chokidar to v4

docs-next/src/content/docs/running/browsers.mdx, docs/index.md
Goes with the same version support range strategy as https://github.com/mochajs/mocha/issues/5226#issuecomment-2445026404: the major versions of evergreen browsers as of the oldest supported Node.js.
=> docs: mention explicit browser support range

.github/release-please/config.json, .github/workflows/release-please.yml
Removes the `prerelease` and `versioning` properties as suggested in https://github.com/mochajs/mocha/issues/5345#issuecomment-2872556628 & https://github.com/mochajs/mocha/issues/5345#issuecomment-2872679272.
=> chore: remove prerelease setting in release-please config

package-lock.json, package.json
Bumps the production dependency. Some dev dependencies still rely on 4.x or 5.x, so the `package-lock.json` is a bit bigger now.
See https://github.com/kpdecker/jsdiff/blob/master/release-notes.md for diff's changelog. 6.x had a lot of breaking changes. I couldn't get any to cause bugs here.
=> feat: bump diff from ^5.2.0 to ^7.0.0

CHANGELOG.md
Updates the changelog to mention the breaking bugfix and link to the issue.
I can also update https://github.com/mochajs/mocha/releases/tag/v11.1.0 if this PR's phrasing is approved.
=> docs: added CHANGELOG.md note around 11.1 yargs-parser update

eslint.config.js, lib/nodejs/esm-utils.js, test/compiler-cjs/test.js, test/compiler-cjs/test.js.compiled, test/compiler-cjs/test.ts, test/compiler-cjs/test.ts.compiled, test/compiler-fixtures/js.fixture.js, test/compiler-fixtures/ts.fixture.js, test/integration/compiler-cjs.spec.js
This allows compilers based on `require.extensions` continue to work, like `ts-node` with Node.js built-in TypeScript support enabled.
Hopefully unblock https://github.com/nodejs/node/pull/57298.
Fixes: https://github.com/mochajs/mocha/issues/5314
Fixes: https://github.com/mochajs/mocha/issues/5317
=> feat: use require to load esm

docs-next/src/content/docs/explainers/nodejs-native-esm-support.mdx, docs/index.md
Fixes: https://github.com/mochajs/mocha/issues/5396
The fix landed in node js main nodejs/node#58957 I belive we now should update the ESM support section of the documentation since this error has been affecting even node LTS. I took the liberty to guess the next node.js version, shouldn't matter if they skip the 24.4.1 patch straight to a new minor, the point will still stand.
I was intentionally vague in the problem description and proposed workaround, and left a link to the original issue so if the person is curious to learn more / understand how the fix works. I want to optimize for the quick answers crowd, the curious crowd can delight itself reading the original issue.
=> docs: explain node import swallowing error

.github/workflows/mocha.yml
Adds the latest Node.js major `24` to `mocha.yml`.
The repo still has existing test instability (#5361, #5376) but that's not related to this PR. This PR shouldn't add any new failures.
💖
=> chore: also test Node.js 24 in CI

docs-next/src/content/docs/running/configuring.mdx, docs/index.md
`mocha bar.spec.js` doesn't necessarily run **only** `bar.spec.js`, it just ensures that that file/glob is matched along with whatever is in the config file. This can be misleading, so we're updating the docs to clarity.
=> docs: document merging of special `spec` option

docs-next/README.md, docs-next/src/content/docs/index.mdx, docs/css/style.css, docs/index.md
Current site now has a custom banner:
New site's `mochajs.org` bold text is now a link back to the current homepage:
Minor cleanup of `docs-next/readme.md` as well :)
=> docs: add banner from old site to new site, link from new to old

docs-next/astro.config.ts, docs-next/src/content/docs/explainers/shared-behaviours.mdx, docs/api-tutorials/jsdoc.tutorials.json, docs/api-tutorials/shared-behaviours.md
=> docs: migrate shared behaviours to docs-next

docs-next/astro.config.ts, docs-next/src/content/docs/explainers/spies.mdx
- Direct migration of wiki/Spies content to docs-next
- Part of #5248 wiki migration effort
This is a direct migration of the [Spies wiki page](https://github.com/mochajs/mocha/wiki/Spies) to `docs-next/src/content/docs/explainers/spies.mdx`.
- Added to docs-next (will add to legacy docs in follow-up)  
- Content placed in explainers section
=> docs: migrate Spies wiki page to explainers

.github/workflows/mocha.yml, test/integration/plugins/root-hooks.spec.js, test/node-unit/reporters/parallel-buffered.spec.js
OK, the issue wasn't technically open, but we had worked around it by simply not bumping CI. This PR expects Node 20.19.x to be buggy for now and links to the relevant Node issue where it should be fixed. No updates there since January though, so bumping anyway.
=> chore: bump CI to use 20.19.4, 22.18.0, 24.6.0

.github/workflows/mocha.yml, docs-next/src/content/docs/getting-started.mdx, docs-next/src/content/docs/running/browsers.mdx, docs/index.md, package-lock.json, package.json
Applies the change in `package.json`'s `"engines"` > `"node"`, as well as docs.
💖
=> feat!: bump minimum Node.js version from 18.18.0 to 20.19.0
