mochajs/mocha

- bin/_mocha
> small fix: commander option for --expose-gc

- bin/mocha
I found myself having to patch this up and I thought it might help others too.
> ammended for deprecated customFds option in child_process

- lib/utils.js
- test/ms.js
- test/reporters/json.js
- test/reporters/nyan.js
- test/utils.js
Add tests to existing units(that untested).
> test(utils|ms|*): test existing units

- index.html
- index.md
Since @travisjeffery releasing a new version, it's time to update the docs.
> docs(website): update all relevant flags

- index.html
- index.md
Added a small note, as requested in https://github.com/mochajs/mocha/issues/267
> Fix #267, document relative require

- README.md
- index.html
- index.md
In reference to https://github.com/mochajs/mocha/issues/57
Hoping the example is concise enough to be helpful! Added section can be found here: https://github.com/danielstjules/mocha/blob/86f85bd66a67063acb859b4321762c95dff77b5a/index.md#meta-generated-test
> Fix #57: Add section on meta-generated tests

- package.json
> chore(package.json): add a8m as a contributor

- lib/reporters/base.js
- lib/utils.js
- test/reporters/base.js
This PR fix issue #1241, and show string diff as a raw data.
> fix(reporter/base): string diff - issue #1241

- lib/utils.js
- test/acceptance/utils.js
Use `toString` for invalid date object
> fix(utils/stringify): fix issue #1660

- test/integration/fixtures/regression/issue-1327.js
- test/integration/regression.js
Tests more closely resemble the original: https://github.com/mochajs/mocha/blob/b1b4bf6ab66ece850f48c2d3b82c2e900f7406b5/test/regression/issue1327/case.js
> Sanity check for issue-1327.js

- test.js
> Removes accidentally commited test.js

- lib/runnable.js
This fixes #1700 and closes #1701.
Thanks to: Edwin Shin [eddies].
> Removes return statement irt #1700.

- bin/mocha
> Adding additional iojs flags

- bin/_mocha
- lib/mocha.js
- support/browser-entry.js
- test/grep.js
- test/integration/fixtures/options/grep.js
- test/integration/options.js
This PR replace #1650 plus I added some integration-tests for it.
@mochajs/mocha can we merge it to **v3.0.0**?
> feature(mocha/grep): improve grep - issue #808

- lib/reporters/markdown.js
- test/integration/fixtures/passing.js
- test/integration/reporters.js
Markdown reporter doesn't currently work in master. See #1875
> Fix 1875: Markdown reporter exceeds maximum call stack size

- test/integration/reporters.js
After a few dozen jobs on travis, I noticed a single failure from this test. Looks like the root cause is that the time can exceed 0.
> Fix fragile xunit reporter spec

- test/reporters/nyan.js
> Fix typo in test/reporters/nyan.js

- bin/_mocha
Moves Mocha interface allocation to after require option has been processed to allow for use of custom Mocha UI's.
> Fixes #1794

- lib/mocha.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mochajs/mocha/1976)
> Simplify function call.

- LICENSE
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mochajs/mocha/2056)
> chore(license): update license year to 2016

- lib/reporters/landing.js
- lib/reporters/progress.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mochajs/mocha/2074)
> Fix: reporters with chalk functions (fixes #2073)

- lib/browser/events.js
Fix JSDoc in EventEmitter browser shim
> Fix JSDoc EventEmitter

- bin/_mocha
- bin/mocha
It is missing from available flags list and I would be nice to have it.
> Add --icu-data-dir flag for node

- package.json
> ensure browser-entry.js gets published; closes #2323

- lib/runnable.js
- test/runnable.js
> ensures slow() called w/o args does not blast value; closes #2311

- test/suite.js
> disregard function names when testing under Node.js 6.5.0; closes #2467

- lib/utils.js
- test/runner.spec.js
- test/utils.spec.js
- also removed component-related cruft
> ensure windows compat with stack trace filter; closes #2502

- lib/runnable.js
- test/integration/fixtures/regression/issue-1417.js
- test/integration/regression.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mochajs/mocha/2059)
> Fix #1417: Show actual error, not 'multiple calls to done()'

- README.md
Will look like this: 
It's kinda the best I managed after quite a few tries.
> Add Browser Support Matrix to README.md

- CONTRIBUTING.md
This text is a first pass at what should eventually appear on the site.  Eventually, I'd like this file to be simply links to the site.  It should be expanded and organized further.
[View it](https://github.com/boneskull/mocha/blob/6c820bc6cfb5f6940bc27be3b80a0d2f3749101b/CONTRIBUTING.md)
> expand / update CONTRIBUTING.md

- package.json
Closes #2644
https://greenkeeper.io/
> fix(package): update debug to version 2.6.0

- bin/_mocha
- lib/runnable.js
- lib/runner.js
> add --allowUncaught to Node.js; fix broken allowUncaught

- .github/CODE_OF_CONDUCT.md
> Added code of conduct

- test/browser/index.html
The bug seems to be only a typo.
> fixed array test name in mocha/test/browser/index.html

- test/integration/regression.spec.js
> Stop timing out

- test/unit/mocha.spec.js
> Update new tests to work in browser per test hierarchy reorganization

- package.json
> update karma-sauce-launcher URL for npm@5

- lib/runner.js
was mentioned in review for #3016
> fix incorrect grouping in conditional as result of linting

- Makefile
- test/integration/fixtures/options/delay.fixture.js
- test/integration/fixtures/retries/async.fixture.js
- test/integration/options.spec.js
- test/integration/regression.spec.js
- test/unit/duration.spec.js
- test/unit/timeout.spec.js
that's about it.  want to see if it works on appveyor though.
> reduce noise about slow tests; make a few tests faster, etc.

- test/browser/array.spec.js
- test/browser/index.html
- test/browser/large.html
* Finish the work started at 9bd9389c58e81b10bef9f4b2e5a54b77a026d2d0
* Fix Array test case. It’s not clear why `1` expected to be `-1`.
> Fix spec paths in test HTML files

- test/integration/options.spec.js
I was just feeling fussy about this.
> refactor "forbid pending" tests for DRY

- test/unit/throw.spec.js
Continuation of #2983 with fixes.
> fix invalid uncaught-exception-related tests

- bin/_mocha
- lib/mocha.js
- lib/reporters/base.js
- test/integration/fixtures/no-diff.fixture.js
- test/integration/no-diff.spec.js
- test/reporters/base.spec.js
this had diverged too much, so I'm fixing up the original PR here.
> continuation of #2536; closes #2514

- lib/utils.js
- test/node-unit/file-utils.spec.js
I am using mocha programmatically, along with its utility `lookupFiles`.
Upon calling `lookupFiles` A regular expression must be evaluated to lookup files although it is not needed in the majority of cases. Shifting the `re` variable definition down to where it is needed will avoid this issue.
The main reason for this change is to eliminate the requirement of always sending an array to the extensions parameter, moving the `re` variable definition to just right above where it is needed will achieve both goals.
An if statement with a default value for the extensions input param. The proposed version is the neatest and most verbose way to do it.
I am using mocha programmatically along with its utility, this is just a tiny enhancement. also it dictates less knowledge about the function …
> Move re variable definition in lookupFiles Utility

- MAINTAINERS.md
Link: [HERE](https://youtu.be/zLayCLcIno0)
This will help future contributors understanding mocha's codebase :)
> Added a link to the walkthrough video

- package.json
As per discussion in #3073, this field is problematic.
> remove engines.npm from package.json; closes #3073

- README.md
I think it is looking a bit better now 😄
> Update README.md for better readability [ci skip]

- lib/reporters/base.js
minor adjustment; probably doesn't make much of a difference, but seems more correct this way
N/A
N/A
* minor performance enhancement
* slightly more consistent reporting
none, I hope
N/A
> Ensure consistent calculation of duration

- docs/index.md
Docs change to add all supported Wallaby.js editors.
> Add all supported wallaby editors

- LICENSE
This pull request extends the licensing year to 2018.
> [Update] license year

- CHANGELOG.md
The PR url was wrong so I fixed it. Probably just a copy-paste error.
> fix PR url

- README.md
This removes the big fuss at the beginning of `README.md`.  There's now a smaller fuss near the bottom.
> update README.md; closes #3191 [ci skip]

- CHANGELOG.md
Typo.
N/A
N/A
The emoji displays.
N/A
N/A
> Fix typo in an emoji (docs)

- karma.conf.js
- lib/runnable.js
> fix debug msg in Runnable#slow; closes #2952

- docs/index.md
This is a proposition of doc precision. My English is not so good so don't hesitate to propose a rephrase if you find the idea good but the sentence is not OK for you
> doc precision for exclusive tests

- package-lock.json
- package.json
there were vulernabilities... now there are fewer.
> update packages per "npm audit fix"

- package-lock.json
- package.json
it keeps the other fixes as merged in 41cce5f1 and 42005f3d
> downgrade assetgraph-builder and svgo to make netlify work; closes #3401

- bin/mocha
This commit adds `--experimental-modules` to the list of Node flag recognized by Mocha. This flag is passed directly to Node and enables experimental native support for ESM modules.
- **Do nothing**: We could not add this option. This would require people to keep using `NODE_OPTIONS` for `--experimental-modules`.
This PR allows to use `mocha --experimental-modules foo.spec.js` instead of requiring the workaround `NODE_OPTIONS="--experimental-modules" mocha foo.spec.js`.
This addition is in line with the various `--harmony` flags that were added while …
> Whitelist `--experimental-modules` Node flag

- .lintstagedrc.json
we were missing some stuff. 
I think it does YAML too?
> ensure all JS (and JSON) files are prettified pre-commit

- MAINTAINERS.md
cc @mochajs/core 
- updated stuff about semver-* labels
- updated what qualifies as a breaking change
- updated some stuff around milestones
- and some stuff about branches
> updates to MAINTAINERS.md 

- docs/index.md
- package-lock.json
- package.json
- scripts/markdown-magic.config.js
- strip ansi stuff
- fix old content terminator
will  merge asap
> fix broken docs

- lib/cli/run-helpers.js
original discussion: https://github.com/mochajs/mocha/pull/3602#discussion_r241724526
> remove SIGINT handler for single runs; see #3570

- package-lock.json
- package.json
At least, I *think* it does.  @plroebuck seems to know more about this.
> upgrade supports-color; closes #1304

- .eslintrc.yml
- lib/growl.js
- package-lock.json
- package.json
also refactor to use modern JS in `lib/growl.js`; update ESLint rules accordingly
> use userland which; closes #3639

- .gitignore
was having some trouble with various temp files, so created this using the [VSCode gitignore extension](https://github.com/CodeZombieCH/vscode-gitignore).
> mega-upgrade of .gitignore [ci skip]

- docs/index.md
- lib/utils.js
Lots of cross-reference changes. Updates to HTML examples. Em-dashes.
NA
NA
Links will be altogether.
None to knowledge
Fixes #3382
semver-patch
> Documentation updates

- package-lock.json
- package.json
Upgrading the docdash library to ^2.0.0 per issue #3663 
N/A
This is need to take advantage of functionality of newer docdash versions
Newer features in new docdash versions
Possible dependency or document formatting issues. I spot checked generated docs and they seemed normal to me. 
Issue #3663
> Upgrade docdash version - issue #3663

- lib/cli/run-helpers.js
> fix --watch not finding any files to execute; closes #3748

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/support-question.md
As #3389 , I created issue templates. You can check [how it works in my repository](https://github.com/outsideris/mocha/issues/new/choose).
I created the templates from GitHub default templates and [babel](https://github.com/babel/babel/issues/new/choose). I'm not native English. So, feel free to point out wrong grammar or better expressions.
> improve issue template.

- .lintstagedrc.json
> autoformat markdown with prettier; closes #3773

- docs/.browserslistrc
- package-lock.json
- package.json
> Add autoprefixer to documentation page CSS

- package-lock.json
- package.json
> Upgrade yargs-parser dependency to avoid loading 2 copies of yargs

- docs/example/tests.html
Made 3 URL conversions to current package releases.
NA
Already part of core.
Uses current release of packages, requiring no further maintenance.
No impact to production code as it is just changing where it is getting the same code from.
Fixes #3810
semver-patch
> Update doc examples "tests.html"

- package-lock.json
- package.json
> upgrade node-environment-flags; closes #3868

- test/reporters/json.spec.js
Squelches STDOUT from test specification using sinon stub.
NA
NA
Easier to see test results.
None
semver-patch
> Remove noise output from JSON reporter test

- .lintstagedrc.json
- docs/index.md
- jsdoc.conf.json
- package-scripts.js
- ensure `.html` gets hit by prettier
- fix order in which docs are generated; let assetgraph process API docs
- fix broken links in custom reporter tutorial
- some auto-generated content in `docs/index.md` updated
> various doc-related fixes

- lib/utils.js
Adds a check for the minified version of mocha.js to the StackTraceFilter.
A regex pattern could be implemented instead of indexOf(), not sure if that's preferred.
Utils would have to be overloaded to provide the same behavior otherwise.
Allows the minified mocha version to exhibit the same filter behavior as designed.
Can't think of any.
closes #3921
> Add mocha.min.js file to stacktrace filter

- package-lock.json
- package.json
> update @mocha/docdash to v2.1.1

- package-lock.json
- package.json
> update @mocha/contributors to v1.0.4

- docs/example/Array.js
There is a variable redeclared in an example which would not work in some cases. In fact we do not have to redeclare this variable.
N/A
N/A
N/A
N/A
N/A
> fix: do not redeclare variable

- package-lock.json
- package.json
Bug fix by yargs-parser which affected Mocha.
closes #3899
> Update yargs to v13.3.0 and yargs-parser to v13.1.1

- docs/api-tutorials/custom-reporter.md
- lib/cli/options.js
- lib/mocha.js
- lib/reporters/base.js
- package-lock.json
- package-scripts.js
- package.json
When the docs are being built, a link scanner will check that all internal links are pointing at things that exist, thus avoiding broken links and bad user experiences.
Easier to spot mistakes in docs.
Longer build time
> Add link checking to docs build step

- CHANGELOG.md
> Updated CHANGELOG for v6.2.1

- test/integration/duplicate-arguments.spec.js
- test/integration/options/ui.spec.js
- test/integration/suite.spec.js
I tested all integration test file, can change runMocha to runMochaJSON.
There were few things I could change.
If we're not testing raw reporter output, we should use runMochaJSON() instead.
nothing
https://github.com/mochajs/mocha/issues/2595
* Is this a breaking change (major release)? no
* Is it an enhancement (minor release)? no
* Is it a bug fix, or does it not impact production code (patch release)? no
> 2595 Changed runMocha to runMochaJSON in test/integration

- package.json
See https://github.com/npm/rfcs/blob/latest/accepted/0017-add-funding-support.md
> Add funding information to package.json

- README.md
This updates `:coffee:` to ☕️ (emoji) in the README.md.
As the emoji form, it *should* then render as an emoji in other places like https://www.npmjs.com/package/mocha
Existing screenshot (MacOS, Firefox 70) for posterity:
FWIW, it is a non-ASCII character, though [Google's JavaScript style guide](https://google.github.io/styleguide/jsguide.html#non-ascii-characters) states:
> Tip: Never make your code less readable simply out of fear that some programs might not handle non-ASCII characters properly. If that happens, those programs are **broken** and they must be **fixed**.
---
* All new code requires tests to …
> docs: Replace :coffee: with emoji ☕️

- docs/index.md
Fix broken link of 'should' package
Shorten link of 'mochawesome' package
Enable link of 'should' package
--------
Closes #4139
> Broken links in docs

- docs/index.md
I tested some CLI options for support in browser context and updated the documentation.
This list of options available in browsers is not conclusive, yet.
> Docs: update browser options

- package-lock.json
- package.json
- _mkdirp:_ prototype pollution by _minimist_ => update to _mkdirp@0.5.3_ 
- _yargs-parser:_ prototype pollution => update to _yargs-parser@13.1.2_
- _yargs:_ update to _yargs@13.3.2_
> security: update dependencies mkdirp, yargs and yargs-parser

- .wallaby.js
also increase default timeout
Ref: #4198
> remove cruft from wallaby config

- .nycrc
should keep more garbage out of the coverage
> fix nyc ignorelist

- package-lock.json
- package.json
Update `@mocha/docdash` to 2.1.3. Fixes whitespace on mobile and issue with syntax highlighting colours.
Details in issues:
- https://github.com/mochajs/mocha/issues/4081
- https://github.com/mochajs/mocha/issues/3664
> Update mocha-docdash for UI fixes on API docs

- test/node-unit/mocha.spec.js
> rename fixtures to have .fixture.js extension

- .eslintignore
- .eslintrc.yml
- docs/js/avatars.js
Lint stuff in `docs/` that's not generated or vendored.
> add javascript in docs to eslint

- .eleventy.js
I do not know if this actually works, but it might.  I just happened upon this option as I was fiddling with other stuff.  Let's see what the netlify build looks like.
Ref: #3716
> smart quotes and such on website; closes #3716

- .travis.yml
- test/sanity/sanity.spec.js
- test/smoke/smoke.spec.js
- add notes about what it is intended to do, and what it cannot do
> renamed smoke test

- package-lock.json
- package.json
Fix: https://github.com/mochajs/mocha/issues/4331
> fix(vulnerabilty): update to serialize-javascript@3.1

- .travis.yml
- Removed serial travis job as tests runs in serial by default. 
Fix to #4326
> Remove serial travis job

- lib/cli/watch-run.js
- lib/errors.js
- lib/mocha.js
- lib/utils.js
> Modify: Fixing typos

- lib/utils.js
Invalid js reference link in lib/utils.js file. 
If you click the link, an error of 404 occurred in the document link in Map and Asign.
However, the create reference worked well. So I modified it to the same form as the one I created.
before: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map|MDN:Map
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign|MDN:Object.assign
after: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Custom_and_Null_obje …
> update js reference link (map, assign) in lib/utils.js

- .lintstagedrc.json
- test/assertions.js
- test/setup.js
also fixes `.lintstagedrc` which I broke.
> refactor assertions into unexpected plugin

- docs/_data/supporters.js
At Open Collective, we're starting to implement a few changes to help Collectives like yours filter undesirable contributions.
The goal is double:
- help you filter contributions and protect your image
- cut the incentive for these people to contribute in the first place
I'm aware of your previous efforts in this direction and I'm just extending it here, based on a categorization system that we started implementing.
Happy to discuss and iterate.
> Implement Open Collective categories for extended filtering

- .github/workflows/mocha.yml
was missing a space in the path!
> avoid deprecated add-path in GHA workflow

- .github/workflows/mocha.yml
> add node.js v15 to build matrix

- package-lock.json
> update deps for some vuln which is not applicable to mocha

- .github/workflows/mocha.yml
eslint job is not checking PRs properly.  I don't fully understand why
> test fix of eslint workflow

- lib/cli/collect-files.js
> refactor collect-files to be a little more simple

- lib/browser/growl.js
Bug-Fix - Fixes [Issue 4516](https://github.com/mochajs/mocha/issues/4516)
> fixes require path

- LICENSE
- README.md
Updated copyright end year from 2020 to 2021.
N/A
N/A
N/A
N/A
N/A
> Update copyright year in LICENSE

- README.md
Update README.md which is shown on Github and NPM with current sponsor(s) and backers.
> Update README incl. sponsors/backers

- lib/reporters/nyan.js
Directly find-and-replaces each call to the `write` function with a call to `process.stdout.write`.
> chore: inline nyan reporter's write function

- docs/_includes/supporters.md
Adds `sponsored` to the supporters template for the site.
> docs: add sponsored to sponsorship link rels

- test/integration/reporters.spec.js
> test: fix xunit integration test

- .github/CONTRIBUTING.md
> docs: remove outdated mailing list reference

- SECURITY.md
To fulfill the lifting at Tidelift we need to add a security policy (which we should have anyways)
> docs: add `SECURITY.md` pointing to Tidelift

- docs/index.md
visionmedia.github.io is not found, https://ladjs.github.io/superagent/docs/test.html works great :)
> docs: update SuperAgent site URL

- lib/nodejs/parallel-buffered-runner.js
- lib/runner.js
This PR fixes the document for `linkPartialObjects` methods:
- https://mochajs.org/api/runner#linkPartialObjects
- https://mochajs.org/api/module-parallel-buffered-runner-parallelbufferedrunner#linkPartialObjects
> docs: fix examples for `linkPartialObjects` methods

- docs/README.md
Adds a line to the readme for new developers :)
> docs: add instructions for hosting API docs

- docs-next/src/content/docs/declaring/dynamic-tests.mdx
- docs-next/src/content/docs/declaring/inclusive-tests.mdx
- docs-next/src/content/docs/declaring/pending-tests.mdx
- docs-next/src/content/docs/declaring/retrying-tests.mdx
- docs-next/src/content/docs/explainers/test-fixture-decision-tree.mdx
- docs-next/src/content/docs/features/assertions.mdx
- docs-next/src/content/docs/features/asynchronous-code.mdx
- docs-next/src/content/docs/features/hooks.mdx
- docs-next/src/content/docs/features/parallel-mode.mdx
- docs-next/src/content/docs/features/root-hook-plugins.mdx
- docs-next/src/content/docs/features/timeouts.mdx
- docs-next/src/content/docs/reporters/markdown.mdx
- docs-next/src/content/docs/reporters/xunit.mdx
- docs-next/src/content/docs/running/browsers.mdx
- docs-next/src/content/docs/running/cli.mdx
- docs-next/src/content/docs/running/configuring.mdx
- docs-next/src/content/docs/running/test-globs.mdx
Apply proofreading comments from #5246:
- fix some typos and grammar issues
- improve accessibility of some link texts
- add comment from docs to definition of help output
> docs: fix new website typos, improve readability

- .github/workflows/mocha.yml
When moving to Node 20.19.0, we are seeing consistent test failures, and it's unclear why. For now, it's best to clarify that we only support Node 20.18.3 and continue investigation on issues with Node ^20.19.0 separately.
We will still have flaky issues with Windows 20.18.3 as clarified in #5052. I had to mark this PR as "fixing" the issue in order to pass a separate PR validation. I will reopen #5052 after this PR is merged for further investigation.
> chore: Fix tests

- package.json
Reverts mochajs/mocha#5319
This change didn't help, let's clean up where we can :)
Ref #5315
> chore: Revert "chore: "Force" Netlify to use npm to build new site"

- docs-next/src/content/docs/getting-started.mdx
- docs/index.md
Updates in both the old site and the new.
> docs: update Node.js version requirements for 11.x

- .wallaby.js
- lib/cli/run.js
- test/integration/options/opts.spec.js
Reverts mochajs/mocha#5402, ref also https://github.com/mochajs/mocha/issues/5243
Sorry, missed that this was a semver-major!
Please adjust the PR title and body as you see fit and merge when convenient
> Revert "chore: cleanup references of --opts"

- docs/index.md
> docs: fix link to new site

- docs-next/astro.config.ts
- docs-next/src/content/docs/explainers/third-party-reporters.mdx
- docs/api-tutorials/jsdoc.tutorials.json
- docs/api-tutorials/third-party-reporters.md
> docs: migrate third party reporters wiki page to docs

- docs-next/astro.config.ts
Alphabetizes remaining sections the new site nav for consistency
> docs: alphabetize new site nav

- docs-next/src/content/docs/index.mdx
Add the `/next` base to the LinkButtons. Ref #5431 for related refactoring work, even that doesn't apply to LinkButton components though
> docs: fix link buttons in new homepage

- SECURITY.md
Removes trailing spaces from a recently-edited file :)
> chore: remove trailing spaces

- FUNDING.md
~- [ ] Addresses an existing open issue: fixes #000~
~- [ ] That issue was marked as [`status: accepting prs`](https://github.com/mochajs/mocha/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)~
~- [ ] Steps in [CONTRIBUTING.md](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md) were taken~
Quick update to our funding page to reflect that we've been paying ourselves $75 per hour since August 1.
> chore: update TSC Members' hourly rate to $75
